import type { Abbreviation } from "../../types/content";

export const abbreviations: Abbreviation[] = [
  {
    id: "abbr-bp",
    shortForm: "BP",
    expandedForm: "blood pressure",
    category: "clinical",
    meaning: "measurement of arterial pressure",
    ambiguous: false,
  },
  {
    id: "abbr-prn",
    shortForm: "PRN",
    expandedForm: "as needed",
    category: "document",
    meaning: "used when something should happen only when needed",
    ambiguous: false,
  },
  {
    id: "abbr-hr",
    shortForm: "HR",
    expandedForm: "heart rate",
    category: "clinical",
    meaning: "number of heartbeats per minute",
    ambiguous: false,
  },
  {
    id: "abbr-rr",
    shortForm: "RR",
    expandedForm: "respiratory rate",
    category: "clinical",
    meaning: "number of breaths per minute",
    ambiguous: false,
  },
  {
    id: "abbr-iv",
    shortForm: "IV",
    expandedForm: "intravenous",
    category: "route",
    meaning: "delivered into a vein",
    ambiguous: false,
  },
  {
    id: "abbr-po",
    shortForm: "PO",
    expandedForm: "by mouth",
    category: "route",
    meaning: "taken orally",
    ambiguous: false,
  },
  {
    id: "abbr-ml",
    shortForm: "mL",
    expandedForm: "milliliter",
    category: "measurement",
    meaning: "metric unit of liquid volume",
    ambiguous: false,
  },
  {
    id: "abbr-sob",
    shortForm: "SOB",
    expandedForm: "shortness of breath",
    category: "clinical",
    meaning: "trouble breathing or the feeling of not getting enough air",
    ambiguous: false,
  },
  {
    id: "abbr-npo",
    shortForm: "NPO",
    expandedForm: "nothing by mouth",
    category: "clinical",
    meaning: "do not eat or drink anything",
    ambiguous: false,
  },
  {
    id: "abbr-hx",
    shortForm: "Hx",
    expandedForm: "history",
    category: "document",
    meaning: "past medical information or the history section of a chart",
    ambiguous: false,
  },
  {
    id: "abbr-dx",
    shortForm: "Dx",
    expandedForm: "diagnosis",
    category: "document",
    meaning: "the identified condition or clinical impression",
    ambiguous: false,
  },
  {
    id: "abbr-tx",
    shortForm: "Tx",
    expandedForm: "treatment",
    category: "document",
    meaning: "the treatment plan or treatment itself",
    ambiguous: false,
  },
  {
    id: "abbr-fu",
    shortForm: "f/u",
    expandedForm: "follow-up",
    category: "document",
    meaning: "return visit, recheck, or next step after current care",
    ambiguous: false,
  },
  {
    id: "abbr-pcp",
    shortForm: "PCP",
    expandedForm: "primary care provider",
    category: "document",
    meaning: "the main clinician or office handling routine care",
    ambiguous: false,
  },
  {
    id: "abbr-dob",
    shortForm: "DOB",
    expandedForm: "date of birth",
    category: "document",
    meaning: "the patient's birth date",
    ambiguous: false,
  },
  {
    id: "abbr-roi",
    shortForm: "ROI",
    expandedForm: "release of information",
    category: "document",
    meaning: "permission to share records with another person or organization",
    ambiguous: false,
  },
  {
    id: "abbr-im",
    shortForm: "IM",
    expandedForm: "intramuscular",
    category: "route",
    meaning: "given into a muscle",
    ambiguous: false,
  },
  {
    id: "abbr-mg",
    shortForm: "mg",
    expandedForm: "milligram",
    category: "measurement",
    meaning: "metric unit of mass commonly used for medicine doses",
    ambiguous: false,
  }
];
