import type { Abbreviation } from "../../types/content";

export const abbreviations: Abbreviation[] = [
  {
    id: "abbr-bp",
    shortForm: "BP",
    expandedForm: "blood pressure",
    category: "clinical",
    meaning: "measurement of arterial pressure",
    ambiguous: false,
  },
  {
    id: "abbr-prn",
    shortForm: "PRN",
    expandedForm: "as needed",
    category: "document",
    meaning: "used when something should happen only when needed",
    ambiguous: false,
  },
  {
    id: "abbr-hr",
    shortForm: "HR",
    expandedForm: "heart rate",
    category: "clinical",
    meaning: "number of heartbeats per minute",
    ambiguous: false,
  },
  {
    id: "abbr-rr",
    shortForm: "RR",
    expandedForm: "respiratory rate",
    category: "clinical",
    meaning: "number of breaths per minute",
    ambiguous: false,
  },
  {
    id: "abbr-iv",
    shortForm: "IV",
    expandedForm: "intravenous",
    category: "route",
    meaning: "delivered into a vein",
    ambiguous: false,
  },
  {
    id: "abbr-po",
    shortForm: "PO",
    expandedForm: "by mouth",
    category: "route",
    meaning: "taken orally",
    ambiguous: false,
  },
  {
    id: "abbr-ml",
    shortForm: "mL",
    expandedForm: "milliliter",
    category: "measurement",
    meaning: "metric unit of liquid volume",
    ambiguous: false,
  },
  {
    id: "abbr-sob",
    shortForm: "SOB",
    expandedForm: "shortness of breath",
    category: "clinical",
    meaning: "trouble breathing or the feeling of not getting enough air",
    ambiguous: false,
  },
  {
    id: "abbr-npo",
    shortForm: "NPO",
    expandedForm: "nothing by mouth",
    category: "clinical",
    meaning: "do not eat or drink anything",
    ambiguous: false,
  },
  {
    id: "abbr-hx",
    shortForm: "Hx",
    expandedForm: "history",
    category: "document",
    meaning: "past medical information or the history section of a chart",
    ambiguous: false,
  },
  {
    id: "abbr-dx",
    shortForm: "Dx",
    expandedForm: "diagnosis",
    category: "document",
    meaning: "the identified condition or clinical impression",
    ambiguous: false,
  },
  {
    id: "abbr-tx",
    shortForm: "Tx",
    expandedForm: "treatment",
    category: "document",
    meaning: "the treatment plan or treatment itself",
    ambiguous: false,
  },
  {
    id: "abbr-fu",
    shortForm: "f/u",
    expandedForm: "follow-up",
    category: "document",
    meaning: "return visit, recheck, or next step after current care",
    ambiguous: false,
  },
  {
    id: "abbr-pcp",
    shortForm: "PCP",
    expandedForm: "primary care provider",
    category: "document",
    meaning: "the main clinician or office handling routine care",
    ambiguous: false,
  },
  {
    id: "abbr-dob",
    shortForm: "DOB",
    expandedForm: "date of birth",
    category: "document",
    meaning: "the patient's birth date",
    ambiguous: false,
  },
  {
    id: "abbr-roi",
    shortForm: "ROI",
    expandedForm: "release of information",
    category: "document",
    meaning: "permission to share records with another person or organization",
    ambiguous: false,
  },
  {
    id: "abbr-im",
    shortForm: "IM",
    expandedForm: "intramuscular",
    category: "route",
    meaning: "given into a muscle",
    ambiguous: false,
  },
  {
    id: "abbr-mg",
    shortForm: "mg",
    expandedForm: "milligram",
    category: "measurement",
    meaning: "metric unit of mass commonly used for medicine doses",
    ambiguous: false,
  },
  {
    id: "abbr-wnl",
    shortForm: "WNL",
    expandedForm: "within normal limits",
    category: "clinical",
    meaning: "findings are in the expected or normal range",
    ambiguous: false,
  },
  {
    id: "abbr-sq",
    shortForm: "SQ",
    expandedForm: "subcutaneous",
    category: "route",
    meaning: "given under the skin",
    ambiguous: false,
  },
  {
    id: "abbr-w-with",
    shortForm: "w/",
    expandedForm: "with",
    category: "document",
    meaning: "used in charting or instructions to mean with",
    ambiguous: false,
  },
  {
    id: "abbr-wo",
    shortForm: "w/o",
    expandedForm: "without",
    category: "document",
    meaning: "used in charting or instructions to mean without",
    ambiguous: false,
  },
  {
    id: "abbr-co",
    shortForm: "c/o",
    expandedForm: "complains of",
    category: "clinical",
    meaning: "used in notes to introduce the symptom or problem the patient reports",
    ambiguous: false,
  },
  {
    id: "abbr-sp",
    shortForm: "s/p",
    expandedForm: "status post",
    category: "document",
    meaning: "used to describe a state after a procedure or event",
    ambiguous: false,
  },
  {
    id: "abbr-nkda",
    shortForm: "NKDA",
    expandedForm: "no known drug allergies",
    category: "clinical",
    meaning: "chart shorthand indicating no known medication allergies",
    ambiguous: false,
  },
  {
    id: "abbr-bid",
    shortForm: "BID",
    expandedForm: "twice daily",
    category: "document",
    meaning: "used in medication instructions to mean two times each day",
    ambiguous: false,
  },
  {
    id: "abbr-tid",
    shortForm: "TID",
    expandedForm: "three times daily",
    category: "document",
    meaning: "used in medication instructions to mean three times each day",
    ambiguous: false,
  },
  {
    id: "abbr-cbc",
    shortForm: "CBC",
    expandedForm: "complete blood count",
    category: "clinical",
    meaning: "a common lab test that measures blood cell counts",
    ambiguous: false,
  },
  {
    id: "abbr-stat",
    shortForm: "STAT",
    expandedForm: "immediately",
    category: "clinical",
    meaning: "used when an order or action should happen without delay",
    ambiguous: false,
  },
  {
    id: "abbr-ct",
    shortForm: "CT",
    expandedForm: "computed tomography",
    category: "clinical",
    meaning: "an imaging scan that uses X-rays to create cross-sectional pictures",
    ambiguous: false,
  },
  {
    id: "abbr-mri",
    shortForm: "MRI",
    expandedForm: "magnetic resonance imaging",
    category: "clinical",
    meaning: "an imaging scan that uses magnetic fields and radio waves",
    ambiguous: false,
  },
  {
    id: "abbr-ua",
    shortForm: "UA",
    expandedForm: "urinalysis",
    category: "clinical",
    meaning: "a test of the urine used to check for several common findings",
    ambiguous: false,
  },
  {
    id: "abbr-qam",
    shortForm: "qAM",
    expandedForm: "every morning",
    category: "document",
    meaning: "used in medication instructions to mean each morning",
    ambiguous: false,
  },
  {
    id: "abbr-qhs",
    shortForm: "qHS",
    expandedForm: "every night at bedtime",
    category: "document",
    meaning: "used in medication instructions to mean nightly at bedtime",
    ambiguous: false,
  },
  {
    id: "abbr-qid",
    shortForm: "QID",
    expandedForm: "four times daily",
    category: "document",
    meaning: "used in medication instructions to mean four times each day",
    ambiguous: false,
  },
  {
    id: "abbr-tab",
    shortForm: "tab",
    expandedForm: "tablet",
    category: "document",
    meaning: "a solid medication dose form shaped as a tablet",
    ambiguous: false,
  },
  {
    id: "abbr-cap",
    shortForm: "cap",
    expandedForm: "capsule",
    category: "document",
    meaning: "a medication dose form enclosed in a capsule shell",
    ambiguous: false,
  },
  {
    id: "abbr-avs",
    shortForm: "AVS",
    expandedForm: "after-visit summary",
    category: "document",
    meaning: "the summary given after a visit with instructions, diagnoses, and next steps",
    ambiguous: false,
  },
  {
    id: "abbr-appt",
    shortForm: "appt",
    expandedForm: "appointment",
    category: "document",
    meaning: "a scheduled visit time or booking",
    ambiguous: false,
  },
  {
    id: "abbr-pa",
    shortForm: "PA",
    expandedForm: "context dependent: prior authorization or physician assistant",
    category: "document",
    meaning: "the surrounding sentence matters; in office workflow it often means prior authorization, but it can also mean physician assistant",
    ambiguous: true,
  },
  {
    id: "abbr-pt",
    shortForm: "PT",
    expandedForm: "context dependent: physical therapy or patient",
    category: "document",
    meaning: "the surrounding sentence matters; it may refer to physical therapy or to the patient",
    ambiguous: true,
  },
  {
    id: "abbr-ms",
    shortForm: "MS",
    expandedForm: "context dependent: multiple sclerosis or morphine sulfate",
    category: "clinical",
    meaning: "the surrounding sentence matters; it may refer to a diagnosis or to a medication",
    ambiguous: true,
  },
  {
    id: "abbr-bs",
    shortForm: "BS",
    expandedForm: "context dependent: bowel sounds or blood sugar",
    category: "clinical",
    meaning: "the surrounding sentence matters; exam context and lab context point to different meanings",
    ambiguous: true,
  },
  {
    id: "abbr-cp",
    shortForm: "CP",
    expandedForm: "context dependent: chest pain or cerebral palsy",
    category: "clinical",
    meaning: "the surrounding sentence matters; symptom context and diagnosis-history context point to different meanings",
    ambiguous: true,
  }
];
