import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-batch-inflammatory-conjunctiv-combining",
    text: "conjunctiv/o",
    type: "combining_form",
    plainMeaning: "conjunctiva; eye lining",
    altMeanings: [],
    pronunciationText: "kon-junk-TIH-voh",
    examples: ["conjunctivitis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 1,
  },
  {
    id: "part-batch-inflammatory-periton-combining",
    text: "periton/o",
    type: "combining_form",
    plainMeaning: "peritoneum; abdominal lining",
    altMeanings: [],
    pronunciationText: "pair-ih-TOH-noh",
    examples: ["peritonitis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 2,
  },
  {
    id: "part-batch-inflammatory-tonsill-combining",
    text: "tonsill/o",
    type: "combining_form",
    plainMeaning: "tonsil",
    altMeanings: [],
    pronunciationText: "TAHN-sil-oh",
    examples: ["tonsillitis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 3,
  },
  {
    id: "part-batch-inflammatory-phleb-combining",
    text: "phleb/o",
    type: "combining_form",
    plainMeaning: "vein",
    altMeanings: [],
    pronunciationText: "FLEB-oh",
    examples: ["phlebitis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 4,
  },
  {
    id: "part-batch-inflammatory-vagin-combining",
    text: "vagin/o",
    type: "combining_form",
    plainMeaning: "vagina",
    altMeanings: [],
    pronunciationText: "vaj-ih-NOH",
    examples: ["vaginitis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-batch-inflammatory-vulv-combining",
    text: "vulv/o",
    type: "combining_form",
    plainMeaning: "vulva",
    altMeanings: [],
    pronunciationText: "VUL-voh",
    examples: ["vulvitis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-batch-inflammatory-cervic-combining",
    text: "cervic/o",
    type: "combining_form",
    plainMeaning: "cervix",
    altMeanings: [],
    pronunciationText: "SER-vih-koh",
    examples: ["cervicitis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-batch-inflammatory-mening-combining",
    text: "mening/o",
    type: "combining_form",
    plainMeaning: "meninges",
    altMeanings: [],
    pronunciationText: "meh-NIN-joh",
    examples: ["meningitis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  },
  {
    id: "part-batch-inflammatory-edem-combining",
    text: "edem/o",
    type: "combining_form",
    plainMeaning: "swelling",
    altMeanings: [],
    pronunciationText: "eh-DEM-oh",
    examples: ["lymphedema"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 9,
  },
  {
    id: "part-batch-inflammatory-trophy-suffix",
    text: "-trophy",
    type: "suffix",
    plainMeaning: "nourishment; growth",
    altMeanings: [],
    pronunciationText: "TROH-fee",
    examples: ["hypertrophy", "atrophy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 10,
  },
  {
    id: "part-batch-inflammatory-a-prefix",
    text: "a-",
    type: "prefix",
    plainMeaning: "without; not",
    altMeanings: [],
    pronunciationText: "ay",
    examples: ["atrophy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 11,
  },
  {
    id: "part-batch-inflammatory-meta-prefix",
    text: "meta-",
    type: "prefix",
    plainMeaning: "change; after",
    altMeanings: [],
    pronunciationText: "MET-uh",
    examples: ["metaplasia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 12,
  },
  {
    id: "part-batch-inflammatory-neo-prefix",
    text: "neo-",
    type: "prefix",
    plainMeaning: "new",
    altMeanings: [],
    pronunciationText: "nee-oh",
    examples: ["neoplasia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 13,
  },
  {
    id: "part-batch-inflammatory-chondr-combining",
    text: "chondr/o",
    type: "combining_form",
    plainMeaning: "cartilage",
    altMeanings: [],
    pronunciationText: "KON-droh",
    examples: ["chondromalacia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 14,
  },
  {
    id: "part-batch-inflammatory-sten-combining",
    text: "sten/o",
    type: "combining_form",
    plainMeaning: "narrow; tight",
    altMeanings: [],
    pronunciationText: "STEN-oh",
    examples: ["stenosis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 15,
  },
  {
    id: "part-batch-inflammatory-stenosis-suffix",
    text: "-stenosis",
    type: "suffix",
    plainMeaning: "narrowing; constriction",
    altMeanings: [],
    pronunciationText: "sten-OH-sis",
    examples: ["bronchostenosis", "tracheostenosis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 16,
  },
  {
    id: "part-batch-inflammatory-dilat-combining",
    text: "dilat/o",
    type: "combining_form",
    plainMeaning: "widen; open",
    altMeanings: [],
    pronunciationText: "dih-LAT-oh",
    examples: ["vasodilation"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 17,
  },
  {
    id: "part-batch-inflammatory-ectasis-suffix",
    text: "-ectasis",
    type: "suffix",
    plainMeaning: "dilation; widening",
    altMeanings: [],
    pronunciationText: "EK-tuh-sis",
    examples: ["bronchiectasis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 18,
  },
  {
    id: "part-batch-inflammatory-rrhage-suffix",
    text: "-rrhage",
    type: "suffix",
    plainMeaning: "bursting forth; bleeding",
    altMeanings: [],
    pronunciationText: "RAYJ",
    examples: ["hemorrhage"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 19,
  },
  {
    id: "part-batch-inflammatory-rrhagia-suffix",
    text: "-rrhagia",
    type: "suffix",
    plainMeaning: "excessive bleeding",
    altMeanings: [],
    pronunciationText: "rra-JEE-uh",
    examples: ["menorrhagia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 20,
  },
  {
    id: "part-batch-inflammatory-cele-suffix",
    text: "-cele",
    type: "suffix",
    plainMeaning: "hernia; protrusion; swelling",
    altMeanings: [],
    pronunciationText: "SEE-lee",
    examples: ["cystocele", "meningocele"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 21,
  },
  {
    id: "part-batch-inflammatory-rect-combining",
    text: "rect/o",
    type: "combining_form",
    plainMeaning: "rectum",
    altMeanings: [],
    pronunciationText: "REK-toh",
    examples: ["rectocele"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 22,
  },
  {
    id: "part-batch-inflammatory-hydr-combining",
    text: "hydr/o",
    type: "combining_form",
    plainMeaning: "water; fluid",
    altMeanings: [],
    pronunciationText: "HY-droh",
    examples: ["hydrocele"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 23,
  },
];
