import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-cyte-suffix",
    text: "-cyte",
    type: "suffix",
    plainMeaning: "cell",
    altMeanings: [],
    pronunciationText: "SITE",
    examples: ["thrombocyte", "leukocyte"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 1,
  },
  {
    id: "part-penia-suffix",
    text: "-penia",
    type: "suffix",
    plainMeaning: "deficiency; low count",
    altMeanings: [],
    pronunciationText: "PEE-nee-uh",
    examples: ["leukopenia", "thrombocytopenia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 2,
  },
  {
    id: "part-panc-prefix",
    text: "panc-",
    type: "prefix",
    plainMeaning: "all; entire",
    altMeanings: [],
    pronunciationText: "pank",
    examples: ["pancytopenia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 3,
  },
  {
    id: "part-hem-combining",
    text: "hem/o",
    type: "combining_form",
    plainMeaning: "blood",
    altMeanings: [],
    pronunciationText: "HEM-oh",
    examples: ["hemogram", "hemolysis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 4,
  },
  {
    id: "part-lysis-suffix",
    text: "-lysis",
    type: "suffix",
    plainMeaning: "breakdown; destruction",
    altMeanings: [],
    pronunciationText: "LYE-sis",
    examples: ["hemolysis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
];
