import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-batch-measure-metr-combining",
    text: "metr/o",
    type: "combining_form",
    plainMeaning: "measure",
    altMeanings: [],
    pronunciationText: "MEE-troh",
    examples: ["thermometry", "spirometry"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 1,
  },
  {
    id: "part-batch-measure-meter-suffix",
    text: "-meter",
    type: "suffix",
    plainMeaning: "instrument for measuring",
    altMeanings: [],
    pronunciationText: "MEE-ter",
    examples: ["spirometer", "oximeter"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 2,
  },
  {
    id: "part-batch-measure-metry-suffix",
    text: "-metry",
    type: "suffix",
    plainMeaning: "process of measuring",
    altMeanings: [],
    pronunciationText: "MEH-tree",
    examples: ["spirometry", "oximetry"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 3,
  },
  {
    id: "part-batch-measure-spir-combining",
    text: "spir/o",
    type: "combining_form",
    plainMeaning: "breath; breathing",
    altMeanings: [],
    pronunciationText: "SPY-roh",
    examples: ["spirometer", "spirometry"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 4,
  },
  {
    id: "part-batch-measure-ox-combining",
    text: "ox/o",
    type: "combining_form",
    plainMeaning: "oxygen",
    altMeanings: [],
    pronunciationText: "OX-oh",
    examples: ["oximeter", "oximetry"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-batch-measure-therm-combining",
    text: "therm/o",
    type: "combining_form",
    plainMeaning: "heat; temperature",
    altMeanings: [],
    pronunciationText: "THERM-oh",
    examples: ["thermometer", "thermometry"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-batch-measure-tom-combining",
    text: "tom/o",
    type: "combining_form",
    plainMeaning: "cut; section",
    altMeanings: [],
    pronunciationText: "TOM-oh",
    examples: ["tomogram", "tomography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-batch-measure-echo-prefix",
    text: "echo-",
    type: "prefix",
    plainMeaning: "reflected sound",
    altMeanings: [],
    pronunciationText: "ECK-oh",
    examples: ["echocardiogram", "echocardiography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  },
];
