import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-batch-fluid-noct-combining",
    text: "noct/o",
    type: "combining_form",
    plainMeaning: "night",
    altMeanings: [],
    pronunciationText: "NOK-toh",
    examples: ["nocturia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 1,
  },
  {
    id: "part-batch-fluid-py-combining",
    text: "py/o",
    type: "combining_form",
    plainMeaning: "pus",
    altMeanings: [],
    pronunciationText: "PYE-oh",
    examples: ["pyuria"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 2,
  },
  {
    id: "part-batch-fluid-bacteri-combining",
    text: "bacteri/o",
    type: "combining_form",
    plainMeaning: "bacteria",
    altMeanings: [],
    pronunciationText: "bak-TEER-ee-oh",
    examples: ["bacteriuria"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 3,
  },
  {
    id: "part-batch-fluid-keton-combining",
    text: "keton/o",
    type: "combining_form",
    plainMeaning: "ketones",
    altMeanings: [],
    pronunciationText: "KEE-tone-oh",
    examples: ["ketonuria"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 4,
  },
  {
    id: "part-batch-fluid-emesis-suffix",
    text: "-emesis",
    type: "suffix",
    plainMeaning: "vomiting",
    altMeanings: [],
    pronunciationText: "EM-eh-sis",
    examples: ["hematemesis", "hyperemesis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-batch-fluid-ptysis-suffix",
    text: "-ptysis",
    type: "suffix",
    plainMeaning: "spitting; coughing up",
    altMeanings: [],
    pronunciationText: "TIH-sis",
    examples: ["hemoptysis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-batch-fluid-galact-combining",
    text: "galact/o",
    type: "combining_form",
    plainMeaning: "milk",
    altMeanings: [],
    pronunciationText: "gah-LAK-toh",
    examples: ["galactorrhea"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-batch-fluid-steat-combining",
    text: "steat/o",
    type: "combining_form",
    plainMeaning: "fat",
    altMeanings: [],
    pronunciationText: "STEE-at-oh",
    examples: ["steatorrhea"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  },
  {
    id: "part-batch-fluid-dia-prefix",
    text: "dia-",
    type: "prefix",
    plainMeaning: "through; across",
    altMeanings: [],
    pronunciationText: "DYE-ah",
    examples: ["diarrhea"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 9,
  },
  {
    id: "part-batch-fluid-chezia-suffix",
    text: "-chezia",
    type: "suffix",
    plainMeaning: "passage of stool",
    altMeanings: [],
    pronunciationText: "KEE-zee-uh",
    examples: ["hematochezia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 10,
  },
];
