import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-batch-imaging-radi-combining",
    text: "radi/o",
    type: "combining_form",
    plainMeaning: "radiation; X-ray",
    altMeanings: [],
    pronunciationText: "RAY-dee-oh",
    examples: ["radiography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 1,
  },
  {
    id: "part-batch-imaging-son-combining",
    text: "son/o",
    type: "combining_form",
    plainMeaning: "sound",
    altMeanings: [],
    pronunciationText: "SOH-noh",
    examples: ["sonogram", "sonography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 2,
  },
  {
    id: "part-batch-imaging-mamm-combining",
    text: "mamm/o",
    type: "combining_form",
    plainMeaning: "breast",
    altMeanings: [],
    pronunciationText: "MAM-oh",
    examples: ["mammogram", "mammography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 3,
  },
  {
    id: "part-batch-imaging-electr-combining",
    text: "electr/o",
    type: "combining_form",
    plainMeaning: "electricity",
    altMeanings: [],
    pronunciationText: "ee-LEK-troh",
    examples: ["electrocardiogram", "electrocardiography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 4,
  },
  {
    id: "part-batch-imaging-cardi-combining",
    text: "cardi/o",
    type: "combining_form",
    plainMeaning: "heart",
    altMeanings: [],
    pronunciationText: "KAR-dee-oh",
    examples: ["cardiograph", "electrocardiogram"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-batch-imaging-fluor-combining",
    text: "fluor/o",
    type: "combining_form",
    plainMeaning: "fluorescence; fluoroscopy",
    altMeanings: [],
    pronunciationText: "floor-OH",
    examples: ["fluoroscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-batch-imaging-lapar-combining",
    text: "lapar/o",
    type: "combining_form",
    plainMeaning: "abdomen; abdominal wall",
    altMeanings: [],
    pronunciationText: "LAP-ah-roh",
    examples: ["laparoscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-batch-imaging-graph-suffix",
    text: "-graph",
    type: "suffix",
    plainMeaning: "instrument that records",
    altMeanings: [],
    pronunciationText: "graf",
    examples: ["cardiograph", "electrocardiograph"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  },
];
