import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-batch-imaging-radi-combining",
    text: "radi/o",
    type: "combining_form",
    plainMeaning: "radiation; X-ray",
    altMeanings: [],
    pronunciationText: "RAY-dee-oh",
    examples: ["radiograph", "radiography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 1,
  },
  {
    id: "part-batch-imaging-son-combining",
    text: "son/o",
    type: "combining_form",
    plainMeaning: "sound",
    altMeanings: [],
    pronunciationText: "SOH-noh",
    examples: ["sonogram", "sonography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 2,
  },
  {
    id: "part-batch-imaging-mamm-combining",
    text: "mamm/o",
    type: "combining_form",
    plainMeaning: "breast",
    altMeanings: [],
    pronunciationText: "MAM-oh",
    examples: ["mammogram", "mammography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 3,
  },
  {
    id: "part-batch-imaging-angi-combining",
    text: "angi/o",
    type: "combining_form",
    plainMeaning: "vessel",
    altMeanings: ["blood vessel"],
    pronunciationText: "AN-jee-oh",
    examples: ["angiogram", "angiography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 4,
  },
  {
    id: "part-batch-imaging-electr-combining",
    text: "electr/o",
    type: "combining_form",
    plainMeaning: "electricity",
    altMeanings: [],
    pronunciationText: "ee-LEK-troh",
    examples: ["electrocardiogram", "electrocardiography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-batch-imaging-cardi-combining",
    text: "cardi/o",
    type: "combining_form",
    plainMeaning: "heart",
    altMeanings: [],
    pronunciationText: "KAR-dee-oh",
    examples: ["cardiogram", "cardiography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-batch-imaging-bronch-combining",
    text: "bronch/o",
    type: "combining_form",
    plainMeaning: "bronchial tube; airway branch",
    altMeanings: ["bronchus"],
    pronunciationText: "BRONG-koh",
    examples: ["bronchoscopy", "bronchitis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-batch-imaging-col-combining",
    text: "col/o",
    type: "combining_form",
    plainMeaning: "colon",
    altMeanings: [],
    pronunciationText: "KOH-loh",
    examples: ["colonoscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  },
  {
    id: "part-batch-imaging-endo-prefix",
    text: "endo-",
    type: "prefix",
    plainMeaning: "within; inside",
    altMeanings: [],
    pronunciationText: "EN-doh",
    examples: ["endoscopy", "endovascular"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 9,
  },
  {
    id: "part-batch-imaging-gram-suffix",
    text: "-gram",
    type: "suffix",
    plainMeaning: "record or image",
    altMeanings: [],
    pronunciationText: "gram",
    examples: ["radiogram", "angiogram"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 10,
  },
  {
    id: "part-batch-imaging-graph-suffix",
    text: "-graph",
    type: "suffix",
    plainMeaning: "instrument that records",
    altMeanings: [],
    pronunciationText: "graf",
    examples: ["cardiograph", "electrocardiograph"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 11,
  },
  {
    id: "part-batch-imaging-graphy-suffix",
    text: "-graphy",
    type: "suffix",
    plainMeaning: "process of recording",
    altMeanings: [],
    pronunciationText: "graf-ee",
    examples: ["radiography", "angiography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 12,
  },
  {
    id: "part-batch-imaging-scopy-suffix",
    text: "-scopy",
    type: "suffix",
    plainMeaning: "viewing with a scope",
    altMeanings: [],
    pronunciationText: "SKOH-pee",
    examples: ["bronchoscopy", "colonoscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 13,
  },
];
