import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-batch-definflam-anti-prefix",
    text: "anti-",
    type: "prefix",
    plainMeaning: "against; opposed to",
    altMeanings: [],
    pronunciationText: "AN-ty",
    examples: ["antibiotic", "antiseptic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 1,
  },
  {
    id: "part-batch-definflam-eu-prefix",
    text: "eu-",
    type: "prefix",
    plainMeaning: "good; normal",
    altMeanings: [],
    pronunciationText: "yoo",
    examples: ["eupnea"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 2,
  },
  {
    id: "part-batch-definflam-mal-prefix",
    text: "mal-",
    type: "prefix",
    plainMeaning: "bad; poor; faulty",
    altMeanings: [],
    pronunciationText: "mal",
    examples: ["malnutrition", "malabsorption"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 3,
  },
  {
    id: "part-batch-definflam-bi-combining",
    text: "bi/o",
    type: "combining_form",
    plainMeaning: "life",
    altMeanings: [],
    pronunciationText: "BY-oh",
    examples: ["antibiotic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 4,
  },
  {
    id: "part-batch-definflam-pyret-combining",
    text: "pyret/o",
    type: "combining_form",
    plainMeaning: "fever",
    altMeanings: [],
    pronunciationText: "py-RET-oh",
    examples: ["antipyretic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-batch-definflam-emet-combining",
    text: "emet/o",
    type: "combining_form",
    plainMeaning: "vomit",
    altMeanings: [],
    pronunciationText: "eh-MET-oh",
    examples: ["antiemetic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-batch-definflam-septic-combining",
    text: "septic/o",
    type: "combining_form",
    plainMeaning: "infection; putrefaction",
    altMeanings: [],
    pronunciationText: "SEP-tik-oh",
    examples: ["antiseptic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-batch-definflam-nutr-combining",
    text: "nutr/o",
    type: "combining_form",
    plainMeaning: "nutrition; nourishment",
    altMeanings: [],
    pronunciationText: "NYOO-troh",
    examples: ["malnutrition"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  },
  {
    id: "part-batch-definflam-absorpt-combining",
    text: "absorpt/o",
    type: "combining_form",
    plainMeaning: "absorption",
    altMeanings: [],
    pronunciationText: "ab-SORP-toh",
    examples: ["malabsorption"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 9,
  },
  {
    id: "part-batch-definflam-ic-suffix",
    text: "-ic",
    type: "suffix",
    plainMeaning: "pertaining to",
    altMeanings: [],
    pronunciationText: "ik",
    examples: ["antiseptic", "antipyretic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 10,
  },
  {
    id: "part-batch-definflam-otic-suffix",
    text: "-otic",
    type: "suffix",
    plainMeaning: "pertaining to",
    altMeanings: [],
    pronunciationText: "OT-ik",
    examples: ["antibiotic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 11,
  },
  {
    id: "part-batch-definflam-tion-suffix",
    text: "-tion",
    type: "suffix",
    plainMeaning: "act; process; result",
    altMeanings: [],
    pronunciationText: "shun",
    examples: ["nutrition", "absorption"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 12,
  },
  {
    id: "part-batch-definflam-phag-combining",
    text: "phag/o",
    type: "combining_form",
    plainMeaning: "eat; swallow",
    altMeanings: [],
    pronunciationText: "FAG-oh",
    examples: ["dysphagia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 13,
  },
  {
    id: "part-batch-definflam-phon-combining",
    text: "phon/o",
    type: "combining_form",
    plainMeaning: "voice; sound",
    altMeanings: [],
    pronunciationText: "FOH-noh",
    examples: ["dysphonia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 14,
  },
  {
    id: "part-batch-definflam-phas-combining",
    text: "phas/o",
    type: "combining_form",
    plainMeaning: "speech",
    altMeanings: [],
    pronunciationText: "FAZ-oh",
    examples: ["dysphasia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 15,
  },
  {
    id: "part-batch-definflam-ton-combining",
    text: "ton/o",
    type: "combining_form",
    plainMeaning: "tone; tension",
    altMeanings: [],
    pronunciationText: "TOH-noh",
    examples: ["dystonia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 16,
  },
  {
    id: "part-batch-definflam-ia-suffix",
    text: "-ia",
    type: "suffix",
    plainMeaning: "condition; state",
    altMeanings: [],
    pronunciationText: "ee-uh",
    examples: ["dysphagia", "dystonia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 17,
  },
  {
    id: "part-batch-definflam-path-combining",
    text: "path/o",
    type: "combining_form",
    plainMeaning: "disease; suffering",
    altMeanings: [],
    pronunciationText: "PATH-oh",
    examples: ["pathology", "pathogenic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 18,
  },
  {
    id: "part-batch-definflam-genic-suffix",
    text: "-genic",
    type: "suffix",
    plainMeaning: "producing; causing",
    altMeanings: [],
    pronunciationText: "JEN-ik",
    examples: ["pathogenic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 19,
  },
  {
    id: "part-batch-definflam-genesis-suffix",
    text: "-genesis",
    type: "suffix",
    plainMeaning: "formation; origin",
    altMeanings: [],
    pronunciationText: "JEN-eh-sis",
    examples: ["pathogenesis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 20,
  },
  {
    id: "part-batch-definflam-stasis-suffix",
    text: "-stasis",
    type: "suffix",
    plainMeaning: "standing still; stopping",
    altMeanings: [],
    pronunciationText: "STAY-sis",
    examples: ["hemostasis", "homeostasis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 21,
  },
  {
    id: "part-batch-definflam-homeo-prefix",
    text: "homeo-",
    type: "prefix",
    plainMeaning: "same; constant",
    altMeanings: [],
    pronunciationText: "HOH-mee-oh",
    examples: ["homeostasis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 22,
  },
];
