import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-batch-growthmass-plasm-combining",
    text: "plasm/o",
    type: "combining_form",
    plainMeaning: "formation; growth",
    altMeanings: ["something formed"],
    pronunciationText: "PLAZ-moh",
    examples: ["neoplasm", "neoplastic"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 1,
  },
  {
    id: "part-batch-growthmass-melan-combining",
    text: "melan/o",
    type: "combining_form",
    plainMeaning: "black; dark pigment",
    altMeanings: [],
    pronunciationText: "mel-an-OH",
    examples: ["melanoma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 2,
  },
  {
    id: "part-batch-growthmass-lip-combining",
    text: "lip/o",
    type: "combining_form",
    plainMeaning: "fat",
    altMeanings: [],
    pronunciationText: "LIP-oh",
    examples: ["lipoma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 3,
  },
  {
    id: "part-batch-growthmass-myel-combining",
    text: "myel/o",
    type: "combining_form",
    plainMeaning: "marrow; spinal cord",
    altMeanings: [],
    pronunciationText: "MYE-eh-loh",
    examples: ["myeloma", "myelography"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 4,
  },
  {
    id: "part-batch-growthmass-granul-combining",
    text: "granul/o",
    type: "combining_form",
    plainMeaning: "granule; small grain-like lump",
    altMeanings: [],
    pronunciationText: "GRAN-yoo-loh",
    examples: ["granuloma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-batch-growthmass-fibr-combining",
    text: "fibr/o",
    type: "combining_form",
    plainMeaning: "fiber; fibrous tissue",
    altMeanings: [],
    pronunciationText: "FYE-broh",
    examples: ["fibroma", "fibroadenoma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-batch-growthmass-gli-combining",
    text: "gli/o",
    type: "combining_form",
    plainMeaning: "glial tissue; glue-like support tissue",
    altMeanings: [],
    pronunciationText: "GLEE-oh",
    examples: ["glioma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-batch-growthmass-papill-combining",
    text: "papill/o",
    type: "combining_form",
    plainMeaning: "nipple-like projection; papilla",
    altMeanings: [],
    pronunciationText: "pap-ih-LOH",
    examples: ["papilloma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  },
  {
    id: "part-batch-growthmass-sarc-combining",
    text: "sarc/o",
    type: "combining_form",
    plainMeaning: "flesh; connective tissue",
    altMeanings: [],
    pronunciationText: "SAR-koh",
    examples: ["sarcoma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 9,
  },
];
