import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-cardi-root",
    text: "cardi",
    type: "root",
    plainMeaning: "heart",
    altMeanings: [],
    pronunciationText: "KAR-dee",
    examples: ["cardiac", "cardiology"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 1,
  },
  {
    id: "part-gastr-root",
    text: "gastr",
    type: "root",
    plainMeaning: "stomach",
    altMeanings: [],
    pronunciationText: "GAS-tr",
    examples: ["gastric", "gastrology"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 2,
  },
  {
    id: "part-neur-root",
    text: "neur",
    type: "root",
    plainMeaning: "nerve",
    altMeanings: [],
    pronunciationText: "nyoor",
    examples: ["neural", "neurology"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 3,
  },
  {
    id: "part-osteo-combining",
    text: "oste/o",
    type: "combining_form",
    plainMeaning: "bone",
    altMeanings: [],
    pronunciationText: "OS-tee-oh",
    examples: ["osteology", "osteotomy"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 4,
  },
  {
    id: "part-itis-suffix",
    text: "-itis",
    type: "suffix",
    plainMeaning: "inflammation",
    altMeanings: [],
    pronunciationText: "EYE-tis",
    examples: ["arthritis", "gastritis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-ology-suffix",
    text: "-logy",
    type: "suffix",
    plainMeaning: "study of",
    altMeanings: [],
    pronunciationText: "ol-uh-jee",
    examples: ["cardiology", "neurology"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-hyper-prefix",
    text: "hyper-",
    type: "prefix",
    plainMeaning: "too much; above normal",
    altMeanings: [],
    pronunciationText: "HY-per",
    examples: ["hypertension"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-hypo-prefix",
    text: "hypo-",
    type: "prefix",
    plainMeaning: "too little; below normal",
    altMeanings: [],
    pronunciationText: "HY-poh",
    examples: ["hypotension"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  },
  {
    id: "part-arthr-combining",
    text: "arthr/o",
    type: "combining_form",
    plainMeaning: "joint",
    altMeanings: [],
    pronunciationText: "AR-throh",
    examples: ["arthritis", "arthroscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 9,
  },
  {
    id: "part-hemat-combining",
    text: "hemat/o",
    type: "combining_form",
    plainMeaning: "blood",
    altMeanings: [],
    pronunciationText: "hee-MAT-oh",
    examples: ["hematology", "hematoma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 10,
  },
  {
    id: "part-derm-combining",
    text: "derm/o",
    type: "combining_form",
    plainMeaning: "skin",
    altMeanings: [],
    pronunciationText: "DERM-oh",
    examples: ["dermatitis", "dermatology"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 11,
  },
  {
    id: "part-hepat-combining",
    text: "hepat/o",
    type: "combining_form",
    plainMeaning: "liver",
    altMeanings: [],
    pronunciationText: "heh-PAT-oh",
    examples: ["hepatitis", "hepatology"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 12,
  },
  {
    id: "part-nephr-combining",
    text: "nephr/o",
    type: "combining_form",
    plainMeaning: "kidney",
    altMeanings: [],
    pronunciationText: "NEF-roh",
    examples: ["nephrology", "nephritis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 13,
  },
  {
    id: "part-algia-suffix",
    text: "-algia",
    type: "suffix",
    plainMeaning: "pain",
    altMeanings: [],
    pronunciationText: "AL-jee-uh",
    examples: ["neuralgia", "myalgia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 14,
  },
  {
    id: "part-appendic-combining",
    text: "appendic/o",
    type: "combining_form",
    plainMeaning: "appendix",
    altMeanings: [],
    pronunciationText: "ah-PEN-dih-koh",
    examples: ["appendectomy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 15,
  },
  {
    id: "part-col-combining",
    text: "col/o",
    type: "combining_form",
    plainMeaning: "colon",
    altMeanings: [],
    pronunciationText: "KOH-loh",
    examples: ["colonoscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 16,
  },
  {
    id: "part-ectomy-suffix",
    text: "-ectomy",
    type: "suffix",
    plainMeaning: "surgical removal",
    altMeanings: [],
    pronunciationText: "EK-toh-mee",
    examples: ["appendectomy", "tonsillectomy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 17,
  },
  {
    id: "part-otomy-suffix",
    text: "-otomy",
    type: "suffix",
    plainMeaning: "incision into",
    altMeanings: [],
    pronunciationText: "OT-oh-mee",
    examples: ["gastrotomy", "tracheotomy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 18,
  },
  {
    id: "part-scopy-suffix",
    text: "-scopy",
    type: "suffix",
    plainMeaning: "viewing with a scope",
    altMeanings: [],
    pronunciationText: "SKOH-pee",
    examples: ["colonoscopy", "endoscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 19,
  },
  {
    id: "part-gram-suffix",
    text: "-gram",
    type: "suffix",
    plainMeaning: "record or image",
    altMeanings: [],
    pronunciationText: "gram",
    examples: ["cardiogram", "angiogram"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 20,
  },
  {
    id: "part-tachy-prefix",
    text: "tachy-",
    type: "prefix",
    plainMeaning: "fast",
    altMeanings: [],
    pronunciationText: "TAK-ee",
    examples: ["tachycardia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 21,
  },
  {
    id: "part-brady-prefix",
    text: "brady-",
    type: "prefix",
    plainMeaning: "slow",
    altMeanings: [],
    pronunciationText: "BRAY-dee",
    examples: ["bradycardia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 22,
  },
  {
    id: "part-angi-combining",
    text: "angi/o",
    type: "combining_form",
    plainMeaning: "vessel",
    altMeanings: [],
    pronunciationText: "AN-jee-oh",
    examples: ["angiogram", "angiology"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 23,
  },
  {
    id: "part-arteri-combining",
    text: "arteri/o",
    type: "combining_form",
    plainMeaning: "artery",
    altMeanings: [],
    pronunciationText: "ar-TEER-ee-oh",
    examples: ["arteritis", "arteriology"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 24,
  },
  {
    id: "part-ven-combining",
    text: "ven/o",
    type: "combining_form",
    plainMeaning: "vein",
    altMeanings: [],
    pronunciationText: "VEE-noh",
    examples: ["venogram", "venous"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 25,
  },
  {
    id: "part-bronch-combining",
    text: "bronch/o",
    type: "combining_form",
    plainMeaning: "bronchial tube; airway branch",
    altMeanings: [],
    pronunciationText: "BRONG-koh",
    examples: ["bronchitis", "bronchoscopy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 26,
  },
  {
    id: "part-trache-combining",
    text: "trache/o",
    type: "combining_form",
    plainMeaning: "trachea; windpipe",
    altMeanings: [],
    pronunciationText: "TRAY-kee-oh",
    examples: ["tracheotomy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 27,
  },
  {
    id: "part-pneum-combining",
    text: "pneum/o",
    type: "combining_form",
    plainMeaning: "lung; air",
    altMeanings: [],
    pronunciationText: "new-MOH",
    examples: ["pneumonia", "pneumothorax"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 28,
  },
  {
    id: "part-pulmon-combining",
    text: "pulmon/o",
    type: "combining_form",
    plainMeaning: "lung",
    altMeanings: [],
    pronunciationText: "PUL-moh-noh",
    examples: ["pulmonary"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 29,
  },
  {
    id: "part-pnea-suffix",
    text: "-pnea",
    type: "suffix",
    plainMeaning: "breathing",
    altMeanings: [],
    pronunciationText: "PNEE-uh",
    examples: ["dyspnea", "tachypnea"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 30,
  },
  {
    id: "part-dys-prefix",
    text: "dys-",
    type: "prefix",
    plainMeaning: "bad; difficult; abnormal",
    altMeanings: [],
    pronunciationText: "diss",
    examples: ["dyspnea"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 31,
  },
  {
    id: "part-oxia-suffix",
    text: "-oxia",
    type: "suffix",
    plainMeaning: "oxygen level or oxygen state",
    altMeanings: [],
    pronunciationText: "OK-see-uh",
    examples: ["hypoxia"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 32,
  },
  {
    id: "part-enter-combining",
    text: "enter/o",
    type: "combining_form",
    plainMeaning: "intestine",
    altMeanings: [],
    pronunciationText: "EN-ter-oh",
    examples: ["enteritis", "gastroenteritis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 33,
  },
  {
    id: "part-esophag-combining",
    text: "esophag/o",
    type: "combining_form",
    plainMeaning: "esophagus",
    altMeanings: [],
    pronunciationText: "eh-SOF-ah-goh",
    examples: ["esophagitis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 34,
  },
  {
    id: "part-cholecyst-combining",
    text: "cholecyst/o",
    type: "combining_form",
    plainMeaning: "gallbladder",
    altMeanings: [],
    pronunciationText: "KOH-lee-SIS-toh",
    examples: ["cholecystectomy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 35,
  }
];
