import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-cardi-root",
    text: "cardi",
    type: "root",
    plainMeaning: "heart",
    altMeanings: [],
    pronunciationText: "KAR-dee",
    examples: ["cardiac", "cardiology"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 1,
  },
  {
    id: "part-gastr-root",
    text: "gastr",
    type: "root",
    plainMeaning: "stomach",
    altMeanings: [],
    pronunciationText: "GAS-tr",
    examples: ["gastric", "gastrology"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 2,
  },
  {
    id: "part-neur-root",
    text: "neur",
    type: "root",
    plainMeaning: "nerve",
    altMeanings: [],
    pronunciationText: "nyoor",
    examples: ["neural", "neurology"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 3,
  },
  {
    id: "part-osteo-combining",
    text: "oste/o",
    type: "combining_form",
    plainMeaning: "bone",
    altMeanings: [],
    pronunciationText: "OS-tee-oh",
    examples: ["osteology", "osteotomy"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 4,
  },
  {
    id: "part-itis-suffix",
    text: "-itis",
    type: "suffix",
    plainMeaning: "inflammation",
    altMeanings: [],
    pronunciationText: "EYE-tis",
    examples: ["arthritis", "gastritis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-ology-suffix",
    text: "-logy",
    type: "suffix",
    plainMeaning: "study of",
    altMeanings: [],
    pronunciationText: "ol-uh-jee",
    examples: ["cardiology", "neurology"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-hyper-prefix",
    text: "hyper-",
    type: "prefix",
    plainMeaning: "too much; above normal",
    altMeanings: [],
    pronunciationText: "HY-per",
    examples: ["hypertension"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-hypo-prefix",
    text: "hypo-",
    type: "prefix",
    plainMeaning: "too little; below normal",
    altMeanings: [],
    pronunciationText: "HY-poh",
    examples: ["hypotension"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  },
  {
    id: "part-arthr-combining",
    text: "arthr/o",
    type: "combining_form",
    plainMeaning: "joint",
    altMeanings: [],
    pronunciationText: "AR-throh",
    examples: ["arthritis", "arthroscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 9,
  },
  {
    id: "part-hemat-combining",
    text: "hemat/o",
    type: "combining_form",
    plainMeaning: "blood",
    altMeanings: [],
    pronunciationText: "hee-MAT-oh",
    examples: ["hematology", "hematoma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 10,
  },
  {
    id: "part-derm-combining",
    text: "derm/o",
    type: "combining_form",
    plainMeaning: "skin",
    altMeanings: [],
    pronunciationText: "DERM-oh",
    examples: ["dermatitis", "dermatology"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 11,
  },
  {
    id: "part-hepat-combining",
    text: "hepat/o",
    type: "combining_form",
    plainMeaning: "liver",
    altMeanings: [],
    pronunciationText: "heh-PAT-oh",
    examples: ["hepatitis", "hepatology"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 12,
  },
  {
    id: "part-nephr-combining",
    text: "nephr/o",
    type: "combining_form",
    plainMeaning: "kidney",
    altMeanings: [],
    pronunciationText: "NEF-roh",
    examples: ["nephrology", "nephritis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 13,
  },
  {
    id: "part-algia-suffix",
    text: "-algia",
    type: "suffix",
    plainMeaning: "pain",
    altMeanings: [],
    pronunciationText: "AL-jee-uh",
    examples: ["neuralgia", "myalgia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 14,
  },
  {
    id: "part-appendic-combining",
    text: "appendic/o",
    type: "combining_form",
    plainMeaning: "appendix",
    altMeanings: [],
    pronunciationText: "ah-PEN-dih-koh",
    examples: ["appendectomy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 15,
  },
  {
    id: "part-col-combining",
    text: "col/o",
    type: "combining_form",
    plainMeaning: "colon",
    altMeanings: [],
    pronunciationText: "KOH-loh",
    examples: ["colonoscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 16,
  },
  {
    id: "part-ectomy-suffix",
    text: "-ectomy",
    type: "suffix",
    plainMeaning: "surgical removal",
    altMeanings: [],
    pronunciationText: "EK-toh-mee",
    examples: ["appendectomy", "tonsillectomy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 17,
  },
  {
    id: "part-otomy-suffix",
    text: "-otomy",
    type: "suffix",
    plainMeaning: "incision into",
    altMeanings: [],
    pronunciationText: "OT-oh-mee",
    examples: ["gastrotomy", "tracheotomy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 18,
  },
  {
    id: "part-scopy-suffix",
    text: "-scopy",
    type: "suffix",
    plainMeaning: "viewing with a scope",
    altMeanings: [],
    pronunciationText: "SKOH-pee",
    examples: ["colonoscopy", "endoscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 19,
  },
  {
    id: "part-gram-suffix",
    text: "-gram",
    type: "suffix",
    plainMeaning: "record or image",
    altMeanings: [],
    pronunciationText: "gram",
    examples: ["cardiogram", "angiogram"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 20,
  },
  {
    id: "part-tachy-prefix",
    text: "tachy-",
    type: "prefix",
    plainMeaning: "fast",
    altMeanings: [],
    pronunciationText: "TAK-ee",
    examples: ["tachycardia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 21,
  },
  {
    id: "part-brady-prefix",
    text: "brady-",
    type: "prefix",
    plainMeaning: "slow",
    altMeanings: [],
    pronunciationText: "BRAY-dee",
    examples: ["bradycardia"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 22,
  },
  {
    id: "part-angi-combining",
    text: "angi/o",
    type: "combining_form",
    plainMeaning: "vessel",
    altMeanings: [],
    pronunciationText: "AN-jee-oh",
    examples: ["angiogram", "angiology"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 23,
  },
  {
    id: "part-arteri-combining",
    text: "arteri/o",
    type: "combining_form",
    plainMeaning: "artery",
    altMeanings: [],
    pronunciationText: "ar-TEER-ee-oh",
    examples: ["arteritis", "arteriology"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 24,
  },
  {
    id: "part-ven-combining",
    text: "ven/o",
    type: "combining_form",
    plainMeaning: "vein",
    altMeanings: [],
    pronunciationText: "VEE-noh",
    examples: ["venogram", "venous"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 25,
  },
  {
    id: "part-bronch-combining",
    text: "bronch/o",
    type: "combining_form",
    plainMeaning: "bronchial tube; airway branch",
    altMeanings: [],
    pronunciationText: "BRONG-koh",
    examples: ["bronchitis", "bronchoscopy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 26,
  },
  {
    id: "part-trache-combining",
    text: "trache/o",
    type: "combining_form",
    plainMeaning: "trachea; windpipe",
    altMeanings: [],
    pronunciationText: "TRAY-kee-oh",
    examples: ["tracheotomy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 27,
  },
  {
    id: "part-pneum-combining",
    text: "pneum/o",
    type: "combining_form",
    plainMeaning: "lung; air",
    altMeanings: [],
    pronunciationText: "new-MOH",
    examples: ["pneumonia", "pneumothorax"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 28,
  },
  {
    id: "part-pulmon-combining",
    text: "pulmon/o",
    type: "combining_form",
    plainMeaning: "lung",
    altMeanings: [],
    pronunciationText: "PUL-moh-noh",
    examples: ["pulmonary"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 29,
  },
  {
    id: "part-pnea-suffix",
    text: "-pnea",
    type: "suffix",
    plainMeaning: "breathing",
    altMeanings: [],
    pronunciationText: "PNEE-uh",
    examples: ["dyspnea", "tachypnea"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 30,
  },
  {
    id: "part-dys-prefix",
    text: "dys-",
    type: "prefix",
    plainMeaning: "bad; difficult; abnormal",
    altMeanings: [],
    pronunciationText: "diss",
    examples: ["dyspnea"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 31,
  },
  {
    id: "part-oxia-suffix",
    text: "-oxia",
    type: "suffix",
    plainMeaning: "oxygen level or oxygen state",
    altMeanings: [],
    pronunciationText: "OK-see-uh",
    examples: ["hypoxia"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 32,
  },
  {
    id: "part-enter-combining",
    text: "enter/o",
    type: "combining_form",
    plainMeaning: "intestine",
    altMeanings: [],
    pronunciationText: "EN-ter-oh",
    examples: ["enteritis", "gastroenteritis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 33,
  },
  {
    id: "part-esophag-combining",
    text: "esophag/o",
    type: "combining_form",
    plainMeaning: "esophagus",
    altMeanings: [],
    pronunciationText: "eh-SOF-ah-goh",
    examples: ["esophagitis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 34,
  },
  {
    id: "part-cholecyst-combining",
    text: "cholecyst/o",
    type: "combining_form",
    plainMeaning: "gallbladder",
    altMeanings: [],
    pronunciationText: "KOH-lee-SIS-toh",
    examples: ["cholecystectomy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 35,
  },
  {
    id: "part-my-combining",
    text: "my/o",
    type: "combining_form",
    plainMeaning: "muscle",
    altMeanings: [],
    pronunciationText: "MY-oh",
    examples: ["myalgia", "myopathy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 36,
  },
  {
    id: "part-pathy-suffix",
    text: "-pathy",
    type: "suffix",
    plainMeaning: "disease; disorder",
    altMeanings: [],
    pronunciationText: "PATH-ee",
    examples: ["myopathy", "arthropathy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 37,
  },
  {
    id: "part-plasty-suffix",
    text: "-plasty",
    type: "suffix",
    plainMeaning: "surgical repair or reconstruction",
    altMeanings: [],
    pronunciationText: "PLAS-tee",
    examples: ["arthroplasty", "rhinoplasty"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 38,
  },
  {
    id: "part-cyst-combining",
    text: "cyst/o",
    type: "combining_form",
    plainMeaning: "bladder; sac",
    altMeanings: [],
    pronunciationText: "SIS-toh",
    examples: ["cystitis", "cystoscopy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 39,
  },
  {
    id: "part-uria-suffix",
    text: "-uria",
    type: "suffix",
    plainMeaning: "urine condition; urination",
    altMeanings: [],
    pronunciationText: "YOOR-ee-uh",
    examples: ["hematuria"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 40,
  },
  {
    id: "part-megaly-suffix",
    text: "-megaly",
    type: "suffix",
    plainMeaning: "enlargement",
    altMeanings: [],
    pronunciationText: "MEG-uh-lee",
    examples: ["cardiomegaly", "hepatomegaly"],
    prerequisiteIds: [],
    unitId: "unit-3",
    frequencyRank: 41,
  },
  {
    id: "part-emia-suffix",
    text: "-emia",
    type: "suffix",
    plainMeaning: "blood condition",
    altMeanings: [],
    pronunciationText: "EE-mee-uh",
    examples: ["anemia", "hyperglycemia"],
    prerequisiteIds: [],
    unitId: "unit-3",
    frequencyRank: 42,
  },
  {
    id: "part-graphy-suffix",
    text: "-graphy",
    type: "suffix",
    plainMeaning: "process of recording or imaging",
    altMeanings: [],
    pronunciationText: "GRAF-ee",
    examples: ["angiography", "cardiography"],
    prerequisiteIds: [],
    unitId: "unit-3",
    frequencyRank: 43,
  },
  {
    id: "part-pre-prefix",
    text: "pre-",
    type: "prefix",
    plainMeaning: "before",
    altMeanings: [],
    pronunciationText: "pree",
    examples: ["preoperative"],
    prerequisiteIds: [],
    unitId: "unit-4",
    frequencyRank: 44,
  },
  {
    id: "part-post-prefix",
    text: "post-",
    type: "prefix",
    plainMeaning: "after",
    altMeanings: [],
    pronunciationText: "post",
    examples: ["postoperative"],
    prerequisiteIds: [],
    unitId: "unit-4",
    frequencyRank: 45,
  },
  {
    id: "part-contra-prefix",
    text: "contra-",
    type: "prefix",
    plainMeaning: "against; opposing",
    altMeanings: [],
    pronunciationText: "KON-truh",
    examples: ["contraindication"],
    prerequisiteIds: [],
    unitId: "unit-4",
    frequencyRank: 46,
  },
  {
    id: "part-encephal-combining",
    text: "encephal/o",
    type: "combining_form",
    plainMeaning: "brain",
    altMeanings: [],
    pronunciationText: "en-SEF-ah-loh",
    examples: ["encephalitis", "encephalopathy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 47,
  },
  {
    id: "part-hemi-prefix",
    text: "hemi-",
    type: "prefix",
    plainMeaning: "half; one side",
    altMeanings: [],
    pronunciationText: "HEM-ee",
    examples: ["hemiplegia"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 48,
  },
  {
    id: "part-plegia-suffix",
    text: "-plegia",
    type: "suffix",
    plainMeaning: "paralysis",
    altMeanings: [],
    pronunciationText: "PLEE-jee-uh",
    examples: ["hemiplegia", "paraplegia"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 49,
  },
  {
    id: "part-glyc-combining",
    text: "glyc/o",
    type: "combining_form",
    plainMeaning: "sugar; glucose",
    altMeanings: [],
    pronunciationText: "GLY-koh",
    examples: ["hyperglycemia", "hypoglycemia"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 50,
  },
  {
    id: "part-thyroid-combining",
    text: "thyroid/o",
    type: "combining_form",
    plainMeaning: "thyroid gland",
    altMeanings: [],
    pronunciationText: "THY-royd-oh",
    examples: ["thyroiditis", "thyroidectomy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 51,
  },
  {
    id: "part-intra-prefix",
    text: "intra-",
    type: "prefix",
    plainMeaning: "within; inside",
    altMeanings: [],
    pronunciationText: "IN-truh",
    examples: ["intravenous"],
    prerequisiteIds: [],
    unitId: "unit-3",
    frequencyRank: 52,
  },
  {
    id: "part-osis-suffix",
    text: "-osis",
    type: "suffix",
    plainMeaning: "abnormal condition; disease state",
    altMeanings: [],
    pronunciationText: "OH-sis",
    examples: ["nephrosis", "dermatosis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 53,
  },
  {
    id: "part-oma-suffix",
    text: "-oma",
    type: "suffix",
    plainMeaning: "mass; tumor; swelling",
    altMeanings: [],
    pronunciationText: "OH-muh",
    examples: ["hematoma", "lymphoma"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 54,
  },
  {
    id: "part-hyster-combining",
    text: "hyster/o",
    type: "combining_form",
    plainMeaning: "uterus",
    altMeanings: [],
    pronunciationText: "HIS-ter-oh",
    examples: ["hysterectomy", "hysteroscopy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 55,
  },
  {
    id: "part-ovari-combining",
    text: "ovari/o",
    type: "combining_form",
    plainMeaning: "ovary",
    altMeanings: [],
    pronunciationText: "oh-VAIR-ee-oh",
    examples: ["ovariectomy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 56,
  },
  {
    id: "part-salping-combining",
    text: "salping/o",
    type: "combining_form",
    plainMeaning: "fallopian tube",
    altMeanings: [],
    pronunciationText: "sal-PING-goh",
    examples: ["salpingitis", "salpingectomy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 57,
  },
  {
    id: "part-immun-combining",
    text: "immun/o",
    type: "combining_form",
    plainMeaning: "immune; protection",
    altMeanings: [],
    pronunciationText: "ih-MYOON-oh",
    examples: ["immunology"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 58,
  },
  {
    id: "part-lymph-combining",
    text: "lymph/o",
    type: "combining_form",
    plainMeaning: "lymph; lymphatic tissue",
    altMeanings: [],
    pronunciationText: "LIMF-oh",
    examples: ["lymphoma", "lymphatic"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 59,
  },
  {
    id: "part-splen-combining",
    text: "splen/o",
    type: "combining_form",
    plainMeaning: "spleen",
    altMeanings: [],
    pronunciationText: "SPLEE-noh",
    examples: ["splenectomy", "splenomegaly"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 60,
  },
  {
    id: "part-cutane-combining",
    text: "cutane/o",
    type: "combining_form",
    plainMeaning: "skin",
    altMeanings: [],
    pronunciationText: "kyoo-TAY-nee-oh",
    examples: ["cutaneous", "subcutaneous"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 61,
  },
  {
    id: "part-sub-prefix",
    text: "sub-",
    type: "prefix",
    plainMeaning: "under; below",
    altMeanings: [],
    pronunciationText: "sub",
    examples: ["subcutaneous"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 62,
  },
  {
    id: "part-ophthalm-combining",
    text: "ophthalm/o",
    type: "combining_form",
    plainMeaning: "eye",
    altMeanings: [],
    pronunciationText: "off-THAL-moh",
    examples: ["ophthalmology"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 63,
  },
  {
    id: "part-ot-combining",
    text: "ot/o",
    type: "combining_form",
    plainMeaning: "ear",
    altMeanings: [],
    pronunciationText: "OH-toh",
    examples: ["otitis", "otoscopy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 64,
  },
  {
    id: "part-audi-combining",
    text: "audi/o",
    type: "combining_form",
    plainMeaning: "hearing",
    altMeanings: [],
    pronunciationText: "AW-dee-oh",
    examples: ["audiology"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 65,
  },
  {
    id: "part-onc-combining",
    text: "onc/o",
    type: "combining_form",
    plainMeaning: "tumor; cancer",
    altMeanings: [],
    pronunciationText: "ONG-koh",
    examples: ["oncology"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 66,
  },
  {
    id: "part-carcin-combining",
    text: "carcin/o",
    type: "combining_form",
    plainMeaning: "cancer",
    altMeanings: [],
    pronunciationText: "kar-SIN-oh",
    examples: ["carcinoma"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 67,
  },
  {
    id: "part-erythr-combining",
    text: "erythr/o",
    type: "combining_form",
    plainMeaning: "red",
    altMeanings: [],
    pronunciationText: "ee-RITH-roh",
    examples: ["erythrocyte"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 68,
  },
  {
    id: "part-leuk-combining",
    text: "leuk/o",
    type: "combining_form",
    plainMeaning: "white",
    altMeanings: [],
    pronunciationText: "LOO-koh",
    examples: ["leukocyte", "leukocytosis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 69,
  },
  {
    id: "part-cyt-combining",
    text: "cyt/o",
    type: "combining_form",
    plainMeaning: "cell",
    altMeanings: [],
    pronunciationText: "SY-toh",
    examples: ["erythrocyte", "leukocyte"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 70,
  },
  {
    id: "part-thromb-combining",
    text: "thromb/o",
    type: "combining_form",
    plainMeaning: "clot",
    altMeanings: [],
    pronunciationText: "THROM-boh",
    examples: ["thrombosis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 71,
  },
  {
    id: "part-poly-prefix",
    text: "poly-",
    type: "prefix",
    plainMeaning: "many; much",
    altMeanings: [],
    pronunciationText: "POL-ee",
    examples: ["polyuria"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 72,
  },
  {
    id: "part-olig-prefix",
    text: "olig-",
    type: "prefix",
    plainMeaning: "few; scanty",
    altMeanings: [],
    pronunciationText: "OL-ig",
    examples: ["oliguria"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 73,
  },
  {
    id: "part-pancreat-combining",
    text: "pancreat/o",
    type: "combining_form",
    plainMeaning: "pancreas",
    altMeanings: [],
    pronunciationText: "pan-kree-AT-oh",
    examples: ["pancreatitis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 74,
  },
  {
    id: "part-chole-combining",
    text: "chol/e",
    type: "combining_form",
    plainMeaning: "bile; gall",
    altMeanings: [],
    pronunciationText: "KOH-lee",
    examples: ["cholelithiasis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 75,
  },
  {
    id: "part-lithiasis-suffix",
    text: "-lithiasis",
    type: "suffix",
    plainMeaning: "stone condition; presence of stones",
    altMeanings: [],
    pronunciationText: "lith-EYE-uh-sis",
    examples: ["cholelithiasis", "nephrolithiasis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 76,
  },
  {
    id: "part-rhin-combining",
    text: "rhin/o",
    type: "combining_form",
    plainMeaning: "nose",
    altMeanings: [],
    pronunciationText: "RYE-noh",
    examples: ["rhinitis", "rhinorrhea"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 77,
  },
  {
    id: "part-sinus-combining",
    text: "sinus/o",
    type: "combining_form",
    plainMeaning: "sinus; air-filled cavity",
    altMeanings: [],
    pronunciationText: "SY-nus-oh",
    examples: ["sinusitis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 78,
  },
  {
    id: "part-pharyng-combining",
    text: "pharyng/o",
    type: "combining_form",
    plainMeaning: "pharynx; throat",
    altMeanings: [],
    pronunciationText: "fah-RING-goh",
    examples: ["pharyngitis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 79,
  },
  {
    id: "part-laryng-combining",
    text: "laryng/o",
    type: "combining_form",
    plainMeaning: "larynx; voice box",
    altMeanings: [],
    pronunciationText: "lah-RING-goh",
    examples: ["laryngitis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 80,
  },
  {
    id: "part-rrhea-suffix",
    text: "-rrhea",
    type: "suffix",
    plainMeaning: "flow; discharge",
    altMeanings: [],
    pronunciationText: "REE-uh",
    examples: ["rhinorrhea", "diarrhea"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 81,
  },
  {
    id: "part-pleur-combining",
    text: "pleur/o",
    type: "combining_form",
    plainMeaning: "pleura; lining around the lungs",
    altMeanings: [],
    pronunciationText: "PLOOR-oh",
    examples: ["pleuritis", "pleural"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 82,
  },
  {
    id: "part-thorac-combining",
    text: "thorac/o",
    type: "combining_form",
    plainMeaning: "chest",
    altMeanings: [],
    pronunciationText: "thor-ACK-oh",
    examples: ["thoracic", "thoracotomy"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 83,
  },
  {
    id: "part-centesis-suffix",
    text: "-centesis",
    type: "suffix",
    plainMeaning: "surgical puncture to remove fluid or air",
    altMeanings: [],
    pronunciationText: "sen-TEE-sis",
    examples: ["thoracentesis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 84,
  },
  {
    id: "part-plasia-suffix",
    text: "-plasia",
    type: "suffix",
    plainMeaning: "formation; growth; development",
    altMeanings: [],
    pronunciationText: "PLAY-zhuh",
    examples: ["dysplasia", "hyperplasia"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 85,
  },
  {
    id: "part-malacia-suffix",
    text: "-malacia",
    type: "suffix",
    plainMeaning: "softening",
    altMeanings: [],
    pronunciationText: "mah-LAY-shee-uh",
    examples: ["osteomalacia"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 86,
  },
  {
    id: "part-aden-combining",
    text: "aden/o",
    type: "combining_form",
    plainMeaning: "gland; node",
    altMeanings: [],
    pronunciationText: "AD-eh-noh",
    examples: ["adenopathy", "lymphadenitis"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 87,
  },
  {
    id: "part-men-combining",
    text: "men/o",
    type: "combining_form",
    plainMeaning: "menstruation; monthly flow",
    altMeanings: [],
    pronunciationText: "MEN-oh",
    examples: ["dysmenorrhea", "amenorrhea"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 88,
  },
  {
    id: "part-mast-combining",
    text: "mast/o",
    type: "combining_form",
    plainMeaning: "breast",
    altMeanings: [],
    pronunciationText: "MAS-toh",
    examples: ["mastitis", "mastalgia"],
    prerequisiteIds: [],
    unitId: "unit-2",
    frequencyRank: 89,
  },
  {
    id: "part-peri-prefix",
    text: "peri-",
    type: "prefix",
    plainMeaning: "around; surrounding",
    altMeanings: [],
    pronunciationText: "PAIR-ee",
    examples: ["pericarditis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 90,
  },
  {
    id: "part-endo-prefix",
    text: "endo-",
    type: "prefix",
    plainMeaning: "within; inner",
    altMeanings: [],
    pronunciationText: "EN-doh",
    examples: ["endocarditis", "endoscopy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 91,
  },
  {
    id: "part-epi-prefix",
    text: "epi-",
    type: "prefix",
    plainMeaning: "upon; on; above",
    altMeanings: [],
    pronunciationText: "EP-ee",
    examples: ["epigastric", "epidermal"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 92,
  },
  {
    id: "part-stomy-suffix",
    text: "-stomy",
    type: "suffix",
    plainMeaning: "surgically created opening",
    altMeanings: [],
    pronunciationText: "STOH-mee",
    examples: ["colostomy", "tracheostomy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 93,
  },
  {
    id: "part-ile-combining",
    text: "ile/o",
    type: "combining_form",
    plainMeaning: "ileum; lower small intestine",
    altMeanings: [],
    pronunciationText: "IL-ee-oh",
    examples: ["ileostomy"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 94,
  }
];
