import type { Part } from "../../types/content";

export const parts: Part[] = [
  {
    id: "part-cardi-root",
    text: "cardi",
    type: "root",
    plainMeaning: "heart",
    altMeanings: [],
    pronunciationText: "KAR-dee",
    examples: ["cardiac", "cardiology"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 1,
  },
  {
    id: "part-gastr-root",
    text: "gastr",
    type: "root",
    plainMeaning: "stomach",
    altMeanings: [],
    pronunciationText: "GAS-tr",
    examples: ["gastric", "gastrology"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 2,
  },
  {
    id: "part-neur-root",
    text: "neur",
    type: "root",
    plainMeaning: "nerve",
    altMeanings: [],
    pronunciationText: "nyoor",
    examples: ["neural", "neurology"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 3,
  },
  {
    id: "part-osteo-combining",
    text: "oste/o",
    type: "combining_form",
    plainMeaning: "bone",
    altMeanings: [],
    pronunciationText: "OS-tee-oh",
    examples: ["osteology", "osteotomy"],
    prerequisiteIds: [],
    unitId: "unit-0",
    frequencyRank: 4,
  },
  {
    id: "part-itis-suffix",
    text: "-itis",
    type: "suffix",
    plainMeaning: "inflammation",
    altMeanings: [],
    pronunciationText: "EYE-tis",
    examples: ["arthritis", "gastritis"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 5,
  },
  {
    id: "part-ology-suffix",
    text: "-logy",
    type: "suffix",
    plainMeaning: "study of",
    altMeanings: [],
    pronunciationText: "ol-uh-jee",
    examples: ["cardiology", "neurology"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 6,
  },
  {
    id: "part-hyper-prefix",
    text: "hyper-",
    type: "prefix",
    plainMeaning: "too much; above normal",
    altMeanings: [],
    pronunciationText: "HY-per",
    examples: ["hypertension"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 7,
  },
  {
    id: "part-hypo-prefix",
    text: "hypo-",
    type: "prefix",
    plainMeaning: "too little; below normal",
    altMeanings: [],
    pronunciationText: "HY-poh",
    examples: ["hypotension"],
    prerequisiteIds: [],
    unitId: "unit-1",
    frequencyRank: 8,
  }
];
