import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-batch-imaging-1",
    type: "root_match",
    prompt: "Which part means sound?",
    choices: ["son/o", "radi/o", "mamm/o", "-graph"],
    answer: "son/o",
    linkedTermIds: ["term-batch-sonogram", "term-batch-sonography"],
    linkedPartIds: ["part-batch-imaging-son-combining"],
  },
  {
    id: "exercise-batch-imaging-2",
    type: "infer_meaning",
    prompt: "What does `radiography` suggest?",
    choices: [
      "the process of making X-ray images",
      "an image of the breast",
      "an instrument that records the heart",
      "a scoped look into the chest",
    ],
    answer: "the process of making X-ray images",
    linkedTermIds: ["term-batch-radiography"],
    linkedPartIds: ["part-batch-imaging-radi-combining", "part-graphy-suffix"],
  },
  {
    id: "exercise-batch-imaging-3",
    type: "split_term",
    prompt: "Which suffix usually names a recorded image?",
    choices: ["-gram", "-graph", "-graphy", "-scopy"],
    answer: "-gram",
    linkedTermIds: ["term-batch-sonogram", "term-batch-mammogram", "term-batch-electrocardiogram"],
    linkedPartIds: ["part-gram-suffix"],
  },
  {
    id: "exercise-batch-imaging-4",
    type: "infer_meaning",
    prompt: "What does `mammogram` suggest?",
    choices: [
      "an X-ray image of the breast",
      "the process of making bladder images",
      "a device that records the heart",
      "live moving X-ray imaging",
    ],
    answer: "an X-ray image of the breast",
    linkedTermIds: ["term-batch-mammogram"],
    linkedPartIds: ["part-batch-imaging-mamm-combining", "part-gram-suffix"],
  },
  {
    id: "exercise-batch-imaging-5",
    type: "infer_meaning",
    prompt: "What does `sonography` suggest?",
    choices: [
      "the process of making sound-wave images",
      "viewing the abdomen with a scope",
      "the process of making vein images",
      "an instrument that records the heart",
    ],
    answer: "the process of making sound-wave images",
    linkedTermIds: ["term-batch-sonography"],
    linkedPartIds: ["part-batch-imaging-son-combining", "part-graphy-suffix"],
  },
  {
    id: "exercise-batch-imaging-6",
    type: "root_match",
    prompt: "Which combining form points to electricity?",
    choices: ["electr/o", "cardi/o", "fluor/o", "lapar/o"],
    answer: "electr/o",
    linkedTermIds: ["term-batch-electrocardiogram", "term-batch-electrocardiograph", "term-batch-electrocardiography"],
    linkedPartIds: ["part-batch-imaging-electr-combining"],
  },
  {
    id: "exercise-batch-imaging-7",
    type: "infer_meaning",
    prompt: "What does `electrocardiogram` suggest?",
    choices: [
      "a record of the heart's electrical activity",
      "the process of making vein images",
      "an X-ray image of the breast",
      "a scoped look into the chest",
    ],
    answer: "a record of the heart's electrical activity",
    linkedTermIds: ["term-batch-electrocardiogram"],
    linkedPartIds: ["part-batch-imaging-electr-combining", "part-batch-imaging-cardi-combining", "part-gram-suffix"],
  },
  {
    id: "exercise-batch-imaging-8",
    type: "split_term",
    prompt: "Which part names the instrument that records?",
    choices: ["-graph", "-gram", "-graphy", "-scopy"],
    answer: "-graph",
    linkedTermIds: ["term-batch-cardiograph", "term-batch-electrocardiograph"],
    linkedPartIds: ["part-batch-imaging-graph-suffix"],
  },
  {
    id: "exercise-batch-imaging-9",
    type: "infer_meaning",
    prompt: "What does `venography` suggest?",
    choices: [
      "the process of making vein images",
      "the process of making heart tracings",
      "viewing the abdomen with a scope",
      "an X-ray image of the breast",
    ],
    answer: "the process of making vein images",
    linkedTermIds: ["term-batch-venography"],
    linkedPartIds: ["part-ven-combining", "part-graphy-suffix"],
  },
  {
    id: "exercise-batch-imaging-10",
    type: "infer_meaning",
    prompt: "What does `fluoroscopy` suggest?",
    choices: [
      "live moving X-ray style imaging during a procedure",
      "a still breast image made with X-rays",
      "the process of making bladder images",
      "a device that records the heart",
    ],
    answer: "live moving X-ray style imaging during a procedure",
    linkedTermIds: ["term-batch-fluoroscopy"],
    linkedPartIds: ["part-batch-imaging-fluor-combining", "part-scopy-suffix"],
  },
  {
    id: "exercise-batch-imaging-11",
    type: "infer_meaning",
    prompt: "What does `thoracoscopy` suggest?",
    choices: [
      "viewing the chest with a scope",
      "viewing the bladder with a scope",
      "the process of making vein images",
      "the process of making sound-wave images",
    ],
    answer: "viewing the chest with a scope",
    linkedTermIds: ["term-batch-thoracoscopy"],
    linkedPartIds: ["part-thorac-combining", "part-scopy-suffix"],
  },
  {
    id: "exercise-batch-imaging-12",
    type: "infer_meaning",
    prompt: "What does `laparoscopy` suggest?",
    choices: [
      "viewing the abdomen with a scope",
      "viewing the chest with a scope",
      "recording the heart's electrical activity",
      "making a bladder image",
    ],
    answer: "viewing the abdomen with a scope",
    linkedTermIds: ["term-batch-laparoscopy"],
    linkedPartIds: ["part-batch-imaging-lapar-combining", "part-scopy-suffix"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-batch-imaging-records",
    title: "Imaging Roots and Records",
    unitId: "unit-1",
    objective: "Let's learn the roots that name common X-ray, sound, and breast imaging words.",
    whyItMatters: "These are the most common recording families in diagnostic language.",
    prerequisiteLessonIds: ["lesson-batch-definflam-path-and-stasis"],
    introducesPartIds: [
      "part-batch-imaging-radi-combining",
      "part-batch-imaging-son-combining",
      "part-batch-imaging-mamm-combining",
      "part-gram-suffix",
      "part-graphy-suffix",
    ],
    introducesTermIds: [
      "term-batch-radiography",
      "term-batch-sonogram",
      "term-batch-sonography",
      "term-batch-mammogram",
      "term-batch-mammography",
    ],
    reinforcesTermIds: [],
    exerciseSetIds: [
      "exercise-batch-imaging-1",
      "exercise-batch-imaging-2",
      "exercise-batch-imaging-3",
      "exercise-batch-imaging-4",
      "exercise-batch-imaging-5",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-heart-and-contrast-records",
    title: "Heart and Contrast Records",
    unitId: "unit-1",
    objective: "Let's learn the heart tracing and contrast-imaging families used across diagnostics.",
    whyItMatters: "These forms show up in cardiac tracing, vascular imaging, and urinary imaging words.",
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    introducesPartIds: [
      "part-batch-imaging-electr-combining",
      "part-batch-imaging-cardi-combining",
      "part-batch-imaging-graph-suffix",
      "part-gram-suffix",
      "part-graphy-suffix",
      "part-ven-combining",
      "part-cyst-combining",
    ],
    introducesTermIds: [
      "term-batch-cardiograph",
      "term-batch-electrocardiogram",
      "term-batch-electrocardiograph",
      "term-batch-electrocardiography",
      "term-batch-venography",
      "term-batch-cystography",
    ],
    reinforcesTermIds: ["term-batch-radiography", "term-batch-mammography"],
    exerciseSetIds: [
      "exercise-batch-imaging-6",
      "exercise-batch-imaging-7",
      "exercise-batch-imaging-8",
      "exercise-batch-imaging-9",
    ],
    estimatedMinutes: 9,
    status: "drafted",
  },
  {
    id: "lesson-batch-live-and-scope-imaging",
    title: "Live and Scope Imaging",
    unitId: "unit-1",
    objective: "Let's learn the live-imaging and scope words used during procedures.",
    whyItMatters: "These terms are common in procedure notes and imaging instructions.",
    prerequisiteLessonIds: ["lesson-batch-heart-and-contrast-records"],
    introducesPartIds: [
      "part-batch-imaging-fluor-combining",
      "part-batch-imaging-lapar-combining",
      "part-thorac-combining",
      "part-scopy-suffix",
    ],
    introducesTermIds: [
      "term-batch-fluoroscopy",
      "term-batch-thoracoscopy",
      "term-batch-laparoscopy",
    ],
    reinforcesTermIds: ["term-batch-cystography", "term-batch-venography"],
    exerciseSetIds: [
      "exercise-batch-imaging-10",
      "exercise-batch-imaging-11",
      "exercise-batch-imaging-12",
    ],
    estimatedMinutes: 7,
    status: "drafted",
  },
];
