import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-batch-measure-tools-1",
    type: "root_match",
    prompt: "Which suffix means an instrument for measuring?",
    choices: ["-meter", "-metry", "-graphy", "-gram"],
    answer: "-meter",
    explanation: "`-meter` points to the device, while `-metry` points to the measuring process.",
    linkedTermIds: [
      "term-batch-measure-spirometer",
      "term-batch-measure-oximeter",
      "term-batch-measure-thermometer",
    ],
    linkedPartIds: ["part-batch-measure-meter-suffix"],
  },
  {
    id: "exercise-batch-measure-tools-2",
    type: "infer_meaning",
    prompt: "What does `spirometry` mean?",
    choices: [
      "the process of measuring breathing",
      "the instrument that measures breathing",
      "the process of imaging the heart",
      "the record of brain electrical activity",
    ],
    answer: "the process of measuring breathing",
    explanation: "`spir/o` points to breathing and `-metry` points to the measuring process.",
    linkedTermIds: ["term-batch-measure-spirometry", "term-batch-measure-spirometer"],
    linkedPartIds: ["part-batch-measure-spir-combining", "part-batch-measure-metry-suffix", "part-batch-measure-meter-suffix"],
  },
  {
    id: "exercise-batch-measure-tools-3",
    type: "infer_meaning",
    prompt: "What does `oximeter` measure?",
    choices: ["oxygen level", "body temperature", "heart size", "urine output"],
    answer: "oxygen level",
    explanation: "`ox/o` keeps the family on oxygen measurement.",
    linkedTermIds: ["term-batch-measure-oximeter", "term-batch-measure-oximetry"],
    linkedPartIds: ["part-batch-measure-ox-combining", "part-batch-measure-meter-suffix"],
  },
  {
    id: "exercise-batch-measure-tools-4",
    type: "infer_meaning",
    prompt: "What does `thermometry` mean?",
    choices: [
      "the process of measuring temperature",
      "the instrument that measures temperature",
      "the process of recording heart sounds",
      "the process of cutting a section image",
    ],
    answer: "the process of measuring temperature",
    explanation: "`therm/o` gives temperature and `-metry` gives the measuring process.",
    linkedTermIds: ["term-batch-measure-thermometry", "term-batch-measure-thermometer"],
    linkedPartIds: ["part-batch-measure-therm-combining", "part-batch-measure-metry-suffix"],
  },
  {
    id: "exercise-batch-measure-records-1",
    type: "root_match",
    prompt: "Which suffix points to a record or image?",
    choices: ["-gram", "-graph", "-meter", "-metry"],
    answer: "-gram",
    explanation: "`-gram` is the record or image, while `-graph` is the recording instrument.",
    linkedTermIds: [
      "term-batch-measure-electroencephalogram",
      "term-batch-measure-myelogram",
    ],
    linkedPartIds: ["part-gram-suffix"],
  },
  {
    id: "exercise-batch-measure-records-2",
    type: "infer_meaning",
    prompt: "What does `electroencephalogram` mean?",
    choices: [
      "record of brain electrical activity",
      "process of recording brain electrical activity",
      "instrument that records brain electrical activity",
      "record of heart electrical activity",
    ],
    answer: "record of brain electrical activity",
    explanation: "This family becomes easier once you separate `-gram`, `-graph`, and `-graphy`.",
    linkedTermIds: [
      "term-batch-measure-electroencephalogram",
      "term-batch-measure-electroencephalograph",
      "term-batch-measure-electroencephalography",
    ],
    linkedPartIds: ["part-batch-imaging-electr-combining", "part-encephal-combining", "part-gram-suffix", "part-batch-imaging-graph-suffix", "part-graphy-suffix"],
  },
  {
    id: "exercise-batch-measure-records-3",
    type: "infer_meaning",
    prompt: "What does `myelography` mean?",
    choices: [
      "the process of imaging the spinal canal",
      "the instrument that images the spinal canal",
      "the process of measuring the spinal canal",
      "the record of oxygen level",
    ],
    answer: "the process of imaging the spinal canal",
    explanation: "`myel/o` points to spinal cord or marrow and `-graphy` points to the recording process.",
    linkedTermIds: ["term-batch-measure-myelography", "term-batch-measure-myelogram"],
    linkedPartIds: ["part-batch-growthmass-myel-combining", "part-graphy-suffix", "part-gram-suffix"],
  },
  {
    id: "exercise-batch-measure-records-4",
    type: "infer_meaning",
    prompt: "Which word names the instrument rather than the tracing or the process?",
    choices: [
      "electroencephalograph",
      "electroencephalogram",
      "electroencephalography",
      "myelography",
    ],
    answer: "electroencephalograph",
    explanation: "`-graph` points to the instrument that does the recording.",
    linkedTermIds: ["term-batch-measure-electroencephalograph"],
    linkedPartIds: ["part-batch-imaging-graph-suffix"],
  },
  {
    id: "exercise-batch-measure-section-1",
    type: "root_match",
    prompt: "Which combining form points to a section or slice?",
    choices: ["tom/o", "echo-", "ox/o", "spir/o"],
    answer: "tom/o",
    explanation: "`tom/o` is the section-imaging family root.",
    linkedTermIds: ["term-batch-measure-tomogram", "term-batch-measure-tomography"],
    linkedPartIds: ["part-batch-measure-tom-combining"],
  },
  {
    id: "exercise-batch-measure-section-2",
    type: "infer_meaning",
    prompt: "What does `tomography` mean?",
    choices: [
      "process of making section images",
      "instrument that makes section images",
      "record of oxygen level",
      "process of measuring temperature",
    ],
    answer: "process of making section images",
    explanation: "`tom/o` points to sectioning and `-graphy` points to recording or imaging.",
    linkedTermIds: ["term-batch-measure-tomography", "term-batch-measure-tomogram"],
    linkedPartIds: ["part-batch-measure-tom-combining", "part-graphy-suffix", "part-gram-suffix"],
  },
  {
    id: "exercise-batch-measure-section-3",
    type: "infer_meaning",
    prompt: "What does `echocardiography` mean?",
    choices: [
      "process of ultrasound imaging of the heart",
      "record of brain electrical activity",
      "instrument that measures temperature",
      "process of measuring breathing",
    ],
    answer: "process of ultrasound imaging of the heart",
    explanation: "`echo-` points to reflected sound and `cardi/o` points to the heart.",
    linkedTermIds: [
      "term-batch-measure-echocardiogram",
      "term-batch-measure-echocardiograph",
      "term-batch-measure-echocardiography",
    ],
    linkedPartIds: ["part-batch-measure-echo-prefix", "part-batch-imaging-cardi-combining", "part-gram-suffix", "part-batch-imaging-graph-suffix", "part-graphy-suffix"],
  },
  {
    id: "exercise-batch-measure-section-4",
    type: "infer_meaning",
    prompt: "Which term names the heart ultrasound image itself rather than the instrument or the process?",
    choices: [
      "echocardiogram",
      "echocardiograph",
      "echocardiography",
      "electrocardiography",
    ],
    answer: "echocardiogram",
    explanation: "`-gram` points to the recorded image itself.",
    linkedTermIds: ["term-batch-measure-echocardiogram"],
    linkedPartIds: ["part-gram-suffix"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-batch-measurement-tools",
    title: "Measurement Tools and Tests",
    unitId: "unit-1",
    objective: "Let's learn the endings that separate measuring instruments from the measuring process itself.",
    whyItMatters: "A small set of endings unlocks many common monitor and test names.",
    prerequisiteLessonIds: ["lesson-batch-fluid-discharge-flow"],
    introducesPartIds: [
      "part-batch-measure-metr-combining",
      "part-batch-measure-meter-suffix",
      "part-batch-measure-metry-suffix",
      "part-batch-measure-spir-combining",
      "part-batch-measure-ox-combining",
      "part-batch-measure-therm-combining",
    ],
    introducesTermIds: [
      "term-batch-measure-spirometer",
      "term-batch-measure-spirometry",
      "term-batch-measure-oximeter",
      "term-batch-measure-oximetry",
      "term-batch-measure-thermometer",
      "term-batch-measure-thermometry",
    ],
    reinforcesTermIds: ["term-batch-electrocardiogram", "term-batch-electrocardiography"],
    exerciseSetIds: [
      "exercise-batch-measure-tools-1",
      "exercise-batch-measure-tools-2",
      "exercise-batch-measure-tools-3",
      "exercise-batch-measure-tools-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-measurement-records",
    title: "Electrical and Spinal Records",
    unitId: "unit-1",
    objective: "Let's learn the record, instrument, and process endings used in brain and spinal studies.",
    whyItMatters: "These words recur in neurology, imaging, and chart summaries.",
    prerequisiteLessonIds: ["lesson-batch-measurement-tools"],
    introducesPartIds: [],
    introducesTermIds: [
      "term-batch-measure-electroencephalogram",
      "term-batch-measure-electroencephalograph",
      "term-batch-measure-electroencephalography",
      "term-batch-measure-myelogram",
      "term-batch-measure-myelography",
    ],
    reinforcesTermIds: [
      "term-batch-electrocardiogram",
      "term-batch-electrocardiograph",
      "term-batch-electrocardiography",
      "term-batch-cardiograph",
    ],
    exerciseSetIds: [
      "exercise-batch-measure-records-1",
      "exercise-batch-measure-records-2",
      "exercise-batch-measure-records-3",
      "exercise-batch-measure-records-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-measurement-section-imaging",
    title: "Section and Echo Imaging",
    unitId: "unit-1",
    objective: "Let's learn the section-imaging and echo-imaging families that show up constantly in reports.",
    whyItMatters: "These roots explain a large share of common scan and heart-study vocabulary.",
    prerequisiteLessonIds: ["lesson-batch-measurement-records"],
    introducesPartIds: [
      "part-batch-measure-tom-combining",
      "part-batch-measure-echo-prefix",
    ],
    introducesTermIds: [
      "term-batch-measure-tomogram",
      "term-batch-measure-tomography",
      "term-batch-measure-echocardiogram",
      "term-batch-measure-echocardiograph",
      "term-batch-measure-echocardiography",
    ],
    reinforcesTermIds: [
      "term-batch-radiography",
      "term-batch-sonogram",
      "term-batch-sonography",
      "term-batch-mammogram",
      "term-batch-mammography",
    ],
    exerciseSetIds: [
      "exercise-batch-measure-section-1",
      "exercise-batch-measure-section-2",
      "exercise-batch-measure-section-3",
      "exercise-batch-measure-section-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
];
