import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-batch-imaging-1",
    type: "root_match",
    prompt: "Which part means sound?",
    choices: ["son/o", "radi/o", "angi/o", "-gram"],
    answer: "son/o",
    explanation: "`son/o` points to sound in terms like `sonogram` and `sonography`.",
    linkedTermIds: ["term-batch-sonogram", "term-batch-sonography"],
    linkedPartIds: ["part-batch-imaging-son-combining"],
  },
  {
    id: "exercise-batch-imaging-2",
    type: "infer_meaning",
    prompt: "If `radi/o` means X-ray and `-graph` means record or image, what does `radiograph` suggest?",
    choices: [
      "an image made with X-rays",
      "the process of making sound images",
      "an instrument that records the heart",
      "viewing the colon with a scope",
    ],
    answer: "an image made with X-rays",
    explanation: "The parts combine to mean a recorded image made with radiation.",
    linkedTermIds: ["term-batch-radiograph"],
    linkedPartIds: ["part-batch-imaging-radi-combining", "part-batch-imaging-graph-suffix"],
  },
  {
    id: "exercise-batch-imaging-3",
    type: "split_term",
    prompt: "Which suffix usually names the process of recording?",
    choices: ["-graphy", "-scopy", "-gram", "-graph"],
    answer: "-graphy",
    explanation: "`-graphy` points to the process of recording or making an image.",
    linkedTermIds: ["term-batch-radiography", "term-batch-sonography", "term-batch-mammography"],
    linkedPartIds: ["part-batch-imaging-graphy-suffix"],
  },
  {
    id: "exercise-batch-imaging-4",
    type: "cloze",
    prompt: "Complete the rule: `-gram` usually means a record or ___.",
    choices: ["image", "infection", "muscle", "joint"],
    answer: "image",
    explanation: "`-gram` is the recording noun form used in many imaging words.",
    linkedTermIds: ["term-batch-sonogram", "term-batch-mammogram", "term-batch-angiogram"],
    linkedPartIds: ["part-batch-imaging-gram-suffix"],
  },
  {
    id: "exercise-batch-imaging-5",
    type: "root_match",
    prompt: "Which part means vessel?",
    choices: ["angi/o", "cardi/o", "electr/o", "endo-"],
    answer: "angi/o",
    explanation: "`angi/o` points to a vessel, often a blood vessel.",
    linkedTermIds: ["term-batch-angiogram", "term-batch-angiography"],
    linkedPartIds: ["part-batch-imaging-angi-combining"],
  },
  {
    id: "exercise-batch-imaging-6",
    type: "infer_meaning",
    prompt: "What does `electrocardiogram` suggest?",
    choices: [
      "a record of the heart's electrical activity",
      "an image of the colon",
      "a sound-based picture of the breast",
      "viewing inside with a scope",
    ],
    answer: "a record of the heart's electrical activity",
    explanation: "`electr/o` and `cardi/o` point to the heart's electrical recording.",
    linkedTermIds: ["term-batch-electrocardiogram"],
    linkedPartIds: [
      "part-batch-imaging-electr-combining",
      "part-batch-imaging-cardi-combining",
      "part-batch-imaging-gram-suffix",
    ],
  },
  {
    id: "exercise-batch-imaging-7",
    type: "split_term",
    prompt: "Which part names the instrument that records?",
    choices: ["-graph", "-gram", "-graphy", "-scopy"],
    answer: "-graph",
    explanation: "`-graph` points to the device or instrument that records.",
    linkedTermIds: ["term-batch-cardiograph", "term-batch-electrocardiograph"],
    linkedPartIds: ["part-batch-imaging-graph-suffix"],
  },
  {
    id: "exercise-batch-imaging-8",
    type: "infer_meaning",
    prompt: "What does `endoscopy` suggest?",
    choices: [
      "viewing the inside of something with a scope",
      "recording the heart with electricity",
      "an X-ray image of the breast",
      "an image of a vessel",
    ],
    answer: "viewing the inside of something with a scope",
    explanation: "The prefix `endo-` means within and `-scopy` means viewing with a scope.",
    linkedTermIds: ["term-batch-endoscopy"],
    linkedPartIds: ["part-batch-imaging-endo-prefix", "part-batch-imaging-scopy-suffix"],
  },
  {
    id: "exercise-batch-imaging-9",
    type: "infer_meaning",
    prompt: "What does `bronchoscopy` suggest?",
    choices: [
      "viewing the bronchial tubes with a scope",
      "the process of making vessel images",
      "an X-ray image of the breast",
      "a recording of heart electricity",
    ],
    answer: "viewing the bronchial tubes with a scope",
    explanation: "`bronch/o` points to the airway branches and `-scopy` points to scope viewing.",
    linkedTermIds: ["term-batch-bronchoscopy"],
    linkedPartIds: ["part-batch-imaging-bronch-combining", "part-batch-imaging-scopy-suffix"],
  },
  {
    id: "exercise-batch-imaging-10",
    type: "infer_meaning",
    prompt: "Which term means viewing the colon with a scope?",
    choices: ["colonoscopy", "radiography", "mammography", "angiography"],
    answer: "colonoscopy",
    explanation: "`col/o` points to the colon and `-scopy` points to scope viewing.",
    linkedTermIds: ["term-batch-colonoscopy"],
    linkedPartIds: ["part-batch-imaging-col-combining", "part-batch-imaging-scopy-suffix"],
  },
  {
    id: "exercise-batch-imaging-11",
    type: "cloze",
    prompt: "Complete the idea: `mammography` is the process of making breast ___.",
    choices: ["images", "incisions", "infection", "records"],
    answer: "images",
    explanation: "The term combines the breast root with the recording process suffix.",
    linkedTermIds: ["term-batch-mammography", "term-batch-mammogram"],
    linkedPartIds: ["part-batch-imaging-mamm-combining", "part-batch-imaging-graphy-suffix"],
  },
  {
    id: "exercise-batch-imaging-12",
    type: "infer_meaning",
    prompt: "What does `angiography` suggest?",
    choices: [
      "the process of making vessel images",
      "the process of viewing a colon with a scope",
      "an instrument that records the heart",
      "an image made with sound waves",
    ],
    answer: "the process of making vessel images",
    explanation: "`angi/o` points to vessels and `-graphy` points to the process of recording.",
    linkedTermIds: ["term-batch-angiography"],
    linkedPartIds: ["part-batch-imaging-angi-combining", "part-batch-imaging-graphy-suffix"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-batch-imaging-records",
    title: "Imaging Roots and Records",
    unitId: "unit-1",
    objective: "Learn the roots that name X-ray, sound, and breast imaging words.",
    whyItMatters: "These are the most common recording families in diagnostic language.",
    prerequisiteLessonIds: ["lesson-unit1-common-prefixes", "lesson-unit1-core-body-roots"],
    introducesPartIds: [
      "part-batch-imaging-radi-combining",
      "part-batch-imaging-son-combining",
      "part-batch-imaging-mamm-combining",
      "part-batch-imaging-gram-suffix",
      "part-batch-imaging-graph-suffix",
      "part-batch-imaging-graphy-suffix",
    ],
    introducesTermIds: [
      "term-batch-radiograph",
      "term-batch-radiography",
      "term-batch-sonogram",
      "term-batch-sonography",
      "term-batch-mammogram",
      "term-batch-mammography",
    ],
    reinforcesTermIds: [],
    exerciseSetIds: [
      "exercise-batch-imaging-1",
      "exercise-batch-imaging-2",
      "exercise-batch-imaging-3",
      "exercise-batch-imaging-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-vascular-heart-records",
    title: "Vessel and Heart Records",
    unitId: "unit-1",
    objective: "Learn the vessel, heart, and electricity families used in common tracing words.",
    whyItMatters: "These forms show up in vessel imaging and heart tracing words everywhere.",
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    introducesPartIds: [
      "part-batch-imaging-angi-combining",
      "part-batch-imaging-electr-combining",
      "part-batch-imaging-cardi-combining",
      "part-batch-imaging-gram-suffix",
      "part-batch-imaging-graph-suffix",
      "part-batch-imaging-graphy-suffix",
    ],
    introducesTermIds: [
      "term-batch-angiogram",
      "term-batch-angiography",
      "term-batch-cardiogram",
      "term-batch-cardiograph",
      "term-batch-cardiography",
      "term-batch-electrocardiogram",
      "term-batch-electrocardiograph",
      "term-batch-electrocardiography",
    ],
    reinforcesTermIds: ["term-batch-radiograph", "term-batch-radiography"],
    exerciseSetIds: [
      "exercise-batch-imaging-5",
      "exercise-batch-imaging-6",
      "exercise-batch-imaging-7",
      "exercise-batch-imaging-12",
    ],
    estimatedMinutes: 9,
    status: "drafted",
  },
  {
    id: "lesson-batch-scope-procedures",
    title: "Scope Procedures and Inside Views",
    unitId: "unit-1",
    objective: "Learn the scope family used for looking inside tubes and organs.",
    whyItMatters: "These terms are common in procedure notes and diagnostic instructions.",
    prerequisiteLessonIds: [
      "lesson-batch-imaging-records",
      "lesson-batch-vascular-heart-records",
    ],
    introducesPartIds: [
      "part-batch-imaging-endo-prefix",
      "part-batch-imaging-bronch-combining",
      "part-batch-imaging-col-combining",
      "part-batch-imaging-scopy-suffix",
    ],
    introducesTermIds: [
      "term-batch-bronchoscopy",
      "term-batch-colonoscopy",
      "term-batch-endoscopy",
    ],
    reinforcesTermIds: [
      "term-batch-radiograph",
      "term-batch-radiography",
      "term-batch-angiogram",
      "term-batch-angiography",
    ],
    exerciseSetIds: [
      "exercise-batch-imaging-8",
      "exercise-batch-imaging-9",
      "exercise-batch-imaging-10",
      "exercise-batch-imaging-11",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
];
