import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-batch-growthmass-formation-1",
    type: "root_match",
    prompt: "Which suffix points to formation or growth?",
    choices: ["-plasia", "-uria", "-rrhea", "-algia"],
    answer: "-plasia",
    linkedTermIds: [
      "term-batch-neoplasia",
      "term-hyperplasia",
      "term-hypoplasia",
      "term-dysplasia",
    ],
    linkedPartIds: ["part-plasia-suffix"],
  },
  {
    id: "exercise-batch-growthmass-formation-2",
    type: "infer_meaning",
    prompt: "What does `neoplastic` mean?",
    choices: [
      "pertaining to new abnormal growth",
      "low blood cell count",
      "pain in a nerve",
      "surgical repair",
    ],
    answer: "pertaining to new abnormal growth",
    linkedTermIds: ["term-batch-growthmass-neoplastic"],
    linkedPartIds: ["part-batch-inflammatory-neo-prefix", "part-batch-growthmass-plasm-combining", "part-batch-definflam-ic-suffix"],
  },
  {
    id: "exercise-batch-growthmass-formation-3",
    type: "infer_meaning",
    prompt: "Which word means the tissue is underdeveloped rather than overgrown?",
    choices: ["hypoplastic", "hyperplastic", "neoplastic", "dysplastic"],
    answer: "hypoplastic",
    linkedTermIds: [
      "term-batch-growthmass-hypoplastic",
      "term-batch-growthmass-hyperplastic",
    ],
    linkedPartIds: ["part-hypo-prefix", "part-hyper-prefix", "part-plasia-suffix"],
  },
  {
    id: "exercise-batch-growthmass-formation-4",
    type: "infer_meaning",
    prompt: "What does `metaplastic` signal?",
    choices: [
      "a changed tissue type",
      "normal tissue development",
      "complete tissue removal",
      "blood vessel imaging",
    ],
    answer: "a changed tissue type",
    linkedTermIds: ["term-batch-growthmass-metaplastic"],
    linkedPartIds: ["part-batch-inflammatory-meta-prefix", "part-plasia-suffix", "part-batch-definflam-ic-suffix"],
  },
  {
    id: "exercise-batch-growthmass-common-1",
    type: "root_match",
    prompt: "Which combining form points to gland tissue?",
    choices: ["aden/o", "melan/o", "lip/o", "myel/o"],
    answer: "aden/o",
    linkedTermIds: ["term-batch-growthmass-adenoma", "term-batch-growthmass-adenocarcinoma"],
    linkedPartIds: ["part-aden-combining"],
  },
  {
    id: "exercise-batch-growthmass-common-2",
    type: "infer_meaning",
    prompt: "What does `adenoma` mean?",
    choices: ["gland tumor", "nerve tumor", "fat tumor", "muscle tumor"],
    answer: "gland tumor",
    linkedTermIds: ["term-batch-growthmass-adenoma"],
    linkedPartIds: ["part-aden-combining", "part-oma-suffix"],
  },
  {
    id: "exercise-batch-growthmass-common-3",
    type: "infer_meaning",
    prompt: "What does `melanoma` literally point toward?",
    choices: [
      "a dark-pigment tumor",
      "a glandular infection",
      "a blood test record",
      "a bone-softening condition",
    ],
    answer: "a dark-pigment tumor",
    linkedTermIds: ["term-batch-growthmass-melanoma"],
    linkedPartIds: ["part-batch-growthmass-melan-combining", "part-oma-suffix"],
  },
  {
    id: "exercise-batch-growthmass-common-4",
    type: "infer_meaning",
    prompt: "Which word combines gland language with cancer language?",
    choices: ["adenocarcinoma", "lipoma", "myeloma", "melanoma"],
    answer: "adenocarcinoma",
    linkedTermIds: ["term-batch-growthmass-adenocarcinoma"],
    linkedPartIds: ["part-aden-combining", "part-carcin-combining", "part-oma-suffix"],
  },
  {
    id: "exercise-batch-growthmass-tissue-1",
    type: "root_match",
    prompt: "Which combining form points to fibrous tissue?",
    choices: ["fibr/o", "gli/o", "granul/o", "papill/o"],
    answer: "fibr/o",
    linkedTermIds: ["term-batch-growthmass-fibroma", "term-batch-growthmass-fibroadenoma"],
    linkedPartIds: ["part-batch-growthmass-fibr-combining"],
  },
  {
    id: "exercise-batch-growthmass-tissue-2",
    type: "infer_meaning",
    prompt: "What does `granuloma` mean in plain English?",
    choices: [
      "a small grain-like inflammatory lump",
      "a tumor of dark pigment cells",
      "a record of tissue growth",
      "an underdeveloped organ",
    ],
    answer: "a small grain-like inflammatory lump",
    linkedTermIds: ["term-batch-growthmass-granuloma"],
    linkedPartIds: ["part-batch-growthmass-granul-combining", "part-oma-suffix"],
  },
  {
    id: "exercise-batch-growthmass-tissue-3",
    type: "infer_meaning",
    prompt: "What does `glioma` point to?",
    choices: [
      "a tumor of glial support tissue",
      "a tumor of muscle tissue",
      "a tumor of bone tissue",
      "a glandular tumor",
    ],
    answer: "a tumor of glial support tissue",
    linkedTermIds: ["term-batch-growthmass-glioma"],
    linkedPartIds: ["part-batch-growthmass-gli-combining", "part-oma-suffix"],
  },
  {
    id: "exercise-batch-growthmass-tissue-4",
    type: "infer_meaning",
    prompt: "Which term means connective-tissue cancer rather than a benign-looking mass word?",
    choices: ["sarcoma", "papilloma", "fibroma", "granuloma"],
    answer: "sarcoma",
    linkedTermIds: ["term-batch-growthmass-sarcoma"],
    linkedPartIds: ["part-batch-growthmass-sarc-combining", "part-oma-suffix"],
  },
  {
    id: "exercise-batch-growthmass-oma-1",
    type: "root_match",
    prompt: "Which root points to bone?",
    choices: ["oste/o", "my/o", "neur", "angi/o"],
    answer: "oste/o",
    linkedTermIds: ["term-batch-growthmass-osteoma"],
    linkedPartIds: ["part-osteo-combining"],
  },
  {
    id: "exercise-batch-growthmass-oma-2",
    type: "infer_meaning",
    prompt: "What does `hemangioma` mean?",
    choices: [
      "a benign growth made of blood vessels",
      "a low red-cell count",
      "a gland tumor",
      "a brain recording",
    ],
    answer: "a benign growth made of blood vessels",
    linkedTermIds: ["term-batch-growthmass-hemangioma"],
    linkedPartIds: ["part-hem-combining", "part-angi-combining", "part-oma-suffix"],
  },
  {
    id: "exercise-batch-growthmass-oma-3",
    type: "infer_meaning",
    prompt: "Which word means a fibrous gland tumor often discussed in breast imaging?",
    choices: ["fibroadenoma", "neuroma", "myoma", "osteoma"],
    answer: "fibroadenoma",
    linkedTermIds: ["term-batch-growthmass-fibroadenoma"],
    linkedPartIds: ["part-batch-growthmass-fibr-combining", "part-aden-combining", "part-oma-suffix"],
  },
  {
    id: "exercise-batch-growthmass-oma-4",
    type: "infer_meaning",
    prompt: "What does `neuroma` mean?",
    choices: ["nerve tumor", "muscle tumor", "bone tumor", "fat tumor"],
    answer: "nerve tumor",
    linkedTermIds: ["term-batch-growthmass-meningioma"],
    linkedPartIds: ["part-batch-inflammatory-mening-combining", "part-oma-suffix"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-batch-growthmass-formation-shifts",
    title: "Growth and Formation Shifts",
    unitId: "unit-1",
    objective: "Let's learn the growth-family words that mark new, excessive, reduced, or abnormal formation.",
    whyItMatters: "These patterns appear constantly in pathology, imaging, and biopsy language.",
    prerequisiteLessonIds: ["lesson-batch-flow-protrusion-roots"],
    introducesPartIds: ["part-batch-growthmass-plasm-combining"],
    introducesTermIds: [
      "term-batch-growthmass-metaplastic",
      "term-batch-growthmass-neoplastic",
      "term-batch-growthmass-hyperplastic",
      "term-batch-growthmass-hypoplastic",
      "term-batch-growthmass-dysplastic",
    ],
    reinforcesTermIds: [
      "term-neoplasm",
      "term-batch-neoplasia",
      "term-hyperplasia",
      "term-hypoplasia",
      "term-dysplasia",
    ],
    exerciseSetIds: [
      "exercise-batch-growthmass-formation-1",
      "exercise-batch-growthmass-formation-2",
      "exercise-batch-growthmass-formation-3",
      "exercise-batch-growthmass-formation-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-growthmass-common-masses",
    title: "Common Mass Words",
    unitId: "unit-1",
    objective: "Let's learn the most common mass words built from gland, pigment, fat, and marrow roots.",
    whyItMatters: "These are the tumor-family words learners keep seeing in reports and chart notes.",
    prerequisiteLessonIds: ["lesson-batch-growthmass-formation-shifts"],
    introducesPartIds: [
      "part-batch-growthmass-melan-combining",
      "part-batch-growthmass-lip-combining",
      "part-batch-growthmass-myel-combining",
    ],
    introducesTermIds: [
      "term-batch-growthmass-adenoma",
      "term-batch-growthmass-adenocarcinoma",
      "term-batch-growthmass-melanoma",
      "term-batch-growthmass-lipoma",
      "term-batch-growthmass-myeloma",
    ],
    reinforcesTermIds: ["term-carcinoma", "term-lymphoma", "term-hematoma"],
    exerciseSetIds: [
      "exercise-batch-growthmass-common-1",
      "exercise-batch-growthmass-common-2",
      "exercise-batch-growthmass-common-3",
      "exercise-batch-growthmass-common-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-growthmass-tissue-masses",
    title: "Tissue and Support-Tissue Masses",
    unitId: "unit-1",
    objective: "Let's learn the mass words built from fibrous, glial, connective-tissue, and inflammatory-lump roots.",
    whyItMatters: "These roots make dense pathology language much easier to decode.",
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-masses"],
    introducesPartIds: [
      "part-batch-growthmass-granul-combining",
      "part-batch-growthmass-fibr-combining",
      "part-batch-growthmass-gli-combining",
      "part-batch-growthmass-papill-combining",
      "part-batch-growthmass-sarc-combining",
    ],
    introducesTermIds: [
      "term-batch-growthmass-granuloma",
      "term-batch-growthmass-fibroma",
      "term-batch-growthmass-glioma",
      "term-batch-growthmass-papilloma",
      "term-batch-growthmass-sarcoma",
    ],
    reinforcesTermIds: ["term-carcinoma", "term-neoplasm", "term-oncology"],
    exerciseSetIds: [
      "exercise-batch-growthmass-tissue-1",
      "exercise-batch-growthmass-tissue-2",
      "exercise-batch-growthmass-tissue-3",
      "exercise-batch-growthmass-tissue-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-growthmass-common-oma-patterns",
    title: "Common -Oma Recombinations",
    unitId: "unit-1",
    objective: "Let's learn the familiar `-oma` combinations that recur across bone, muscle, nerve, vessel, and gland language.",
    whyItMatters: "Once these recombinations feel normal, pathology terms stop looking random.",
    prerequisiteLessonIds: ["lesson-batch-growthmass-tissue-masses"],
    introducesPartIds: [],
    introducesTermIds: [
      "term-batch-growthmass-osteoma",
      "term-batch-growthmass-myoma",
      "term-batch-growthmass-hemangioma",
      "term-batch-growthmass-fibroadenoma",
      "term-batch-growthmass-meningioma",
    ],
    reinforcesTermIds: [
      "term-batch-growthmass-adenoma",
      "term-batch-growthmass-lipoma",
      "term-batch-growthmass-melanoma",
    ],
    exerciseSetIds: [
      "exercise-batch-growthmass-oma-1",
      "exercise-batch-growthmass-oma-2",
      "exercise-batch-growthmass-oma-3",
      "exercise-batch-growthmass-oma-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
];
