import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-batch-inflammation-1",
    type: "root_match",
    prompt: "Which suffix means inflammation?",
    choices: ["-itis", "-megaly", "-cele", "-rrhagia"],
    answer: "-itis",
    linkedTermIds: [
      "term-batch-neuritis",
      "term-batch-appendicitis",
      "term-batch-peritonitis",
      "term-batch-conjunctivitis",
      "term-batch-tonsillitis",
    ],
    linkedPartIds: ["part-itis-suffix"],
  },
  {
    id: "exercise-batch-inflammation-2",
    type: "infer_meaning",
    prompt: "What does `appendicitis` mean?",
    choices: [
      "inflammation of the appendix",
      "narrowing of the appendix",
      "bleeding from the appendix",
      "a protrusion of the appendix",
    ],
    answer: "inflammation of the appendix",
    linkedTermIds: ["term-batch-appendicitis"],
    linkedPartIds: ["part-appendic-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-batch-inflammation-3",
    type: "root_match",
    prompt: "Which combining form points to the peritoneum?",
    choices: ["periton/o", "tonsill/o", "phleb/o", "cervic/o"],
    answer: "periton/o",
    linkedTermIds: ["term-batch-peritonitis"],
    linkedPartIds: ["part-batch-inflammatory-periton-combining"],
  },
  {
    id: "exercise-batch-inflammation-4",
    type: "infer_meaning",
    prompt: "What does `tonsillitis` mean?",
    choices: [
      "inflammation of the tonsils",
      "narrowing of the tonsils",
      "enlargement of the tonsils",
      "bleeding from the tonsils",
    ],
    answer: "inflammation of the tonsils",
    linkedTermIds: ["term-batch-tonsillitis"],
    linkedPartIds: ["part-batch-inflammatory-tonsill-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-batch-inflammation-5",
    type: "root_match",
    prompt: "Which combining form points to a vein?",
    choices: ["phleb/o", "vagin/o", "mening/o", "conjunctiv/o"],
    answer: "phleb/o",
    linkedTermIds: ["term-batch-phlebitis"],
    linkedPartIds: ["part-batch-inflammatory-phleb-combining"],
  },
  {
    id: "exercise-batch-inflammation-6",
    type: "infer_meaning",
    prompt: "What does `lymphangitis` mean?",
    choices: [
      "inflammation of lymph vessels",
      "narrowing of lymph vessels",
      "bleeding from lymph vessels",
      "swelling caused by too much lymph",
    ],
    answer: "inflammation of lymph vessels",
    linkedTermIds: ["term-batch-lymphangitis"],
    linkedPartIds: ["part-lymph-combining", "part-angi-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-batch-inflammation-7",
    type: "infer_meaning",
    prompt: "What does `meningitis` mean?",
    choices: [
      "inflammation of the meninges",
      "narrowing of the meninges",
      "enlargement of the meninges",
      "bleeding from the meninges",
    ],
    answer: "inflammation of the meninges",
    linkedTermIds: ["term-batch-meningitis"],
    linkedPartIds: ["part-batch-inflammatory-mening-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-batch-inflammation-8",
    type: "infer_meaning",
    prompt: "What does `salpingitis` mean?",
    choices: [
      "inflammation of a fallopian tube",
      "narrowing of a fallopian tube",
      "swelling of a fallopian tube",
      "bleeding from a fallopian tube",
    ],
    answer: "inflammation of a fallopian tube",
    linkedTermIds: ["term-salpingitis"],
    linkedPartIds: ["part-salping-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-batch-growth-1",
    type: "root_match",
    prompt: "Which combining form points to swelling?",
    choices: ["edem/o", "chondr/o", "neo-", "sten/o"],
    answer: "edem/o",
    linkedTermIds: ["term-batch-lymphedema"],
    linkedPartIds: ["part-batch-inflammatory-edem-combining"],
  },
  {
    id: "exercise-batch-growth-2",
    type: "infer_meaning",
    prompt: "What does `lymphedema` mean?",
    choices: [
      "swelling caused by trapped lymph fluid",
      "narrowing of a lymph vessel",
      "inflammation of a lymph vessel",
      "bleeding from lymph tissue",
    ],
    answer: "swelling caused by trapped lymph fluid",
    linkedTermIds: ["term-batch-lymphedema"],
    linkedPartIds: ["part-lymph-combining", "part-batch-inflammatory-edem-combining"],
  },
  {
    id: "exercise-batch-growth-3",
    type: "split_term",
    prompt: "Which suffix usually means enlargement?",
    choices: ["-megaly", "-cele", "-itis", "-rrhagia"],
    answer: "-megaly",
    linkedTermIds: ["term-batch-thyromegaly"],
    linkedPartIds: ["part-megaly-suffix"],
  },
  {
    id: "exercise-batch-growth-4",
    type: "infer_meaning",
    prompt: "What does `hypertrophy` mean?",
    choices: [
      "excessive growth of tissue",
      "shrinkage of tissue",
      "change in tissue type",
      "narrowing of tissue",
    ],
    answer: "excessive growth of tissue",
    linkedTermIds: ["term-batch-hypertrophy"],
    linkedPartIds: ["part-hyper-prefix", "part-batch-inflammatory-trophy-suffix"],
  },
  {
    id: "exercise-batch-change-1",
    type: "root_match",
    prompt: "Which prefix means new?",
    choices: ["neo-", "meta-", "a-", "hyper-"],
    answer: "neo-",
    linkedTermIds: ["term-batch-neoplasia"],
    linkedPartIds: ["part-batch-inflammatory-neo-prefix"],
  },
  {
    id: "exercise-batch-change-2",
    type: "infer_meaning",
    prompt: "What does `metaplasia` mean?",
    choices: [
      "change in the type of tissue or cells",
      "too much tissue growth",
      "loss of tissue growth",
      "bleeding from tissue",
    ],
    answer: "change in the type of tissue or cells",
    linkedTermIds: ["term-batch-metaplasia"],
    linkedPartIds: ["part-batch-inflammatory-meta-prefix", "part-plasia-suffix"],
  },
  {
    id: "exercise-batch-change-3",
    type: "root_match",
    prompt: "Which combining form points to cartilage?",
    choices: ["chondr/o", "cervic/o", "phleb/o", "periton/o"],
    answer: "chondr/o",
    linkedTermIds: ["term-batch-chondromalacia"],
    linkedPartIds: ["part-batch-inflammatory-chondr-combining"],
  },
  {
    id: "exercise-batch-change-4",
    type: "infer_meaning",
    prompt: "What does `chondromalacia` mean?",
    choices: [
      "softening of cartilage",
      "hardening of cartilage",
      "bleeding of cartilage",
      "inflammation of cartilage",
    ],
    answer: "softening of cartilage",
    linkedTermIds: ["term-batch-chondromalacia"],
    linkedPartIds: ["part-batch-inflammatory-chondr-combining", "part-malacia-suffix"],
  },
  {
    id: "exercise-batch-narrowing-1",
    type: "root_match",
    prompt: "Which combining form means narrow or tight?",
    choices: ["sten/o", "dilat/o", "hydr/o", "edem/o"],
    answer: "sten/o",
    linkedTermIds: ["term-batch-stenosis", "term-batch-bronchostenosis", "term-batch-tracheostenosis"],
    linkedPartIds: ["part-batch-inflammatory-sten-combining"],
  },
  {
    id: "exercise-batch-narrowing-2",
    type: "infer_meaning",
    prompt: "What does `stenosis` mean?",
    choices: [
      "narrowing of a passage",
      "widening of a passage",
      "bleeding from a passage",
      "swelling of a passage",
    ],
    answer: "narrowing of a passage",
    linkedTermIds: ["term-batch-stenosis"],
    linkedPartIds: ["part-batch-inflammatory-sten-combining", "part-batch-inflammatory-stenosis-suffix"],
  },
  {
    id: "exercise-batch-narrowing-3",
    type: "infer_meaning",
    prompt: "What does `bronchostenosis` mean?",
    choices: [
      "narrowing of a bronchus",
      "widening of a bronchus",
      "bleeding from a bronchus",
      "inflammation of a bronchus",
    ],
    answer: "narrowing of a bronchus",
    linkedTermIds: ["term-batch-bronchostenosis"],
    linkedPartIds: ["part-bronch-combining", "part-batch-inflammatory-sten-combining", "part-batch-inflammatory-stenosis-suffix"],
  },
  {
    id: "exercise-batch-narrowing-4",
    type: "infer_meaning",
    prompt: "What does `vasodilation` mean?",
    choices: [
      "widening of a blood vessel",
      "narrowing of a blood vessel",
      "bleeding from a vessel",
      "swelling of a vessel",
    ],
    answer: "widening of a blood vessel",
    linkedTermIds: ["term-batch-vasodilation"],
    linkedPartIds: ["part-vascul-root", "part-batch-inflammatory-dilat-combining"],
  },
  {
    id: "exercise-batch-flow-1",
    type: "infer_meaning",
    prompt: "What does `bronchiectasis` mean?",
    choices: [
      "widening of a bronchus",
      "narrowing of a bronchus",
      "bleeding from a bronchus",
      "inflammation of a bronchus",
    ],
    answer: "widening of a bronchus",
    linkedTermIds: ["term-batch-bronchiectasis"],
    linkedPartIds: ["part-bronch-combining", "part-batch-inflammatory-ectasis-suffix"],
  },
  {
    id: "exercise-batch-flow-2",
    type: "infer_meaning",
    prompt: "What does `hemorrhage` mean?",
    choices: [
      "bursting forth of blood; bleeding",
      "narrowing of blood",
      "swelling of blood",
      "new blood growth",
    ],
    answer: "bursting forth of blood; bleeding",
    linkedTermIds: ["term-batch-hemorrhage"],
    linkedPartIds: ["part-hem-combining", "part-batch-inflammatory-rrhage-suffix"],
  },
  {
    id: "exercise-batch-flow-3",
    type: "infer_meaning",
    prompt: "What does `menorrhagia` mean?",
    choices: [
      "excessive menstrual bleeding",
      "narrowing of menstrual flow",
      "swelling during menstruation",
      "new menstrual tissue growth",
    ],
    answer: "excessive menstrual bleeding",
    linkedTermIds: ["term-batch-menorrhagia"],
    linkedPartIds: ["part-men-combining", "part-batch-inflammatory-rrhagia-suffix"],
  },
  {
    id: "exercise-batch-flow-4",
    type: "split_term",
    prompt: "Which suffix means hernia or protrusion?",
    choices: ["-cele", "-megaly", "-itis", "-rrhage"],
    answer: "-cele",
    linkedTermIds: [
      "term-batch-cystocele",
      "term-batch-rectocele",
      "term-batch-encephalocele",
      "term-batch-meningocele",
      "term-batch-hydrocele",
    ],
    linkedPartIds: ["part-batch-inflammatory-cele-suffix"],
  },
  {
    id: "exercise-batch-flow-5",
    type: "infer_meaning",
    prompt: "What does `cystocele` mean?",
    choices: [
      "bladder hernia or bulge",
      "bladder bleeding",
      "bladder narrowing",
      "bladder enlargement",
    ],
    answer: "bladder hernia or bulge",
    linkedTermIds: ["term-batch-cystocele"],
    linkedPartIds: ["part-cyst-combining", "part-batch-inflammatory-cele-suffix"],
  },
  {
    id: "exercise-batch-flow-6",
    type: "infer_meaning",
    prompt: "What does `hydrocele` mean?",
    choices: [
      "fluid-filled swelling or sac",
      "air-filled swelling or sac",
      "blood-filled swelling or sac",
      "a narrowed fluid passage",
    ],
    answer: "fluid-filled swelling or sac",
    linkedTermIds: ["term-batch-hydrocele"],
    linkedPartIds: ["part-batch-inflammatory-hydr-combining", "part-batch-inflammatory-cele-suffix"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-batch-inflammatory-roots-1",
    title: "Inflammation Roots I",
    unitId: "unit-1",
    objective: "Let's learn the high-frequency `-itis` pattern with common body roots.",
    whyItMatters: "Inflammation words are everywhere in notes, referrals, and patient instructions.",
    prerequisiteLessonIds: ["lesson-unit1-common-suffixes"],
    introducesPartIds: [
      "part-batch-inflammatory-periton-combining",
      "part-batch-inflammatory-conjunctiv-combining",
      "part-batch-inflammatory-tonsill-combining",
    ],
    introducesTermIds: [
      "term-batch-neuritis",
      "term-batch-appendicitis",
      "term-batch-peritonitis",
      "term-batch-conjunctivitis",
      "term-batch-tonsillitis",
    ],
    reinforcesTermIds: ["term-gastritis", "term-arthritis", "term-dermatitis", "term-hepatitis"],
    exerciseSetIds: [
      "exercise-batch-inflammation-1",
      "exercise-batch-inflammation-2",
      "exercise-batch-inflammation-3",
      "exercise-batch-inflammation-4",
    ],
    estimatedMinutes: 7,
    status: "drafted",
  },
  {
    id: "lesson-batch-inflammatory-roots-2",
    title: "Inflammation Roots II",
    unitId: "unit-1",
    objective: "Let's learn more `-itis` words built from common body roots.",
    whyItMatters: "These terms make anatomy easier to read inside chart language.",
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-1"],
    introducesPartIds: [
      "part-batch-inflammatory-phleb-combining",
      "part-batch-inflammatory-vagin-combining",
      "part-batch-inflammatory-vulv-combining",
      "part-batch-inflammatory-cervic-combining",
      "part-batch-inflammatory-mening-combining",
    ],
    introducesTermIds: [
      "term-batch-phlebitis",
      "term-batch-lymphangitis",
      "term-batch-vaginitis",
      "term-batch-vulvitis",
      "term-batch-cervicitis",
      "term-batch-meningitis",
    ],
    reinforcesTermIds: [
      "term-bronchitis",
      "term-rhinitis",
      "term-otitis",
      "term-lymphadenitis",
      "term-salpingitis",
    ],
    exerciseSetIds: [
      "exercise-batch-inflammation-5",
      "exercise-batch-inflammation-6",
      "exercise-batch-inflammation-7",
      "exercise-batch-inflammation-8",
    ],
    estimatedMinutes: 7,
    status: "drafted",
  },
  {
    id: "lesson-batch-swelling-growth-roots",
    title: "Swelling and Growth",
    unitId: "unit-1",
    objective: "Let's learn swelling and enlargement words that show up in exams and imaging.",
    whyItMatters: "These roots help separate fluid buildup from tissue growth.",
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-2"],
    introducesPartIds: [
      "part-batch-inflammatory-edem-combining",
      "part-batch-inflammatory-trophy-suffix",
      "part-batch-inflammatory-a-prefix",
    ],
    introducesTermIds: [
      "term-batch-lymphedema",
      "term-batch-thyromegaly",
      "term-batch-hypertrophy",
      "term-batch-atrophy",
    ],
    reinforcesTermIds: ["term-edema", "term-cardiomegaly", "term-hepatomegaly", "term-splenomegaly"],
    exerciseSetIds: [
      "exercise-batch-growth-1",
      "exercise-batch-growth-2",
      "exercise-batch-growth-3",
      "exercise-batch-growth-4",
    ],
    estimatedMinutes: 7,
    status: "drafted",
  },
  {
    id: "lesson-batch-tissue-change-roots",
    title: "Tissue Change",
    unitId: "unit-1",
    objective: "Let's learn tissue-change words that describe growth, shift, and softening.",
    whyItMatters: "These patterns show up in pathology, imaging, and problem lists.",
    prerequisiteLessonIds: ["lesson-batch-swelling-growth-roots"],
    introducesPartIds: [
      "part-batch-inflammatory-meta-prefix",
      "part-batch-inflammatory-neo-prefix",
      "part-batch-inflammatory-chondr-combining",
    ],
    introducesTermIds: [
      "term-batch-metaplasia",
      "term-batch-chondromalacia",
      "term-batch-neoplasia",
    ],
    reinforcesTermIds: ["term-dysplasia", "term-hyperplasia", "term-hypoplasia", "term-osteomalacia"],
    exerciseSetIds: [
      "exercise-batch-change-1",
      "exercise-batch-change-2",
      "exercise-batch-change-3",
      "exercise-batch-change-4",
    ],
    estimatedMinutes: 7,
    status: "drafted",
  },
  {
    id: "lesson-batch-narrowing-dilation-roots",
    title: "Narrowing and Dilation",
    unitId: "unit-1",
    objective: "Let's learn narrowing and widening words used in procedures and diagnoses.",
    whyItMatters: "These terms explain passage size, blood flow, and airway caliber.",
    prerequisiteLessonIds: ["lesson-batch-tissue-change-roots"],
    introducesPartIds: [
      "part-batch-inflammatory-sten-combining",
      "part-batch-inflammatory-stenosis-suffix",
      "part-batch-inflammatory-dilat-combining",
      "part-batch-inflammatory-ectasis-suffix",
    ],
    introducesTermIds: [
      "term-batch-stenosis",
      "term-batch-bronchostenosis",
      "term-batch-tracheostenosis",
      "term-batch-vasodilation",
      "term-batch-bronchiectasis",
      "term-batch-hemorrhage",
    ],
    reinforcesTermIds: ["term-bronchitis", "term-rhinorrhea", "term-thrombosis"],
    exerciseSetIds: [
      "exercise-batch-narrowing-1",
      "exercise-batch-narrowing-2",
      "exercise-batch-narrowing-3",
      "exercise-batch-narrowing-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-flow-protrusion-roots",
    title: "Flow and Protrusion",
    unitId: "unit-1",
    objective: "Let's learn protrusion words and the heavier bleeding family.",
    whyItMatters: "These endings are common in discharge notes, problem lists, and imaging reports.",
    prerequisiteLessonIds: ["lesson-batch-narrowing-dilation-roots"],
    introducesPartIds: [
      "part-batch-inflammatory-rrhagia-suffix",
      "part-batch-inflammatory-cele-suffix",
      "part-batch-inflammatory-rect-combining",
      "part-batch-inflammatory-hydr-combining",
    ],
    introducesTermIds: [
      "term-batch-menorrhagia",
      "term-batch-cystocele",
      "term-batch-rectocele",
      "term-batch-encephalocele",
      "term-batch-meningocele",
      "term-batch-hydrocele",
    ],
    reinforcesTermIds: ["term-rhinorrhea", "term-edema", "term-cystitis", "term-lymphadenitis"],
    exerciseSetIds: [
      "exercise-batch-flow-1",
      "exercise-batch-flow-2",
      "exercise-batch-flow-3",
      "exercise-batch-flow-4",
      "exercise-batch-flow-5",
      "exercise-batch-flow-6",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
];
