import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-batch-definflam-prefix-1",
    type: "root_match",
    prompt: "Which prefix means against or opposed to?",
    choices: ["anti-", "eu-", "mal-", "dys-"],
    answer: "anti-",
    linkedTermIds: ["term-batch-antibiotic", "term-batch-antiseptic", "term-batch-antipyretic", "term-batch-antiemetic"],
    linkedPartIds: ["part-batch-definflam-anti-prefix"],
  },
  {
    id: "exercise-batch-definflam-prefix-2",
    type: "infer_meaning",
    prompt: "What does `antibiotic` suggest?",
    choices: [
      "a medicine that fights bacterial infection",
      "a word for normal breathing",
      "a condition of poor nutrition",
      "a disease study term",
    ],
    answer: "a medicine that fights bacterial infection",
    linkedTermIds: ["term-batch-antibiotic"],
    linkedPartIds: ["part-batch-definflam-anti-prefix", "part-batch-definflam-bi-combining", "part-batch-definflam-otic-suffix"],
  },
  {
    id: "exercise-batch-definflam-prefix-3",
    type: "infer_meaning",
    prompt: "What does `antipyretic` suggest?",
    choices: ["fever reducing", "voice difficulty", "blood stopping", "poor absorption"],
    answer: "fever reducing",
    linkedTermIds: ["term-batch-antipyretic"],
    linkedPartIds: ["part-batch-definflam-anti-prefix", "part-batch-definflam-pyret-combining", "part-batch-definflam-ic-suffix"],
  },
  {
    id: "exercise-batch-definflam-prefix-4",
    type: "infer_meaning",
    prompt: "What does `antiemetic` suggest?",
    choices: ["against vomiting", "against fever", "against infection", "normal breathing"],
    answer: "against vomiting",
    linkedTermIds: ["term-batch-antiemetic"],
    linkedPartIds: ["part-batch-definflam-anti-prefix", "part-batch-definflam-emet-combining", "part-batch-definflam-ic-suffix"],
  },
  {
    id: "exercise-batch-definflam-prefix-5",
    type: "infer_meaning",
    prompt: "What does `eupnea` suggest?",
    choices: ["normal breathing", "difficulty swallowing", "poor nutrition", "disease origin"],
    answer: "normal breathing",
    linkedTermIds: ["term-batch-eupnea"],
    linkedPartIds: ["part-batch-definflam-eu-prefix", "part-pnea-suffix"],
  },
  {
    id: "exercise-batch-definflam-prefix-6",
    type: "infer_meaning",
    prompt: "What does `malnutrition` suggest?",
    choices: ["poor nutrition", "normal breathing", "against infection", "stable balance"],
    answer: "poor nutrition",
    linkedTermIds: ["term-batch-malnutrition"],
    linkedPartIds: ["part-batch-definflam-mal-prefix", "part-batch-definflam-nutr-combining", "part-batch-definflam-tion-suffix"],
  },
  {
    id: "exercise-batch-definflam-prefix-7",
    type: "infer_meaning",
    prompt: "What does `malabsorption` suggest?",
    choices: ["poor absorption", "difficulty swallowing", "normal breathing", "blood stopping"],
    answer: "poor absorption",
    linkedTermIds: ["term-batch-malabsorption"],
    linkedPartIds: ["part-batch-definflam-mal-prefix", "part-batch-definflam-absorpt-combining", "part-batch-definflam-tion-suffix"],
  },
  {
    id: "exercise-batch-definflam-dys-1",
    type: "root_match",
    prompt: "Which prefix means difficult or abnormal?",
    choices: ["dys-", "eu-", "anti-", "mal-"],
    answer: "dys-",
    linkedTermIds: ["term-batch-dysphagia", "term-batch-dysphonia", "term-batch-dysphasia", "term-batch-dystonia"],
    linkedPartIds: ["part-dys-prefix"],
  },
  {
    id: "exercise-batch-definflam-dys-2",
    type: "infer_meaning",
    prompt: "What does `dysphagia` suggest?",
    choices: ["difficulty swallowing", "difficulty speaking", "abnormal muscle tone", "poor bile flow"],
    answer: "difficulty swallowing",
    linkedTermIds: ["term-batch-dysphagia"],
    linkedPartIds: ["part-dys-prefix", "part-batch-definflam-phag-combining", "part-batch-definflam-ia-suffix"],
  },
  {
    id: "exercise-batch-definflam-dys-3",
    type: "infer_meaning",
    prompt: "What does `dysphonia` suggest?",
    choices: ["voice difficulty", "speech difficulty", "abnormal muscle tone", "normal breathing"],
    answer: "voice difficulty",
    linkedTermIds: ["term-batch-dysphonia"],
    linkedPartIds: ["part-dys-prefix", "part-batch-definflam-phon-combining", "part-batch-definflam-ia-suffix"],
  },
  {
    id: "exercise-batch-definflam-dys-4",
    type: "infer_meaning",
    prompt: "What does `dysphasia` suggest?",
    choices: ["speech difficulty", "difficulty swallowing", "poor nutrition", "stable balance"],
    answer: "speech difficulty",
    linkedTermIds: ["term-batch-dysphasia"],
    linkedPartIds: ["part-dys-prefix", "part-batch-definflam-phas-combining", "part-batch-definflam-ia-suffix"],
  },
  {
    id: "exercise-batch-definflam-dys-5",
    type: "infer_meaning",
    prompt: "What does `dystonia` suggest?",
    choices: ["abnormal muscle tone", "poor absorption", "normal breathing", "blood stopping"],
    answer: "abnormal muscle tone",
    linkedTermIds: ["term-batch-dystonia"],
    linkedPartIds: ["part-dys-prefix", "part-batch-definflam-ton-combining", "part-batch-definflam-ia-suffix"],
  },
  {
    id: "exercise-batch-definflam-path-1",
    type: "root_match",
    prompt: "Which combining form points to disease or suffering?",
    choices: ["path/o", "hem/o", "chol/e", "homeo-"],
    answer: "path/o",
    linkedTermIds: ["term-batch-pathology", "term-batch-pathogenic", "term-batch-pathogenesis"],
    linkedPartIds: ["part-batch-definflam-path-combining"],
  },
  {
    id: "exercise-batch-definflam-path-2",
    type: "infer_meaning",
    prompt: "What does `pathology` mean?",
    choices: ["study of disease", "causing disease", "blood stopping", "poor absorption"],
    answer: "study of disease",
    linkedTermIds: ["term-batch-pathology"],
    linkedPartIds: ["part-batch-definflam-path-combining", "part-ology-suffix"],
  },
  {
    id: "exercise-batch-definflam-path-3",
    type: "infer_meaning",
    prompt: "What does `pathogenic` mean?",
    choices: ["causing disease", "study of disease", "blood stopping", "stable balance"],
    answer: "causing disease",
    linkedTermIds: ["term-batch-pathogenic"],
    linkedPartIds: ["part-batch-definflam-path-combining", "part-batch-definflam-genic-suffix"],
  },
  {
    id: "exercise-batch-definflam-path-4",
    type: "infer_meaning",
    prompt: "What does `pathogenesis` mean?",
    choices: ["how a disease develops", "how blood stops after injury", "normal breathing", "poor nutrition"],
    answer: "how a disease develops",
    linkedTermIds: ["term-batch-pathogenesis"],
    linkedPartIds: ["part-batch-definflam-path-combining", "part-batch-definflam-genesis-suffix"],
  },
  {
    id: "exercise-batch-definflam-path-5",
    type: "infer_meaning",
    prompt: "What does `hemostasis` mean?",
    choices: ["stopping bleeding", "stable internal balance", "poor bile flow", "normal breathing"],
    answer: "stopping bleeding",
    linkedTermIds: ["term-batch-hemostasis"],
    linkedPartIds: ["part-hem-combining", "part-batch-definflam-stasis-suffix"],
  },
  {
    id: "exercise-batch-definflam-path-6",
    type: "infer_meaning",
    prompt: "What does `homeostasis` mean?",
    choices: ["stable internal balance", "blood stopping", "poor nutrition", "disease origin"],
    answer: "stable internal balance",
    linkedTermIds: ["term-batch-homeostasis"],
    linkedPartIds: ["part-batch-definflam-homeo-prefix", "part-batch-definflam-stasis-suffix"],
  },
  {
    id: "exercise-batch-definflam-path-7",
    type: "infer_meaning",
    prompt: "What does `cholestasis` mean?",
    choices: ["poor bile flow", "stable internal balance", "causing disease", "difficulty swallowing"],
    answer: "poor bile flow",
    linkedTermIds: ["term-batch-cholestasis"],
    linkedPartIds: ["part-chole-combining", "part-batch-definflam-stasis-suffix"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-batch-definflam-prefix-shifts",
    title: "Prefix Shifts",
    unitId: "unit-1",
    objective: "Let's learn the prefix families that change the meaning of common medical words.",
    whyItMatters: "These short shifts show up in medication names, symptoms, and routine chart language.",
    prerequisiteLessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    introducesPartIds: [
      "part-batch-definflam-anti-prefix",
      "part-batch-definflam-eu-prefix",
      "part-batch-definflam-mal-prefix",
      "part-batch-definflam-bi-combining",
      "part-batch-definflam-pyret-combining",
      "part-batch-definflam-emet-combining",
      "part-batch-definflam-septic-combining",
      "part-batch-definflam-nutr-combining",
      "part-batch-definflam-absorpt-combining",
      "part-batch-definflam-ic-suffix",
      "part-batch-definflam-otic-suffix",
      "part-batch-definflam-tion-suffix",
      "part-pnea-suffix",
    ],
    introducesTermIds: [
      "term-batch-antibiotic",
      "term-batch-antiseptic",
      "term-batch-antipyretic",
      "term-batch-antiemetic",
      "term-batch-eupnea",
      "term-batch-malnutrition",
      "term-batch-malabsorption",
    ],
    reinforcesTermIds: [],
    exerciseSetIds: [
      "exercise-batch-definflam-prefix-1",
      "exercise-batch-definflam-prefix-2",
      "exercise-batch-definflam-prefix-3",
      "exercise-batch-definflam-prefix-4",
      "exercise-batch-definflam-prefix-5",
      "exercise-batch-definflam-prefix-6",
      "exercise-batch-definflam-prefix-7",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-definflam-dysfunction-words",
    title: "Dys- Function Words",
    unitId: "unit-1",
    objective: "Let's learn the dys- families used for swallowing, speech, and movement problems.",
    whyItMatters: "These words appear constantly in symptom notes and neurologic descriptions.",
    prerequisiteLessonIds: ["lesson-batch-definflam-prefix-shifts"],
    introducesPartIds: [
      "part-dys-prefix",
      "part-batch-definflam-phag-combining",
      "part-batch-definflam-phon-combining",
      "part-batch-definflam-phas-combining",
      "part-batch-definflam-ton-combining",
      "part-batch-definflam-ia-suffix",
    ],
    introducesTermIds: [
      "term-batch-dysphagia",
      "term-batch-dysphonia",
      "term-batch-dysphasia",
      "term-batch-dystonia",
    ],
    reinforcesTermIds: ["term-batch-eupnea"],
    exerciseSetIds: [
      "exercise-batch-definflam-dys-1",
      "exercise-batch-definflam-dys-2",
      "exercise-batch-definflam-dys-3",
      "exercise-batch-definflam-dys-4",
      "exercise-batch-definflam-dys-5",
    ],
    estimatedMinutes: 7,
    status: "drafted",
  },
  {
    id: "lesson-batch-definflam-path-and-stasis",
    title: "Path and Stasis",
    unitId: "unit-1",
    objective: "Let's learn the path- and stasis families that describe disease and balance.",
    whyItMatters: "These words show up in pathology, lab results, and status notes.",
    prerequisiteLessonIds: ["lesson-batch-definflam-dysfunction-words"],
    introducesPartIds: [
      "part-batch-definflam-path-combining",
      "part-batch-definflam-genic-suffix",
      "part-batch-definflam-genesis-suffix",
      "part-batch-definflam-stasis-suffix",
      "part-hem-combining",
      "part-batch-definflam-homeo-prefix",
      "part-chole-combining",
      "part-ology-suffix",
    ],
    introducesTermIds: [
      "term-batch-pathology",
      "term-batch-pathogenic",
      "term-batch-pathogenesis",
      "term-batch-hemostasis",
      "term-batch-homeostasis",
      "term-batch-cholestasis",
    ],
    reinforcesTermIds: ["term-batch-antibiotic", "term-batch-antiseptic", "term-batch-eupnea"],
    exerciseSetIds: [
      "exercise-batch-definflam-path-1",
      "exercise-batch-definflam-path-2",
      "exercise-batch-definflam-path-3",
      "exercise-batch-definflam-path-4",
      "exercise-batch-definflam-path-5",
      "exercise-batch-definflam-path-6",
      "exercise-batch-definflam-path-7",
    ],
    estimatedMinutes: 9,
    status: "drafted",
  },
];
