import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-root-bloodcounts-white-1",
    type: "root_match",
    prompt: "Which suffix means a low count or deficiency?",
    choices: ["-penia", "-osis", "-gram", "-cyte"],
    answer: "-penia",
    linkedTermIds: ["term-leukopenia", "term-cytopenia", "term-pancytopenia"],
    linkedPartIds: ["part-penia-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-white-2",
    type: "infer_meaning",
    prompt: "What does `leukopenia` mean?",
    choices: ["low white blood cell count", "high white blood cell count", "blood record", "blood breakdown"],
    answer: "low white blood cell count",
    linkedTermIds: ["term-leukopenia"],
    linkedPartIds: ["part-leuk-combining", "part-penia-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-white-3",
    type: "infer_meaning",
    prompt: "What should a learner do with `leukemia`?",
    choices: [
      "treat it as a recognition-first term",
      "split it into a perfect root-plus-suffix formula",
      "read it as a red cell term",
      "read it as a platelet count term",
    ],
    answer: "treat it as a recognition-first term",
    linkedTermIds: ["term-leukemia"],
    linkedPartIds: [],
  },
  {
    id: "exercise-root-bloodcounts-white-4",
    type: "infer_meaning",
    prompt: "What does `leukocytosis` suggest?",
    choices: ["high white blood cell count", "low white blood cell count", "blood record", "blood breakdown"],
    answer: "high white blood cell count",
    linkedTermIds: ["term-leukocytosis", "term-leukopenia"],
    linkedPartIds: ["part-leuk-combining", "part-osis-suffix", "part-penia-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-platelet-1",
    type: "root_match",
    prompt: "Which combining form points to clot or platelet?",
    choices: ["thromb/o", "erythr/o", "leuk/o", "hem/o"],
    answer: "thromb/o",
    linkedTermIds: ["term-thrombocyte", "term-thrombocytopenia", "term-thrombocytosis"],
    linkedPartIds: ["part-thromb-combining"],
  },
  {
    id: "exercise-root-bloodcounts-platelet-2",
    type: "infer_meaning",
    prompt: "What does `thrombocyte` mean?",
    choices: ["platelet", "red blood cell", "white blood cell", "blood study"],
    answer: "platelet",
    linkedTermIds: ["term-thrombocyte"],
    linkedPartIds: ["part-thromb-combining", "part-cyte-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-platelet-3",
    type: "infer_meaning",
    prompt: "What does `thrombocytopenia` mean?",
    choices: ["low platelet count", "high platelet count", "blood cell study", "blood breakdown"],
    answer: "low platelet count",
    linkedTermIds: ["term-thrombocytopenia"],
    linkedPartIds: ["part-thromb-combining", "part-cyt-combining", "part-penia-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-platelet-4",
    type: "infer_meaning",
    prompt: "What does `thrombocytosis` mean?",
    choices: ["high platelet count", "low platelet count", "cell study", "blood condition"],
    answer: "high platelet count",
    linkedTermIds: ["term-thrombocytosis"],
    linkedPartIds: ["part-thromb-combining", "part-cyt-combining", "part-osis-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-red-1",
    type: "root_match",
    prompt: "Which combining form points to red?",
    choices: ["erythr/o", "leuk/o", "thromb/o", "cyt/o"],
    answer: "erythr/o",
    linkedTermIds: ["term-erythrocyte", "term-erythrocytosis", "term-polycythemia"],
    linkedPartIds: ["part-erythr-combining"],
  },
  {
    id: "exercise-root-bloodcounts-red-2",
    type: "infer_meaning",
    prompt: "What does `erythrocytosis` mean?",
    choices: ["high red blood cell count", "low red blood cell count", "cell study", "blood breakdown"],
    answer: "high red blood cell count",
    linkedTermIds: ["term-erythrocytosis"],
    linkedPartIds: ["part-erythr-combining", "part-cyt-combining", "part-osis-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-red-3",
    type: "infer_meaning",
    prompt: "What does `polycythemia` mean?",
    choices: ["too many blood cells", "too few blood cells", "blood study", "blood breakdown"],
    answer: "too many blood cells",
    linkedTermIds: ["term-polycythemia"],
    linkedPartIds: ["part-poly-prefix", "part-cyt-combining", "part-emia-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-red-4",
    type: "infer_meaning",
    prompt: "What does `anemia` mean in plain English?",
    choices: [
      "too little healthy blood",
      "too many red blood cells",
      "blood cell study",
      "breakdown of blood cells",
    ],
    answer: "too little healthy blood",
    linkedTermIds: ["term-anemia", "term-polycythemia"],
    linkedPartIds: ["part-emia-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-count-1",
    type: "root_match",
    prompt: "Which combining form means cell?",
    choices: ["cyt/o", "hemat/o", "erythr/o", "thromb/o"],
    answer: "cyt/o",
    linkedTermIds: ["term-cytology", "term-cytopenia", "term-pancytopenia"],
    linkedPartIds: ["part-cyt-combining"],
  },
  {
    id: "exercise-root-bloodcounts-count-2",
    type: "infer_meaning",
    prompt: "What does `cytology` mean?",
    choices: ["the study of cells", "low cell count", "blood study", "record of blood"],
    answer: "the study of cells",
    linkedTermIds: ["term-cytology"],
    linkedPartIds: ["part-cyt-combining", "part-ology-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-count-3",
    type: "infer_meaning",
    prompt: "What does `cytopenia` mean?",
    choices: ["low cell count", "high cell count", "cell study", "blood breakdown"],
    answer: "low cell count",
    linkedTermIds: ["term-cytopenia"],
    linkedPartIds: ["part-cyt-combining", "part-penia-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-count-4",
    type: "infer_meaning",
    prompt: "What does `pancytopenia` mean?",
    choices: [
      "low counts of all blood cell types",
      "high counts of all blood cell types",
      "blood record",
      "blood study",
    ],
    answer: "low counts of all blood cell types",
    linkedTermIds: ["term-pancytopenia"],
    linkedPartIds: ["part-panc-prefix", "part-cyt-combining", "part-penia-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-count-5",
    type: "infer_meaning",
    prompt: "What does `hematology` mean?",
    choices: ["the study of blood", "the study of cells", "blood breakdown", "a blood count record"],
    answer: "the study of blood",
    linkedTermIds: ["term-hematology"],
    linkedPartIds: ["part-hemat-combining", "part-ology-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-count-6",
    type: "infer_meaning",
    prompt: "What does `hemogram` mean?",
    choices: ["a blood count record", "the study of blood", "low blood cell count", "blood cell breakdown"],
    answer: "a blood count record",
    linkedTermIds: ["term-hemogram"],
    linkedPartIds: ["part-hem-combining", "part-gram-suffix"],
  },
  {
    id: "exercise-root-bloodcounts-count-7",
    type: "infer_meaning",
    prompt: "What does `hemolysis` mean?",
    choices: ["blood cell breakdown", "blood study", "low blood count", "too many red cells"],
    answer: "blood cell breakdown",
    linkedTermIds: ["term-hemolysis"],
    linkedPartIds: ["part-hem-combining", "part-lysis-suffix"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-root-bloodcounts-white-cell-family",
    title: "White Cell Family",
    unitId: "unit-1",
    objective: "Let's learn the white-cell family used for high and low count language.",
    whyItMatters: "These contrasts show up often in labs, infection workups, and chart notes.",
    prerequisiteLessonIds: ["lesson-unit1-vessel-root-family"],
    introducesPartIds: ["part-penia-suffix"],
    introducesTermIds: ["term-leukopenia", "term-leukemia"],
    reinforcesTermIds: ["term-leukocyte", "term-leukocytosis"],
    exerciseSetIds: [
      "exercise-root-bloodcounts-white-1",
      "exercise-root-bloodcounts-white-2",
      "exercise-root-bloodcounts-white-3",
      "exercise-root-bloodcounts-white-4",
    ],
    estimatedMinutes: 6,
    status: "drafted",
  },
  {
    id: "lesson-root-bloodcounts-platelet-family",
    title: "Platelet Family",
    unitId: "unit-1",
    objective: "Let's learn the platelet family used for clotting and count language.",
    whyItMatters: "Platelet terms are common in labs, bleeding notes, and clotting discussions.",
    prerequisiteLessonIds: ["lesson-root-bloodcounts-white-cell-family"],
    introducesPartIds: ["part-cyte-suffix"],
    introducesTermIds: ["term-thrombocyte", "term-thrombocytopenia", "term-thrombocytosis"],
    reinforcesTermIds: ["term-thrombosis", "term-leukopenia"],
    exerciseSetIds: [
      "exercise-root-bloodcounts-platelet-1",
      "exercise-root-bloodcounts-platelet-2",
      "exercise-root-bloodcounts-platelet-3",
      "exercise-root-bloodcounts-platelet-4",
    ],
    estimatedMinutes: 6,
    status: "drafted",
  },
  {
    id: "lesson-root-bloodcounts-red-cell-family",
    title: "Red Cell Family",
    unitId: "unit-1",
    objective: "Let's learn the red-cell family and the words that describe too many or too few red cells.",
    whyItMatters: "Red-cell words are common in labs, anemia workups, and oxygen-carrying discussions.",
    prerequisiteLessonIds: ["lesson-root-bloodcounts-platelet-family"],
    introducesPartIds: [],
    introducesTermIds: ["term-erythrocytosis", "term-polycythemia"],
    reinforcesTermIds: ["term-erythrocyte", "term-anemia"],
    exerciseSetIds: [
      "exercise-root-bloodcounts-red-1",
      "exercise-root-bloodcounts-red-2",
      "exercise-root-bloodcounts-red-3",
      "exercise-root-bloodcounts-red-4",
    ],
    estimatedMinutes: 6,
    status: "drafted",
  },
  {
    id: "lesson-root-bloodcounts-count-and-deficiency",
    title: "Count and Deficiency",
    unitId: "unit-1",
    objective: "Let's learn the cell-count and blood-record words that tie these families together.",
    whyItMatters: "These terms show up whenever labs, cell counts, and low-count states are discussed together.",
    prerequisiteLessonIds: ["lesson-root-bloodcounts-red-cell-family"],
    introducesPartIds: ["part-panc-prefix", "part-hem-combining", "part-lysis-suffix"],
    introducesTermIds: ["term-cytology", "term-cytopenia", "term-pancytopenia", "term-hemogram", "term-hemolysis"],
    reinforcesTermIds: ["term-hematology", "term-leukopenia", "term-thrombocytopenia", "term-polycythemia"],
    exerciseSetIds: [
      "exercise-root-bloodcounts-count-1",
      "exercise-root-bloodcounts-count-2",
      "exercise-root-bloodcounts-count-3",
      "exercise-root-bloodcounts-count-4",
      "exercise-root-bloodcounts-count-5",
      "exercise-root-bloodcounts-count-6",
      "exercise-root-bloodcounts-count-7",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
];
