import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-batch-fluid-urine-1",
    type: "root_match",
    prompt: "Which suffix points to urine or urination?",
    choices: ["-uria", "-rrhea", "-emesis", "-chezia"],
    answer: "-uria",
    explanation: "`-uria` is the core urine-family ending.",
    linkedTermIds: [
      "term-batch-fluid-anuria",
      "term-batch-fluid-nocturia",
      "term-batch-fluid-pyuria",
      "term-batch-fluid-glycosuria",
    ],
    linkedPartIds: ["part-uria-suffix"],
  },
  {
    id: "exercise-batch-fluid-urine-2",
    type: "infer_meaning",
    prompt: "What does `anuria` mean?",
    choices: [
      "no urine output",
      "too much urine output",
      "blood in the urine",
      "painful urination",
    ],
    answer: "no urine output",
    explanation: "`a-` means without and `-uria` keeps the meaning on urine output.",
    linkedTermIds: ["term-batch-fluid-anuria"],
    linkedPartIds: ["part-batch-inflammatory-a-prefix", "part-uria-suffix"],
  },
  {
    id: "exercise-batch-fluid-urine-3",
    type: "infer_meaning",
    prompt: "What does `pyuria` mean?",
    choices: [
      "pus in the urine",
      "ketones in the urine",
      "bacteria in the urine",
      "nighttime urination",
    ],
    answer: "pus in the urine",
    explanation: "`py/o` points to pus and `-uria` points to urine.",
    linkedTermIds: ["term-batch-fluid-pyuria"],
    linkedPartIds: ["part-batch-fluid-py-combining", "part-uria-suffix"],
  },
  {
    id: "exercise-batch-fluid-urine-4",
    type: "infer_meaning",
    prompt: "Which word means waking at night to urinate?",
    choices: ["nocturia", "glycosuria", "bacteriuria", "ketonuria"],
    answer: "nocturia",
    explanation: "`noct/o` points to night, which makes the pattern easier to spot.",
    linkedTermIds: ["term-batch-fluid-nocturia"],
    linkedPartIds: ["part-batch-fluid-noct-combining", "part-uria-suffix"],
  },
  {
    id: "exercise-batch-fluid-blood-1",
    type: "root_match",
    prompt: "Which suffix means vomiting?",
    choices: ["-emesis", "-ptysis", "-rrhea", "-chezia"],
    answer: "-emesis",
    explanation: "`-emesis` is the vomiting family ending.",
    linkedTermIds: ["term-batch-fluid-hematemesis", "term-batch-fluid-hyperemesis"],
    linkedPartIds: ["part-batch-fluid-emesis-suffix"],
  },
  {
    id: "exercise-batch-fluid-blood-2",
    type: "infer_meaning",
    prompt: "What does `hematemesis` mean?",
    choices: [
      "vomiting blood",
      "coughing up blood",
      "blood in stool",
      "nosebleed",
    ],
    answer: "vomiting blood",
    explanation: "`hemat/o` gives blood and `-emesis` gives vomiting.",
    linkedTermIds: ["term-batch-fluid-hematemesis"],
    linkedPartIds: ["part-hemat-combining", "part-batch-fluid-emesis-suffix"],
  },
  {
    id: "exercise-batch-fluid-blood-3",
    type: "infer_meaning",
    prompt: "What does `hemoptysis` mean?",
    choices: [
      "coughing up blood",
      "vomiting blood",
      "blood in stool",
      "ear discharge",
    ],
    answer: "coughing up blood",
    explanation: "`-ptysis` keeps the meaning on spitting or coughing something out.",
    linkedTermIds: ["term-batch-fluid-hemoptysis"],
    linkedPartIds: ["part-hem-combining", "part-batch-fluid-ptysis-suffix"],
  },
  {
    id: "exercise-batch-fluid-blood-4",
    type: "infer_meaning",
    prompt: "Which term is a recognition-first word for a nosebleed?",
    choices: ["epistaxis", "melena", "hematochezia", "hyperemesis"],
    answer: "epistaxis",
    explanation: "This is a common nosebleed term that learners should recognize directly.",
    linkedTermIds: ["term-batch-fluid-epistaxis"],
    linkedPartIds: [],
  },
  {
    id: "exercise-batch-fluid-blood-5",
    type: "infer_meaning",
    prompt: "What does `hematochezia` mean?",
    choices: [
      "passing bright blood in stool",
      "black tarry stool from digested blood",
      "vomiting blood",
      "coughing up blood",
    ],
    answer: "passing bright blood in stool",
    explanation: "`hemat/o` gives blood and `-chezia` points to stool passage.",
    linkedTermIds: ["term-batch-fluid-hematochezia", "term-batch-fluid-melena"],
    linkedPartIds: ["part-hemat-combining", "part-batch-fluid-chezia-suffix"],
  },
  {
    id: "exercise-batch-fluid-discharge-1",
    type: "root_match",
    prompt: "Which suffix points to flow or discharge?",
    choices: ["-rrhea", "-uria", "-chezia", "-ptysis"],
    answer: "-rrhea",
    explanation: "`-rrhea` is the high-yield discharge family ending.",
    linkedTermIds: [
      "term-batch-fluid-otorrhea",
      "term-batch-fluid-diarrhea",
      "term-batch-fluid-galactorrhea",
      "term-batch-fluid-steatorrhea",
    ],
    linkedPartIds: ["part-rrhea-suffix"],
  },
  {
    id: "exercise-batch-fluid-discharge-2",
    type: "infer_meaning",
    prompt: "What does `otorrhea` mean?",
    choices: ["ear discharge", "nose discharge", "urine discharge", "milk discharge"],
    answer: "ear discharge",
    explanation: "`ot/o` points to ear and `-rrhea` points to discharge.",
    linkedTermIds: ["term-batch-fluid-otorrhea"],
    linkedPartIds: ["part-ot-combining", "part-rrhea-suffix"],
  },
  {
    id: "exercise-batch-fluid-discharge-3",
    type: "infer_meaning",
    prompt: "What does `galactorrhea` mean?",
    choices: [
      "milk discharge",
      "fat in the stool",
      "ear discharge",
      "loose stool flowing through",
    ],
    answer: "milk discharge",
    explanation: "`galact/o` points to milk and `-rrhea` keeps the meaning on discharge.",
    linkedTermIds: ["term-batch-fluid-galactorrhea"],
    linkedPartIds: ["part-batch-fluid-galact-combining", "part-rrhea-suffix"],
  },
  {
    id: "exercise-batch-fluid-discharge-4",
    type: "infer_meaning",
    prompt: "Which term points to fatty stool from poor fat absorption?",
    choices: ["steatorrhea", "diarrhea", "galactorrhea", "otorrhea"],
    answer: "steatorrhea",
    explanation: "`steat/o` points to fat and `-rrhea` points to discharge or flow.",
    linkedTermIds: ["term-batch-fluid-steatorrhea"],
    linkedPartIds: ["part-batch-fluid-steat-combining", "part-rrhea-suffix"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-batch-fluid-urine-output",
    title: "Urine Output and Content",
    unitId: "unit-1",
    objective: "Let's learn the urine-family endings that mark amount, timing, and what is present in the sample.",
    whyItMatters: "These words appear constantly in labs, triage notes, and diabetes or infection workups.",
    prerequisiteLessonIds: ["lesson-batch-flow-protrusion-roots"],
    introducesPartIds: [
      "part-batch-fluid-noct-combining",
      "part-batch-fluid-py-combining",
      "part-batch-fluid-bacteri-combining",
      "part-batch-fluid-keton-combining",
    ],
    introducesTermIds: [
      "term-batch-fluid-anuria",
      "term-batch-fluid-nocturia",
      "term-batch-fluid-pyuria",
      "term-batch-fluid-glycosuria",
      "term-batch-fluid-bacteriuria",
      "term-batch-fluid-ketonuria",
    ],
    reinforcesTermIds: [
      "term-dysuria",
      "term-polyuria",
      "term-oliguria",
      "term-hematuria",
      "term-proteinuria",
    ],
    exerciseSetIds: [
      "exercise-batch-fluid-urine-1",
      "exercise-batch-fluid-urine-2",
      "exercise-batch-fluid-urine-3",
      "exercise-batch-fluid-urine-4",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-fluid-blood-out",
    title: "Blood Coming Out",
    unitId: "unit-1",
    objective: "Let's learn the common words for blood coming out through vomiting, coughing, stool, or a nosebleed.",
    whyItMatters: "These are high-signal chart terms that quickly tell you where blood is appearing.",
    prerequisiteLessonIds: ["lesson-batch-fluid-urine-output"],
    introducesPartIds: [
      "part-batch-fluid-emesis-suffix",
      "part-batch-fluid-ptysis-suffix",
      "part-batch-fluid-chezia-suffix",
    ],
    introducesTermIds: [
      "term-batch-fluid-hematemesis",
      "term-batch-fluid-hemoptysis",
      "term-batch-fluid-hyperemesis",
      "term-batch-fluid-epistaxis",
      "term-batch-fluid-melena",
      "term-batch-fluid-hematochezia",
    ],
    reinforcesTermIds: ["term-batch-hemorrhage", "term-batch-menorrhagia"],
    exerciseSetIds: [
      "exercise-batch-fluid-blood-1",
      "exercise-batch-fluid-blood-2",
      "exercise-batch-fluid-blood-3",
      "exercise-batch-fluid-blood-4",
      "exercise-batch-fluid-blood-5",
    ],
    estimatedMinutes: 8,
    status: "drafted",
  },
  {
    id: "lesson-batch-fluid-discharge-flow",
    title: "Discharge and Flow",
    unitId: "unit-1",
    objective: "Let's learn the discharge-family words that show what is flowing out and from where.",
    whyItMatters: "This one ending explains a large share of common ENT, GI, and reproductive vocabulary.",
    prerequisiteLessonIds: ["lesson-batch-fluid-blood-out"],
    introducesPartIds: [
      "part-batch-fluid-galact-combining",
      "part-batch-fluid-steat-combining",
      "part-batch-fluid-dia-prefix",
    ],
    introducesTermIds: [
      "term-batch-fluid-otorrhea",
      "term-batch-fluid-diarrhea",
      "term-batch-fluid-galactorrhea",
      "term-batch-fluid-steatorrhea",
    ],
    reinforcesTermIds: [
      "term-rhinorrhea",
      "term-dysmenorrhea",
      "term-amenorrhea",
    ],
    exerciseSetIds: [
      "exercise-batch-fluid-discharge-1",
      "exercise-batch-fluid-discharge-2",
      "exercise-batch-fluid-discharge-3",
      "exercise-batch-fluid-discharge-4",
    ],
    estimatedMinutes: 7,
    status: "drafted",
  },
];
