import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-word-parts-1",
    type: "root_match",
    prompt: "Which word part points to the heart?",
    choices: ["cardi", "gastr", "neur", "-itis"],
    answer: "cardi",
    explanation: "`cardi` points to the heart in words like `cardiology` and `cardiac`.",
    linkedTermIds: ["term-cardiology"],
    linkedPartIds: ["part-cardi-root"],
  },
  {
    id: "exercise-word-parts-2",
    type: "infer_meaning",
    prompt: "If `neur` means nerve and `-logy` means study of, what does `neurology` suggest?",
    choices: [
      "study of the nervous system",
      "inflammation of nerves",
      "pain in the head",
      "recording of muscles"
    ],
    answer: "study of the nervous system",
    explanation: "The parts point to a field of study centered on nerves and the nervous system.",
    linkedTermIds: ["term-neurology"],
    linkedPartIds: ["part-neur-root", "part-ology-suffix"],
  },
  {
    id: "exercise-combining-1",
    type: "split_term",
    prompt: "Why does `oste/o` include the `o`?",
    choices: [
      "It helps the word join smoothly to another part",
      "It marks a plural ending",
      "It means above normal",
      "It turns the root into a suffix"
    ],
    answer: "It helps the word join smoothly to another part",
    explanation: "The combining vowel keeps many medical terms pronounceable when parts are joined.",
    linkedTermIds: [],
    linkedPartIds: ["part-osteo-combining"],
  },
  {
    id: "exercise-combining-2",
    type: "cloze",
    prompt: "Complete the rule: a combining vowel usually makes a long medical term easier to ___.",
    choices: ["pronounce", "diagnose", "memorize", "prescribe"],
    answer: "pronounce",
    explanation: "Combining vowels primarily help the parts connect and sound smoother.",
    linkedTermIds: [],
    linkedPartIds: ["part-osteo-combining"],
  },
  {
    id: "exercise-plurals-1",
    type: "infer_meaning",
    prompt: "Which form names more than one vertebra?",
    choices: ["vertebra", "vertebrae", "diagnosis", "bacterium"],
    answer: "vertebrae",
    explanation: "`vertebrae` is the plural form, while `vertebra` refers to one spinal bone.",
    linkedTermIds: ["term-vertebra", "term-vertebrae"],
    linkedPartIds: [],
  },
  {
    id: "exercise-plurals-2",
    type: "root_match",
    prompt: "Which singular and plural pair is correct?",
    choices: [
      "diagnosis / diagnoses",
      "diagnosis / diagnosis",
      "bacterium / bacteriums",
      "vertebrae / vertebra"
    ],
    answer: "diagnosis / diagnoses",
    explanation: "Several medical terms keep classical plural endings such as `-is` to `-es`.",
    linkedTermIds: ["term-diagnosis", "term-diagnoses"],
    linkedPartIds: [],
  },
  {
    id: "exercise-pronunciation-1",
    type: "split_term",
    prompt: "In `cardiology`, which syllable usually carries the main stress?",
    choices: ["OL", "KAR", "jee", "dee"],
    answer: "OL",
    explanation: "Many longer medical terms place the strongest stress close to the end of the word.",
    linkedTermIds: ["term-cardiology"],
    linkedPartIds: [],
  },
  {
    id: "exercise-pronunciation-2",
    type: "root_match",
    prompt: "Which ending is usually pronounced like `EYE-tis`?",
    choices: ["-itis", "-logy", "-gram", "-scopy"],
    answer: "-itis",
    explanation: "The inflammation suffix `-itis` is commonly pronounced `EYE-tis`.",
    linkedTermIds: ["term-gastritis"],
    linkedPartIds: ["part-itis-suffix"],
  },
  {
    id: "exercise-suffixes-1",
    type: "infer_meaning",
    prompt: "If `gastr` means stomach and `-itis` means inflammation, what is `gastritis`?",
    choices: [
      "inflammation of the stomach",
      "study of the stomach",
      "stomach surgery",
      "pain in the stomach"
    ],
    answer: "inflammation of the stomach",
    explanation: "This is a straightforward root-plus-suffix combination.",
    linkedTermIds: ["term-gastritis"],
    linkedPartIds: ["part-gastr-root", "part-itis-suffix"],
  },
  {
    id: "exercise-body-roots-1",
    type: "infer_meaning",
    prompt: "If `derm/o` means skin and `-itis` means inflammation, what does `dermatitis` mean?",
    choices: [
      "inflammation of the skin",
      "study of the skin",
      "pain in the skin",
      "removal of the skin"
    ],
    answer: "inflammation of the skin",
    explanation: "The root and suffix point directly to inflammation in the skin.",
    linkedTermIds: ["term-dermatitis"],
    linkedPartIds: ["part-derm-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-body-roots-2",
    type: "root_match",
    prompt: "Which combining form points to the kidney?",
    choices: ["nephr/o", "hepat/o", "hemat/o", "arthr/o"],
    answer: "nephr/o",
    explanation: "`nephr/o` points to the kidney in words like `nephrology`.",
    linkedTermIds: ["term-nephrology"],
    linkedPartIds: ["part-nephr-combining"],
  },
  {
    id: "exercise-prefixes-1",
    type: "infer_meaning",
    prompt: "Which prefix points to a value above normal?",
    choices: ["hyper-", "hypo-", "-itis", "neur"],
    answer: "hyper-",
    explanation: "`hyper-` often signals something higher or greater than normal.",
    linkedTermIds: ["term-hypertension"],
    linkedPartIds: ["part-hyper-prefix"],
  },
  {
    id: "exercise-rate-prefixes-1",
    type: "root_match",
    prompt: "Which prefix suggests a rate that is too fast?",
    choices: ["tachy-", "brady-", "hypo-", "hyper-"],
    answer: "tachy-",
    explanation: "`tachy-` points to speed or a fast rate.",
    linkedTermIds: ["term-tachycardia"],
    linkedPartIds: ["part-tachy-prefix"],
  },
  {
    id: "exercise-rate-prefixes-2",
    type: "infer_meaning",
    prompt: "What does `bradycardia` suggest?",
    choices: [
      "a heart rate that is too slow",
      "a heart rate that is too fast",
      "inflammation of the heart",
      "study of the heart"
    ],
    answer: "a heart rate that is too slow",
    explanation: "`brady-` points to slow, and `cardi` points to the heart.",
    linkedTermIds: ["term-bradycardia"],
    linkedPartIds: ["part-brady-prefix", "part-cardi-root"],
  },
  {
    id: "exercise-procedures-1",
    type: "infer_meaning",
    prompt: "What does `appendectomy` suggest?",
    choices: [
      "surgical removal of the appendix",
      "inflammation of the appendix",
      "viewing the appendix with a scope",
      "record of the appendix"
    ],
    answer: "surgical removal of the appendix",
    explanation: "`appendic/o` points to the appendix and `-ectomy` means surgical removal.",
    linkedTermIds: ["term-appendectomy"],
    linkedPartIds: ["part-appendic-combining", "part-ectomy-suffix"],
  },
  {
    id: "exercise-procedures-2",
    type: "root_match",
    prompt: "Which suffix signals viewing with a scope?",
    choices: ["-scopy", "-otomy", "-ectomy", "-gram"],
    answer: "-scopy",
    explanation: "`-scopy` points to a visual examination with a scope.",
    linkedTermIds: ["term-colonoscopy"],
    linkedPartIds: ["part-scopy-suffix"],
  },
  {
    id: "exercise-cardio-1",
    type: "infer_meaning",
    prompt: "If `angi/o` means vessel and `-gram` means record or image, what is an `angiogram`?",
    choices: [
      "a vessel image or record",
      "inflammation of a vessel",
      "surgical removal of a vessel",
      "study of a vessel"
    ],
    answer: "a vessel image or record",
    explanation: "The combining form and suffix together point to an imaging record of vessels.",
    linkedTermIds: ["term-angiogram"],
    linkedPartIds: ["part-angi-combining", "part-gram-suffix"],
  },
  {
    id: "exercise-cardio-2",
    type: "infer_meaning",
    prompt: "What does `arteritis` suggest?",
    choices: [
      "inflammation of an artery",
      "study of an artery",
      "image of an artery",
      "slow artery flow"
    ],
    answer: "inflammation of an artery",
    explanation: "`arteri/o` points to an artery and `-itis` points to inflammation.",
    linkedTermIds: ["term-arteritis"],
    linkedPartIds: ["part-arteri-combining", "part-itis-suffix"],
  }
];

export const lessons: Lesson[] = [
  {
    id: "lesson-unit0-word-parts",
    title: "Word Parts That Carry Meaning",
    unitId: "unit-0",
    objective: "Identify roots and suffixes that make common terms decodable.",
    whyItMatters: "A small set of roots and suffixes unlocks much of basic medical language.",
    prerequisiteLessonIds: [],
    introducesPartIds: ["part-cardi-root", "part-gastr-root", "part-neur-root", "part-ology-suffix"],
    introducesTermIds: ["term-cardiology", "term-neurology"],
    reinforcesTermIds: [],
    exerciseSetIds: ["exercise-word-parts-1", "exercise-word-parts-2"],
    estimatedMinutes: 6,
    status: "shipped",
  },
  {
    id: "lesson-unit0-combining-vowels",
    title: "Combining Vowels and Smooth Joins",
    unitId: "unit-0",
    objective: "Explain why many medical terms use connecting vowels.",
    whyItMatters: "Learners decode faster when they understand why forms like `oste/o` appear.",
    prerequisiteLessonIds: ["lesson-unit0-word-parts"],
    introducesPartIds: ["part-osteo-combining"],
    introducesTermIds: [],
    reinforcesTermIds: ["term-cardiology", "term-neurology"],
    exerciseSetIds: ["exercise-combining-1", "exercise-combining-2"],
    estimatedMinutes: 5,
    status: "shipped",
  },
  {
    id: "lesson-unit0-plural-patterns",
    title: "Plural Patterns You Will Keep Seeing",
    unitId: "unit-0",
    objective: "Recognize high-frequency singular and plural shifts in medical language.",
    whyItMatters: "Medical writing often keeps older plural endings that can confuse new learners.",
    prerequisiteLessonIds: ["lesson-unit0-word-parts"],
    introducesPartIds: [],
    introducesTermIds: [
      "term-diagnosis",
      "term-diagnoses",
      "term-vertebra",
      "term-vertebrae",
      "term-bacterium",
      "term-bacteria"
    ],
    reinforcesTermIds: [],
    exerciseSetIds: ["exercise-plurals-1", "exercise-plurals-2"],
    estimatedMinutes: 6,
    status: "shipped",
  },
  {
    id: "lesson-unit0-pronunciation-basics",
    title: "Pronunciation Patterns Worth Recognizing",
    unitId: "unit-0",
    objective: "Notice stress and common endings so familiar terms are easier to hear.",
    whyItMatters: "Recognition improves when learners can hear the term shape as well as read it.",
    prerequisiteLessonIds: ["lesson-unit0-combining-vowels"],
    introducesPartIds: [],
    introducesTermIds: [],
    reinforcesTermIds: ["term-cardiology", "term-neurology", "term-gastritis"],
    exerciseSetIds: ["exercise-pronunciation-1", "exercise-pronunciation-2"],
    estimatedMinutes: 5,
    status: "shipped",
  },
  {
    id: "lesson-unit1-common-suffixes",
    title: "High-Yield Suffixes: -itis and -logy",
    unitId: "unit-1",
    objective: "Decode common suffixes that point to inflammation and fields of study.",
    whyItMatters: "Common suffixes appear in both everyday terms and specialty names.",
    prerequisiteLessonIds: ["lesson-unit0-word-parts"],
    introducesPartIds: ["part-itis-suffix", "part-ology-suffix"],
    introducesTermIds: ["term-gastritis", "term-arthritis"],
    reinforcesTermIds: ["term-cardiology", "term-neurology"],
    exerciseSetIds: ["exercise-suffixes-1"],
    estimatedMinutes: 7,
    status: "shipped",
  },
  {
    id: "lesson-unit1-core-body-roots",
    title: "Core Body Roots You Will See Everywhere",
    unitId: "unit-1",
    objective: "Recognize high-yield roots for joints, skin, liver, kidneys, blood, and nerve pain.",
    whyItMatters: "A small set of organ and tissue roots unlocks many later body-system terms.",
    prerequisiteLessonIds: ["lesson-unit1-common-suffixes"],
    introducesPartIds: [
      "part-arthr-combining",
      "part-hemat-combining",
      "part-derm-combining",
      "part-hepat-combining",
      "part-nephr-combining",
      "part-algia-suffix"
    ],
    introducesTermIds: [
      "term-arthritis",
      "term-dermatitis",
      "term-hepatitis",
      "term-nephrology",
      "term-hematology",
      "term-neuralgia"
    ],
    reinforcesTermIds: ["term-gastritis", "term-cardiology", "term-neurology"],
    exerciseSetIds: ["exercise-body-roots-1", "exercise-body-roots-2"],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit1-common-prefixes",
    title: "Common Prefixes: Hyper- and Hypo-",
    unitId: "unit-1",
    objective: "Recognize common intensity prefixes that change meaning quickly.",
    whyItMatters: "A single prefix often flips whether a medical state is too much or too little.",
    prerequisiteLessonIds: ["lesson-unit1-common-suffixes"],
    introducesPartIds: ["part-hyper-prefix", "part-hypo-prefix"],
    introducesTermIds: ["term-hypertension", "term-hypotension"],
    reinforcesTermIds: ["term-gastritis", "term-arthritis"],
    exerciseSetIds: ["exercise-prefixes-1"],
    estimatedMinutes: 5,
    status: "shipped",
  },
  {
    id: "lesson-unit1-rate-prefixes",
    title: "Rate Prefixes: Tachy- and Brady-",
    unitId: "unit-1",
    objective: "Decode high-yield prefixes that signal faster or slower than normal.",
    whyItMatters: "Fast-versus-slow contrasts show up constantly in cardiovascular language.",
    prerequisiteLessonIds: ["lesson-unit1-common-prefixes"],
    introducesPartIds: ["part-tachy-prefix", "part-brady-prefix"],
    introducesTermIds: ["term-tachycardia", "term-bradycardia"],
    reinforcesTermIds: ["term-hypertension", "term-hypotension"],
    exerciseSetIds: ["exercise-rate-prefixes-1", "exercise-rate-prefixes-2"],
    estimatedMinutes: 6,
    status: "shipped",
  },
  {
    id: "lesson-unit1-procedure-language",
    title: "Procedure Language: Removal, Incision, Viewing, Record",
    unitId: "unit-1",
    objective: "Recognize procedure suffixes that describe what a clinician is doing.",
    whyItMatters: "Procedure language is one of the fastest ways to decode charts, consults, and specialty names.",
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    introducesPartIds: [
      "part-appendic-combining",
      "part-col-combining",
      "part-ectomy-suffix",
      "part-otomy-suffix",
      "part-scopy-suffix",
      "part-gram-suffix"
    ],
    introducesTermIds: [
      "term-appendectomy",
      "term-colonoscopy",
      "term-gastrotomy",
      "term-cardiogram"
    ],
    reinforcesTermIds: ["term-gastritis", "term-cardiology"],
    exerciseSetIds: ["exercise-procedures-1", "exercise-procedures-2"],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit2-cardiovascular-starter",
    title: "Cardiovascular Starter Terms",
    unitId: "unit-2",
    objective: "Recognize core vessel and artery terms in the first body-system module.",
    whyItMatters: "Cardiovascular language appears often and combines many high-yield roots already learned.",
    prerequisiteLessonIds: ["lesson-unit1-rate-prefixes", "lesson-unit1-procedure-language"],
    introducesPartIds: ["part-angi-combining", "part-arteri-combining", "part-ven-combining"],
    introducesTermIds: ["term-angiogram", "term-arteritis", "term-venogram"],
    reinforcesTermIds: [
      "term-hypertension",
      "term-hypotension",
      "term-tachycardia",
      "term-bradycardia",
      "term-cardiogram"
    ],
    exerciseSetIds: ["exercise-cardio-1", "exercise-cardio-2"],
    estimatedMinutes: 8,
    status: "shipped",
  }
];
