import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-word-parts-1",
    type: "root_match",
    prompt: "Which word part points to the heart?",
    choices: ["cardi", "gastr", "neur", "-itis"],
    answer: "cardi",
    explanation: "`cardi` points to the heart in words like `cardiology` and `cardiac`.",
    linkedTermIds: ["term-cardiology"],
    linkedPartIds: ["part-cardi-root"],
  },
  {
    id: "exercise-word-parts-2",
    type: "infer_meaning",
    prompt: "If `neur` means nerve and `-logy` means study of, what does `neurology` suggest?",
    choices: [
      "study of the nervous system",
      "inflammation of nerves",
      "pain in the head",
      "recording of muscles"
    ],
    answer: "study of the nervous system",
    explanation: "The parts point to a field of study centered on nerves and the nervous system.",
    linkedTermIds: ["term-neurology"],
    linkedPartIds: ["part-neur-root", "part-ology-suffix"],
  },
  {
    id: "exercise-combining-1",
    type: "split_term",
    prompt: "Why does `oste/o` include the `o`?",
    choices: [
      "It helps the word join smoothly to another part",
      "It marks a plural ending",
      "It means above normal",
      "It turns the root into a suffix"
    ],
    answer: "It helps the word join smoothly to another part",
    explanation: "The combining vowel keeps many medical terms pronounceable when parts are joined.",
    linkedTermIds: [],
    linkedPartIds: ["part-osteo-combining"],
  },
  {
    id: "exercise-combining-2",
    type: "cloze",
    prompt: "Complete the rule: a combining vowel usually makes a long medical term easier to ___.",
    choices: ["pronounce", "diagnose", "memorize", "prescribe"],
    answer: "pronounce",
    explanation: "Combining vowels primarily help the parts connect and sound smoother.",
    linkedTermIds: [],
    linkedPartIds: ["part-osteo-combining"],
  },
  {
    id: "exercise-plurals-1",
    type: "infer_meaning",
    prompt: "Which form names more than one vertebra?",
    choices: ["vertebra", "vertebrae", "diagnosis", "bacterium"],
    answer: "vertebrae",
    explanation: "`vertebrae` is the plural form, while `vertebra` refers to one spinal bone.",
    linkedTermIds: ["term-vertebra", "term-vertebrae"],
    linkedPartIds: [],
  },
  {
    id: "exercise-plurals-2",
    type: "root_match",
    prompt: "Which singular and plural pair is correct?",
    choices: [
      "diagnosis / diagnoses",
      "diagnosis / diagnosis",
      "bacterium / bacteriums",
      "vertebrae / vertebra"
    ],
    answer: "diagnosis / diagnoses",
    explanation: "Several medical terms keep classical plural endings such as `-is` to `-es`.",
    linkedTermIds: ["term-diagnosis", "term-diagnoses"],
    linkedPartIds: [],
  },
  {
    id: "exercise-pronunciation-1",
    type: "split_term",
    prompt: "In `cardiology`, which syllable usually carries the main stress?",
    choices: ["OL", "KAR", "jee", "dee"],
    answer: "OL",
    explanation: "Many longer medical terms place the strongest stress close to the end of the word.",
    linkedTermIds: ["term-cardiology"],
    linkedPartIds: [],
  },
  {
    id: "exercise-pronunciation-2",
    type: "root_match",
    prompt: "Which ending is usually pronounced like `EYE-tis`?",
    choices: ["-itis", "-logy", "-gram", "-scopy"],
    answer: "-itis",
    explanation: "The inflammation suffix `-itis` is commonly pronounced `EYE-tis`.",
    linkedTermIds: ["term-gastritis"],
    linkedPartIds: ["part-itis-suffix"],
  },
  {
    id: "exercise-suffixes-1",
    type: "infer_meaning",
    prompt: "If `gastr` means stomach and `-itis` means inflammation, what is `gastritis`?",
    choices: [
      "inflammation of the stomach",
      "study of the stomach",
      "stomach surgery",
      "pain in the stomach"
    ],
    answer: "inflammation of the stomach",
    explanation: "This is a straightforward root-plus-suffix combination.",
    linkedTermIds: ["term-gastritis"],
    linkedPartIds: ["part-gastr-root", "part-itis-suffix"],
  },
  {
    id: "exercise-body-roots-1",
    type: "infer_meaning",
    prompt: "If `derm/o` means skin and `-itis` means inflammation, what does `dermatitis` mean?",
    choices: [
      "inflammation of the skin",
      "study of the skin",
      "pain in the skin",
      "removal of the skin"
    ],
    answer: "inflammation of the skin",
    explanation: "The root and suffix point directly to inflammation in the skin.",
    linkedTermIds: ["term-dermatitis"],
    linkedPartIds: ["part-derm-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-body-roots-2",
    type: "root_match",
    prompt: "Which combining form points to the kidney?",
    choices: ["nephr/o", "hepat/o", "hemat/o", "arthr/o"],
    answer: "nephr/o",
    explanation: "`nephr/o` points to the kidney in words like `nephrology`.",
    linkedTermIds: ["term-nephrology"],
    linkedPartIds: ["part-nephr-combining"],
  },
  {
    id: "exercise-prefixes-1",
    type: "infer_meaning",
    prompt: "Which prefix points to a value above normal?",
    choices: ["hyper-", "hypo-", "-itis", "neur"],
    answer: "hyper-",
    explanation: "`hyper-` often signals something higher or greater than normal.",
    linkedTermIds: ["term-hypertension"],
    linkedPartIds: ["part-hyper-prefix"],
  },
  {
    id: "exercise-rate-prefixes-1",
    type: "root_match",
    prompt: "Which prefix suggests a rate that is too fast?",
    choices: ["tachy-", "brady-", "hypo-", "hyper-"],
    answer: "tachy-",
    explanation: "`tachy-` points to speed or a fast rate.",
    linkedTermIds: ["term-tachycardia"],
    linkedPartIds: ["part-tachy-prefix"],
  },
  {
    id: "exercise-rate-prefixes-2",
    type: "infer_meaning",
    prompt: "What does `bradycardia` suggest?",
    choices: [
      "a heart rate that is too slow",
      "a heart rate that is too fast",
      "inflammation of the heart",
      "study of the heart"
    ],
    answer: "a heart rate that is too slow",
    explanation: "`brady-` points to slow, and `cardi` points to the heart.",
    linkedTermIds: ["term-bradycardia"],
    linkedPartIds: ["part-brady-prefix", "part-cardi-root"],
  },
  {
    id: "exercise-procedures-1",
    type: "infer_meaning",
    prompt: "What does `appendectomy` suggest?",
    choices: [
      "surgical removal of the appendix",
      "inflammation of the appendix",
      "viewing the appendix with a scope",
      "record of the appendix"
    ],
    answer: "surgical removal of the appendix",
    explanation: "`appendic/o` points to the appendix and `-ectomy` means surgical removal.",
    linkedTermIds: ["term-appendectomy"],
    linkedPartIds: ["part-appendic-combining", "part-ectomy-suffix"],
  },
  {
    id: "exercise-procedures-2",
    type: "root_match",
    prompt: "Which suffix signals viewing with a scope?",
    choices: ["-scopy", "-otomy", "-ectomy", "-gram"],
    answer: "-scopy",
    explanation: "`-scopy` points to a visual examination with a scope.",
    linkedTermIds: ["term-colonoscopy"],
    linkedPartIds: ["part-scopy-suffix"],
  },
  {
    id: "exercise-cardio-1",
    type: "infer_meaning",
    prompt: "If `angi/o` means vessel and `-gram` means record or image, what is an `angiogram`?",
    choices: [
      "a vessel image or record",
      "inflammation of a vessel",
      "surgical removal of a vessel",
      "study of a vessel"
    ],
    answer: "a vessel image or record",
    explanation: "The combining form and suffix together point to an imaging record of vessels.",
    linkedTermIds: ["term-angiogram"],
    linkedPartIds: ["part-angi-combining", "part-gram-suffix"],
  },
  {
    id: "exercise-cardio-2",
    type: "infer_meaning",
    prompt: "What does `arteritis` suggest?",
    choices: [
      "inflammation of an artery",
      "study of an artery",
      "image of an artery",
      "slow artery flow"
    ],
    answer: "inflammation of an artery",
    explanation: "`arteri/o` points to an artery and `-itis` points to inflammation.",
    linkedTermIds: ["term-arteritis"],
    linkedPartIds: ["part-arteri-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-respiratory-airway-1",
    type: "root_match",
    prompt: "Which combining form points to a bronchial tube or airway branch?",
    choices: ["bronch/o", "trache/o", "pneum/o", "pulmon/o"],
    answer: "bronch/o",
    explanation: "`bronch/o` points to the branching airways inside the lungs.",
    linkedTermIds: ["term-bronchitis", "term-bronchoscopy"],
    linkedPartIds: ["part-bronch-combining"],
  },
  {
    id: "exercise-respiratory-airway-2",
    type: "infer_meaning",
    prompt: "If `bronch/o` means bronchial tube and `-itis` means inflammation, what does `bronchitis` suggest?",
    choices: [
      "inflammation of the bronchial tubes",
      "viewing the bronchial tubes with a scope",
      "a cut into the windpipe",
      "a condition related to the lungs"
    ],
    answer: "inflammation of the bronchial tubes",
    explanation: "This follows the same root-plus-inflammation pattern used in other `-itis` terms.",
    linkedTermIds: ["term-bronchitis"],
    linkedPartIds: ["part-bronch-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-respiratory-airway-3",
    type: "infer_meaning",
    prompt: "What does `tracheotomy` suggest?",
    choices: [
      "an incision into the trachea",
      "inflammation of the trachea",
      "viewing the trachea with a scope",
      "a record of the trachea"
    ],
    answer: "an incision into the trachea",
    explanation: "`trache/o` points to the windpipe and `-otomy` points to an incision.",
    linkedTermIds: ["term-tracheotomy"],
    linkedPartIds: ["part-trache-combining", "part-otomy-suffix"],
  },
  {
    id: "exercise-respiratory-status-1",
    type: "root_match",
    prompt: "Which suffix points to breathing?",
    choices: ["-pnea", "-oxia", "-gram", "-scopy"],
    answer: "-pnea",
    explanation: "`-pnea` shows up in breathing-rate and breathing-difficulty terms.",
    linkedTermIds: ["term-tachypnea", "term-dyspnea"],
    linkedPartIds: ["part-pnea-suffix"],
  },
  {
    id: "exercise-respiratory-status-2",
    type: "infer_meaning",
    prompt: "What does `dyspnea` suggest in plain English?",
    choices: [
      "difficult breathing or shortness of breath",
      "slow breathing",
      "fast breathing",
      "low oxygen"
    ],
    answer: "difficult breathing or shortness of breath",
    explanation: "`dys-` points to difficulty or abnormal function and `-pnea` points to breathing.",
    linkedTermIds: ["term-dyspnea"],
    linkedPartIds: ["part-dys-prefix", "part-pnea-suffix"],
  },
  {
    id: "exercise-gastro-inflammation-1",
    type: "infer_meaning",
    prompt: "If `enter/o` means intestine and `-itis` means inflammation, what does `enteritis` suggest?",
    choices: [
      "inflammation of the intestine",
      "a scope exam of the intestine",
      "surgical removal of the intestine",
      "a record of the intestine"
    ],
    answer: "inflammation of the intestine",
    explanation: "This is another direct combining-form plus suffix term.",
    linkedTermIds: ["term-enteritis"],
    linkedPartIds: ["part-enter-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-gastro-inflammation-2",
    type: "infer_meaning",
    prompt: "What does `gastroenteritis` suggest?",
    choices: [
      "inflammation involving the stomach and intestines",
      "surgical removal of the stomach",
      "viewing the stomach and intestines with a scope",
      "pain in the stomach and intestines"
    ],
    answer: "inflammation involving the stomach and intestines",
    explanation: "The term combines `gastr` for stomach, `enter/o` for intestine, and `-itis` for inflammation.",
    linkedTermIds: ["term-gastroenteritis"],
    linkedPartIds: ["part-gastr-root", "part-enter-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-gastro-procedures-1",
    type: "infer_meaning",
    prompt: "What does `cholecystectomy` suggest?",
    choices: [
      "surgical removal of the gallbladder",
      "inflammation of the gallbladder",
      "a scoped look at the gallbladder",
      "an incision into the gallbladder"
    ],
    answer: "surgical removal of the gallbladder",
    explanation: "`cholecyst/o` points to the gallbladder and `-ectomy` points to removal.",
    linkedTermIds: ["term-cholecystectomy"],
    linkedPartIds: ["part-cholecyst-combining", "part-ectomy-suffix"],
  },
  {
    id: "exercise-musculoskeletal-1",
    type: "root_match",
    prompt: "Which suffix points to a disease or disorder?",
    choices: ["-pathy", "-plasty", "-algia", "-uria"],
    answer: "-pathy",
    explanation: "`-pathy` points to disease or disorder in terms like `myopathy` and `arthropathy`.",
    linkedTermIds: ["term-myopathy", "term-arthropathy"],
    linkedPartIds: ["part-pathy-suffix"],
  },
  {
    id: "exercise-musculoskeletal-2",
    type: "infer_meaning",
    prompt: "If `my/o` means muscle and `-algia` means pain, what does `myalgia` suggest?",
    choices: [
      "muscle pain",
      "muscle repair",
      "joint disease",
      "blood in the urine"
    ],
    answer: "muscle pain",
    explanation: "The combining form points to muscle and the suffix points to pain.",
    linkedTermIds: ["term-myalgia"],
    linkedPartIds: ["part-my-combining", "part-algia-suffix"],
  },
  {
    id: "exercise-musculoskeletal-3",
    type: "infer_meaning",
    prompt: "What does `arthroplasty` suggest?",
    choices: [
      "surgical repair or reconstruction of a joint",
      "inflammation of a joint",
      "joint pain",
      "an image of a joint"
    ],
    answer: "surgical repair or reconstruction of a joint",
    explanation: "`arthr/o` points to a joint and `-plasty` points to repair or reconstruction.",
    linkedTermIds: ["term-arthroplasty"],
    linkedPartIds: ["part-arthr-combining", "part-plasty-suffix"],
  },
  {
    id: "exercise-renal-1",
    type: "infer_meaning",
    prompt: "If `cyst/o` means bladder and `-itis` means inflammation, what does `cystitis` suggest?",
    choices: [
      "inflammation of the bladder",
      "viewing the bladder with a scope",
      "blood in the urine",
      "the study of the bladder"
    ],
    answer: "inflammation of the bladder",
    explanation: "This follows the same inflammation pattern used in earlier body-system lessons.",
    linkedTermIds: ["term-cystitis"],
    linkedPartIds: ["part-cyst-combining", "part-itis-suffix"],
  },
  {
    id: "exercise-renal-2",
    type: "infer_meaning",
    prompt: "What does `hematuria` suggest?",
    choices: [
      "blood in the urine",
      "kidney inflammation",
      "bladder viewing with a scope",
      "slow urination"
    ],
    answer: "blood in the urine",
    explanation: "`hemat/o` points to blood and `-uria` points to a urine condition or urination finding.",
    linkedTermIds: ["term-hematuria"],
    linkedPartIds: ["part-hemat-combining", "part-uria-suffix"],
  },
  {
    id: "exercise-renal-3",
    type: "infer_meaning",
    prompt: "What does `cystoscopy` suggest?",
    choices: [
      "viewing the bladder with a scope",
      "surgical removal of the bladder",
      "inflammation of the bladder",
      "blood in the urine"
    ],
    answer: "viewing the bladder with a scope",
    explanation: "`cyst/o` points to the bladder and `-scopy` points to viewing with a scope.",
    linkedTermIds: ["term-cystoscopy"],
    linkedPartIds: ["part-cyst-combining", "part-scopy-suffix"],
  },
  {
    id: "exercise-unit3-status-1",
    type: "root_match",
    prompt: "Which suffix points to enlargement?",
    choices: ["-megaly", "-emia", "-uria", "-pathy"],
    answer: "-megaly",
    explanation: "`-megaly` signals enlargement in terms like `cardiomegaly` and `hepatomegaly`.",
    linkedTermIds: ["term-cardiomegaly", "term-hepatomegaly"],
    linkedPartIds: ["part-megaly-suffix"],
  },
  {
    id: "exercise-unit3-status-2",
    type: "infer_meaning",
    prompt: "If `cardi` means heart and `-megaly` means enlargement, what does `cardiomegaly` suggest?",
    choices: [
      "enlargement of the heart",
      "pain in the heart",
      "imaging of the heart",
      "a fast heart rate"
    ],
    answer: "enlargement of the heart",
    explanation: "The root and suffix together point to an enlarged heart.",
    linkedTermIds: ["term-cardiomegaly"],
    linkedPartIds: ["part-cardi-root", "part-megaly-suffix"],
  },
  {
    id: "exercise-unit3-status-3",
    type: "infer_meaning",
    prompt: "Which term best matches swelling from extra fluid?",
    choices: ["edema", "anemia", "dyspnea", "neuralgia"],
    answer: "edema",
    explanation: "`edema` is a high-frequency clinical status word for swelling caused by extra fluid.",
    linkedTermIds: ["term-edema"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-procedures-1",
    type: "root_match",
    prompt: "Which suffix points to the process of recording or imaging?",
    choices: ["-graphy", "-gram", "-scopy", "-otomy"],
    answer: "-graphy",
    explanation: "`-graphy` points to the process of imaging or recording rather than the final image itself.",
    linkedTermIds: ["term-angiography", "term-cardiography"],
    linkedPartIds: ["part-graphy-suffix"],
  },
  {
    id: "exercise-unit3-procedures-2",
    type: "infer_meaning",
    prompt: "What does `angioplasty` suggest?",
    choices: [
      "surgical repair or widening of a vessel",
      "an image of a vessel",
      "viewing a vessel with a scope",
      "inflammation of a vessel"
    ],
    answer: "surgical repair or widening of a vessel",
    explanation: "`angi/o` points to a vessel and `-plasty` points to repair or reshaping.",
    linkedTermIds: ["term-angioplasty"],
    linkedPartIds: ["part-angi-combining", "part-plasty-suffix"],
  },
  {
    id: "exercise-unit3-procedures-3",
    type: "infer_meaning",
    prompt: "If `arthr/o` means joint and `-scopy` means viewing with a scope, what does `arthroscopy` mean?",
    choices: [
      "viewing a joint with a scope",
      "repairing a joint",
      "cutting into bone",
      "recording heart activity"
    ],
    answer: "viewing a joint with a scope",
    explanation: "This is the same procedure-family pattern used in other scope terms across systems.",
    linkedTermIds: ["term-arthroscopy"],
    linkedPartIds: ["part-arthr-combining", "part-scopy-suffix"],
  },
  {
    id: "exercise-unit4-scheduling-1",
    type: "root_match",
    prompt: "Which prefix points to before?",
    choices: ["pre-", "post-", "contra-", "hypo-"],
    answer: "pre-",
    explanation: "`pre-` points to something happening before an operation or other event.",
    linkedTermIds: ["term-preoperative"],
    linkedPartIds: ["part-pre-prefix"],
  },
  {
    id: "exercise-unit4-scheduling-2",
    type: "infer_meaning",
    prompt: "What does `postoperative` suggest?",
    choices: [
      "after an operation",
      "before an operation",
      "care without hospital admission",
      "approval needed before care"
    ],
    answer: "after an operation",
    explanation: "`post-` points to after, so `postoperative` refers to the period after surgery.",
    linkedTermIds: ["term-postoperative"],
    linkedPartIds: ["part-post-prefix"],
  },
  {
    id: "exercise-unit4-scheduling-3",
    type: "infer_meaning",
    prompt: "Which phrase best matches care without hospital admission?",
    choices: ["outpatient", "inpatient", "follow-up", "preoperative"],
    answer: "outpatient",
    explanation: "`outpatient` refers to care that does not require staying in the hospital.",
    linkedTermIds: ["term-outpatient"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-records-1",
    type: "infer_meaning",
    prompt: "Which phrase means approval is needed before some care is covered?",
    choices: [
      "prior authorization",
      "referral",
      "documentation",
      "discharge instructions"
    ],
    answer: "prior authorization",
    explanation: "`prior authorization` means approval is needed before certain services or medications are covered.",
    linkedTermIds: ["term-prior-authorization"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-records-2",
    type: "infer_meaning",
    prompt: "If `contra-` means against, what does `contraindication` suggest?",
    choices: [
      "a reason not to use a treatment or medication",
      "a record of treatment",
      "permission to proceed with treatment",
      "instructions after discharge"
    ],
    answer: "a reason not to use a treatment or medication",
    explanation: "`contra-` points to something that argues against an intervention.",
    linkedTermIds: ["term-contraindication"],
    linkedPartIds: ["part-contra-prefix"],
  },
  {
    id: "exercise-unit4-records-3",
    type: "infer_meaning",
    prompt: "Which document should a learner read after leaving the hospital or clinic?",
    choices: [
      "discharge instructions",
      "referral",
      "documentation",
      "prior authorization"
    ],
    answer: "discharge instructions",
    explanation: "`discharge instructions` are the take-home directions given after care.",
    linkedTermIds: ["term-discharge-instructions"],
    linkedPartIds: [],
  },
  {
    id: "exercise-nervous-1",
    type: "root_match",
    prompt: "Which suffix points to paralysis?",
    choices: ["-plegia", "-pathy", "-megaly", "-uria"],
    answer: "-plegia",
    explanation: "`-plegia` points to paralysis in terms like `hemiplegia` and `paraplegia`.",
    linkedTermIds: ["term-hemiplegia"],
    linkedPartIds: ["part-plegia-suffix"],
  },
  {
    id: "exercise-nervous-2",
    type: "infer_meaning",
    prompt: "If `neur` means nerve and `-pathy` means disease or disorder, what does `neuropathy` suggest?",
    choices: [
      "nerve disease or nerve damage",
      "inflammation of the brain",
      "one-sided paralysis",
      "swelling in brain tissue"
    ],
    answer: "nerve disease or nerve damage",
    explanation: "`neuropathy` is a direct combination of the nerve root and a disorder suffix.",
    linkedTermIds: ["term-neuropathy"],
    linkedPartIds: ["part-neur-root", "part-pathy-suffix"],
  },
  {
    id: "exercise-nervous-3",
    type: "infer_meaning",
    prompt: "What does `hemiplegia` suggest?",
    choices: [
      "paralysis affecting one side of the body",
      "inflammation of one side of the brain",
      "pain in half the body",
      "a disease of the spinal cord"
    ],
    answer: "paralysis affecting one side of the body",
    explanation: "`hemi-` points to one side and `-plegia` points to paralysis.",
    linkedTermIds: ["term-hemiplegia"],
    linkedPartIds: ["part-hemi-prefix", "part-plegia-suffix"],
  },
  {
    id: "exercise-unit3-chart-1",
    type: "infer_meaning",
    prompt: "Which note section usually states the clinician's impression of what is going on?",
    choices: ["assessment", "plan", "monitoring", "stable"],
    answer: "assessment",
    explanation: "`assessment` is the section where the clinician summarizes the evaluation or impression.",
    linkedTermIds: ["term-assessment"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-chart-2",
    type: "infer_meaning",
    prompt: "What does `plan` usually suggest in chart language?",
    choices: [
      "the next treatment or follow-up steps",
      "the patient's main symptom",
      "a final billing decision",
      "movement to another unit"
    ],
    answer: "the next treatment or follow-up steps",
    explanation: "A chart `plan` usually covers orders, treatment decisions, or follow-up actions.",
    linkedTermIds: ["term-plan"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-chart-3",
    type: "infer_meaning",
    prompt: "If a patient is described as `stable`, what does that usually suggest?",
    choices: [
      "the condition is steady and not currently worsening",
      "the patient is ready for surgery right away",
      "the patient has been discharged",
      "the patient needs an insurance claim"
    ],
    answer: "the condition is steady and not currently worsening",
    explanation: "`stable` usually signals that the condition is holding steady for now.",
    linkedTermIds: ["term-stable"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-workflow-1",
    type: "infer_meaning",
    prompt: "What does `admission` suggest in hospital workflow?",
    choices: [
      "formally entering the hospital for care",
      "leaving the hospital with instructions",
      "requesting payment from an insurer",
      "watching a patient over time"
    ],
    answer: "formally entering the hospital for care",
    explanation: "`admission` refers to being taken into the hospital for ongoing treatment or observation.",
    linkedTermIds: ["term-admission"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-workflow-2",
    type: "infer_meaning",
    prompt: "What does `consult` suggest?",
    choices: [
      "a request for another clinician's opinion",
      "a transfer to another room",
      "the main reason for the visit",
      "approval before coverage"
    ],
    answer: "a request for another clinician's opinion",
    explanation: "`consult` usually means another clinician or service is asked to evaluate the patient or provide input.",
    linkedTermIds: ["term-consult"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-workflow-3",
    type: "infer_meaning",
    prompt: "Which term best matches moving a patient from one unit or facility to another?",
    choices: ["transfer", "discharge", "assessment", "monitoring"],
    answer: "transfer",
    explanation: "`transfer` refers to movement between locations, services, or facilities within the care process.",
    linkedTermIds: ["term-transfer"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-intake-1",
    type: "infer_meaning",
    prompt: "Which intake phrase usually means the main reason for today's visit?",
    choices: ["chief complaint", "medical history", "consent form", "coverage"],
    answer: "chief complaint",
    explanation: "`chief complaint` is the standard label for the patient's main concern or reason for the visit.",
    linkedTermIds: ["term-chief-complaint"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-intake-2",
    type: "infer_meaning",
    prompt: "Why does a clinic ask for a `medication list`?",
    choices: [
      "to know which medicines the patient is currently taking",
      "to decide whether insurance will approve the visit",
      "to record the clinician's final impression",
      "to measure breathing difficulty"
    ],
    answer: "to know which medicines the patient is currently taking",
    explanation: "A medication list helps the care team avoid errors, duplications, and harmful interactions.",
    linkedTermIds: ["term-medication-list"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-intake-3",
    type: "infer_meaning",
    prompt: "Which intake item asks about drug, food, or environmental reactions that matter for safe care?",
    choices: ["allergies", "copay", "claim", "transfer"],
    answer: "allergies",
    explanation: "`allergies` alerts the care team to reactions or sensitivities that can affect safe treatment.",
    linkedTermIds: ["term-allergies"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-billing-1",
    type: "infer_meaning",
    prompt: "What does `copay` mean?",
    choices: [
      "a fixed amount the patient pays at the time of care",
      "the full yearly insurance premium",
      "a request sent to a specialist",
      "a note about past medical problems"
    ],
    answer: "a fixed amount the patient pays at the time of care",
    explanation: "`copay` is the set amount a patient pays for a visit, prescription, or other covered service.",
    linkedTermIds: ["term-copay"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-billing-2",
    type: "infer_meaning",
    prompt: "What does `deductible` suggest?",
    choices: [
      "the amount paid before some insurance coverage starts",
      "a second opinion request from another doctor",
      "a document signed before a procedure",
      "the main symptom written on intake paperwork"
    ],
    answer: "the amount paid before some insurance coverage starts",
    explanation: "`deductible` refers to what the patient usually pays before the plan starts covering more costs.",
    linkedTermIds: ["term-deductible"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-billing-3",
    type: "infer_meaning",
    prompt: "Which word best matches an insurer refusing payment or requested coverage?",
    choices: ["denial", "coverage", "assessment", "allergies"],
    answer: "denial",
    explanation: "`denial` is the insurer's refusal to approve or pay for the requested item or service.",
    linkedTermIds: ["term-denial"],
    linkedPartIds: [],
  },
  {
    id: "exercise-endocrine-1",
    type: "root_match",
    prompt: "Which combining form points to sugar or glucose?",
    choices: ["glyc/o", "thyroid/o", "cyst/o", "bronch/o"],
    answer: "glyc/o",
    explanation: "`glyc/o` points to sugar or glucose in words like `hyperglycemia` and `hypoglycemia`.",
    linkedTermIds: ["term-hyperglycemia", "term-hypoglycemia"],
    linkedPartIds: ["part-glyc-combining"],
  },
  {
    id: "exercise-endocrine-2",
    type: "infer_meaning",
    prompt: "What does `hyperglycemia` suggest?",
    choices: [
      "high blood sugar",
      "low blood sugar",
      "inflammation of the thyroid gland",
      "removal of the thyroid gland"
    ],
    answer: "high blood sugar",
    explanation: "`hyper-` points to above normal and `glyc/o` points to sugar or glucose.",
    linkedTermIds: ["term-hyperglycemia"],
    linkedPartIds: ["part-hyper-prefix", "part-glyc-combining"],
  },
  {
    id: "exercise-endocrine-3",
    type: "infer_meaning",
    prompt: "If `thyroid/o` means thyroid gland and `-ectomy` means surgical removal, what does `thyroidectomy` suggest?",
    choices: [
      "surgical removal of the thyroid gland",
      "inflammation of the thyroid gland",
      "high blood sugar",
      "a hormone made by the thyroid gland"
    ],
    answer: "surgical removal of the thyroid gland",
    explanation: "This follows the same organ-plus-procedure pattern used in other `-ectomy` terms.",
    linkedTermIds: ["term-thyroidectomy"],
    linkedPartIds: ["part-thyroid-combining", "part-ectomy-suffix"],
  },
  {
    id: "exercise-unit3-diagnostics-1",
    type: "infer_meaning",
    prompt: "What does `biopsy` suggest?",
    choices: [
      "removal of a small tissue sample for examination",
      "an imaging test that uses sound waves",
      "the final summary at the end of a report",
      "medicine given by mouth"
    ],
    answer: "removal of a small tissue sample for examination",
    explanation: "`biopsy` refers to taking a small sample so it can be studied more closely.",
    linkedTermIds: ["term-biopsy"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-diagnostics-2",
    type: "infer_meaning",
    prompt: "In report language, what are `findings`?",
    choices: [
      "the observations or results seen on an exam, image, or test",
      "the amount and schedule of a medicine",
      "an online account for patient messages",
      "a request for another specialist's opinion"
    ],
    answer: "the observations or results seen on an exam, image, or test",
    explanation: "`findings` names what the clinician or report actually observed.",
    linkedTermIds: ["term-findings"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-diagnostics-3",
    type: "infer_meaning",
    prompt: "Which report section usually gives the short summary interpretation at the end?",
    choices: ["impression", "specimen", "ultrasound", "dosage"],
    answer: "impression",
    explanation: "`impression` is commonly used for the brief take-home interpretation or summary.",
    linkedTermIds: ["term-impression"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-medications-1",
    type: "infer_meaning",
    prompt: "What does `oral` usually mean for a medication?",
    choices: [
      "taken by mouth",
      "given into a vein",
      "applied on the skin",
      "administered as a scan"
    ],
    answer: "taken by mouth",
    explanation: "`oral` describes medication that goes through the mouth rather than by needle or skin application.",
    linkedTermIds: ["term-oral"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit3-medications-2",
    type: "infer_meaning",
    prompt: "If `intra-` means within and `ven/o` points to a vein, what does `intravenous` suggest?",
    choices: [
      "given into a vein",
      "applied on the skin",
      "taken under the tongue",
      "used after discharge only"
    ],
    answer: "given into a vein",
    explanation: "`intravenous` literally points to something delivered within a vein.",
    linkedTermIds: ["term-intravenous"],
    linkedPartIds: ["part-intra-prefix", "part-ven-combining"],
  },
  {
    id: "exercise-unit3-medications-3",
    type: "infer_meaning",
    prompt: "What does `dosage` refer to?",
    choices: [
      "the amount and schedule of a medicine",
      "the sample sent to the lab",
      "the summary line at the end of a report",
      "the process of entering the hospital"
    ],
    answer: "the amount and schedule of a medicine",
    explanation: "`dosage` covers how much medicine is used and how often it should be taken or given.",
    linkedTermIds: ["term-dosage"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-portal-1",
    type: "infer_meaning",
    prompt: "Portal notice: `Your test results are ready to review.` What does `test results` refer to here?",
    choices: [
      "the reported outcome of a completed test",
      "a request for more medication",
      "a reminder about an upcoming appointment",
      "a summary of the insurance deductible"
    ],
    answer: "the reported outcome of a completed test",
    explanation: "`test results` names the information returned after a lab, imaging study, or other test is completed.",
    linkedTermIds: ["term-test-results"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-portal-2",
    type: "infer_meaning",
    prompt: "Message header: `After-visit summary available.` What is the `after-visit summary`?",
    choices: [
      "the take-home summary of the visit and next steps",
      "a request for a specialist opinion",
      "a billing claim sent to insurance",
      "a tissue sample sent for testing"
    ],
    answer: "the take-home summary of the visit and next steps",
    explanation: "An `after-visit summary` is the short review of what happened during the visit and what should happen next.",
    linkedTermIds: ["term-after-visit-summary"],
    linkedPartIds: [],
  },
  {
    id: "exercise-unit4-portal-3",
    type: "infer_meaning",
    prompt: "Portal action: `Send refill request.` What does `refill request` mean?",
    choices: [
      "ask for more of an existing prescription",
      "reschedule the appointment",
      "upload a new insurance card",
      "read a radiology impression"
    ],
    answer: "ask for more of an existing prescription",
    explanation: "`refill request` means asking for another supply of a medicine that is already prescribed.",
    linkedTermIds: ["term-refill-request"],
    linkedPartIds: [],
  }
];

export const lessons: Lesson[] = [
  {
    id: "lesson-unit0-word-parts",
    title: "Word Parts That Carry Meaning",
    unitId: "unit-0",
    objective: "Identify roots and suffixes that make common terms decodable.",
    whyItMatters: "A small set of roots and suffixes unlocks much of basic medical language.",
    prerequisiteLessonIds: [],
    introducesPartIds: ["part-cardi-root", "part-gastr-root", "part-neur-root", "part-ology-suffix"],
    introducesTermIds: ["term-cardiology", "term-neurology"],
    reinforcesTermIds: [],
    exerciseSetIds: ["exercise-word-parts-1", "exercise-word-parts-2"],
    estimatedMinutes: 6,
    status: "shipped",
  },
  {
    id: "lesson-unit0-combining-vowels",
    title: "Combining Vowels and Smooth Joins",
    unitId: "unit-0",
    objective: "Explain why many medical terms use connecting vowels.",
    whyItMatters: "Learners decode faster when they understand why forms like `oste/o` appear.",
    prerequisiteLessonIds: ["lesson-unit0-word-parts"],
    introducesPartIds: ["part-osteo-combining"],
    introducesTermIds: [],
    reinforcesTermIds: ["term-cardiology", "term-neurology"],
    exerciseSetIds: ["exercise-combining-1", "exercise-combining-2"],
    estimatedMinutes: 5,
    status: "shipped",
  },
  {
    id: "lesson-unit0-plural-patterns",
    title: "Plural Patterns You Will Keep Seeing",
    unitId: "unit-0",
    objective: "Recognize high-frequency singular and plural shifts in medical language.",
    whyItMatters: "Medical writing often keeps older plural endings that can confuse new learners.",
    prerequisiteLessonIds: ["lesson-unit0-word-parts"],
    introducesPartIds: [],
    introducesTermIds: [
      "term-diagnosis",
      "term-diagnoses",
      "term-vertebra",
      "term-vertebrae",
      "term-bacterium",
      "term-bacteria"
    ],
    reinforcesTermIds: [],
    exerciseSetIds: ["exercise-plurals-1", "exercise-plurals-2"],
    estimatedMinutes: 6,
    status: "shipped",
  },
  {
    id: "lesson-unit0-pronunciation-basics",
    title: "Pronunciation Patterns Worth Recognizing",
    unitId: "unit-0",
    objective: "Notice stress and common endings so familiar terms are easier to hear.",
    whyItMatters: "Recognition improves when learners can hear the term shape as well as read it.",
    prerequisiteLessonIds: ["lesson-unit0-combining-vowels"],
    introducesPartIds: [],
    introducesTermIds: [],
    reinforcesTermIds: ["term-cardiology", "term-neurology", "term-gastritis"],
    exerciseSetIds: ["exercise-pronunciation-1", "exercise-pronunciation-2"],
    estimatedMinutes: 5,
    status: "shipped",
  },
  {
    id: "lesson-unit1-common-suffixes",
    title: "High-Yield Suffixes: -itis and -logy",
    unitId: "unit-1",
    objective: "Decode common suffixes that point to inflammation and fields of study.",
    whyItMatters: "Common suffixes appear in both everyday terms and specialty names.",
    prerequisiteLessonIds: ["lesson-unit0-word-parts"],
    introducesPartIds: ["part-itis-suffix", "part-ology-suffix"],
    introducesTermIds: ["term-gastritis", "term-arthritis"],
    reinforcesTermIds: ["term-cardiology", "term-neurology"],
    exerciseSetIds: ["exercise-suffixes-1"],
    estimatedMinutes: 7,
    status: "shipped",
  },
  {
    id: "lesson-unit1-core-body-roots",
    title: "Core Body Roots You Will See Everywhere",
    unitId: "unit-1",
    objective: "Recognize high-yield roots for joints, skin, liver, kidneys, blood, and nerve pain.",
    whyItMatters: "A small set of organ and tissue roots unlocks many later body-system terms.",
    prerequisiteLessonIds: ["lesson-unit1-common-suffixes"],
    introducesPartIds: [
      "part-arthr-combining",
      "part-hemat-combining",
      "part-derm-combining",
      "part-hepat-combining",
      "part-nephr-combining",
      "part-algia-suffix"
    ],
    introducesTermIds: [
      "term-arthritis",
      "term-dermatitis",
      "term-hepatitis",
      "term-nephrology",
      "term-hematology",
      "term-neuralgia"
    ],
    reinforcesTermIds: ["term-gastritis", "term-cardiology", "term-neurology"],
    exerciseSetIds: ["exercise-body-roots-1", "exercise-body-roots-2"],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit1-common-prefixes",
    title: "Common Prefixes: Hyper- and Hypo-",
    unitId: "unit-1",
    objective: "Recognize common intensity prefixes that change meaning quickly.",
    whyItMatters: "A single prefix often flips whether a medical state is too much or too little.",
    prerequisiteLessonIds: ["lesson-unit1-common-suffixes"],
    introducesPartIds: ["part-hyper-prefix", "part-hypo-prefix"],
    introducesTermIds: ["term-hypertension", "term-hypotension"],
    reinforcesTermIds: ["term-gastritis", "term-arthritis"],
    exerciseSetIds: ["exercise-prefixes-1"],
    estimatedMinutes: 5,
    status: "shipped",
  },
  {
    id: "lesson-unit1-rate-prefixes",
    title: "Rate Prefixes: Tachy- and Brady-",
    unitId: "unit-1",
    objective: "Decode high-yield prefixes that signal faster or slower than normal.",
    whyItMatters: "Fast-versus-slow contrasts show up constantly in cardiovascular language.",
    prerequisiteLessonIds: ["lesson-unit1-common-prefixes"],
    introducesPartIds: ["part-tachy-prefix", "part-brady-prefix"],
    introducesTermIds: ["term-tachycardia", "term-bradycardia"],
    reinforcesTermIds: ["term-hypertension", "term-hypotension"],
    exerciseSetIds: ["exercise-rate-prefixes-1", "exercise-rate-prefixes-2"],
    estimatedMinutes: 6,
    status: "shipped",
  },
  {
    id: "lesson-unit1-procedure-language",
    title: "Procedure Language: Removal, Incision, Viewing, Record",
    unitId: "unit-1",
    objective: "Recognize procedure suffixes that describe what a clinician is doing.",
    whyItMatters: "Procedure language is one of the fastest ways to decode charts, consults, and specialty names.",
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    introducesPartIds: [
      "part-appendic-combining",
      "part-col-combining",
      "part-ectomy-suffix",
      "part-otomy-suffix",
      "part-scopy-suffix",
      "part-gram-suffix"
    ],
    introducesTermIds: [
      "term-appendectomy",
      "term-colonoscopy",
      "term-gastrotomy",
      "term-cardiogram"
    ],
    reinforcesTermIds: ["term-gastritis", "term-cardiology"],
    exerciseSetIds: ["exercise-procedures-1", "exercise-procedures-2"],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit2-cardiovascular-starter",
    title: "Cardiovascular Starter Terms",
    unitId: "unit-2",
    objective: "Recognize core vessel and artery terms in the first body-system module.",
    whyItMatters: "Cardiovascular language appears often and combines many high-yield roots already learned.",
    prerequisiteLessonIds: ["lesson-unit1-rate-prefixes", "lesson-unit1-procedure-language"],
    introducesPartIds: ["part-angi-combining", "part-arteri-combining", "part-ven-combining"],
    introducesTermIds: ["term-angiogram", "term-arteritis", "term-venogram"],
    reinforcesTermIds: [
      "term-hypertension",
      "term-hypotension",
      "term-tachycardia",
      "term-bradycardia",
      "term-cardiogram"
    ],
    exerciseSetIds: ["exercise-cardio-1", "exercise-cardio-2"],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit2-respiratory-airway-language",
    title: "Respiratory Airway Language",
    unitId: "unit-2",
    objective: "Recognize the most common roots for airways and lungs.",
    whyItMatters: "Learners hear these terms in infections, imaging, and respiratory procedure talk.",
    prerequisiteLessonIds: ["lesson-unit2-cardiovascular-starter", "lesson-unit1-procedure-language"],
    introducesPartIds: [
      "part-bronch-combining",
      "part-trache-combining",
      "part-pneum-combining",
      "part-pulmon-combining"
    ],
    introducesTermIds: [
      "term-bronchitis",
      "term-bronchoscopy",
      "term-tracheotomy",
      "term-pulmonary",
      "term-pneumonia"
    ],
    reinforcesTermIds: ["term-gastrotomy", "term-colonoscopy", "term-gastritis"],
    exerciseSetIds: [
      "exercise-respiratory-airway-1",
      "exercise-respiratory-airway-2",
      "exercise-respiratory-airway-3"
    ],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit2-respiratory-breathing-status",
    title: "Breathing Status and Oxygen Language",
    unitId: "unit-2",
    objective: "Decode common breathing-rate and oxygen-status terms.",
    whyItMatters: "These words show up in triage, charting, and common respiratory complaints.",
    prerequisiteLessonIds: [
      "lesson-unit2-respiratory-airway-language",
      "lesson-unit1-rate-prefixes",
      "lesson-unit1-common-prefixes"
    ],
    introducesPartIds: ["part-pnea-suffix", "part-dys-prefix", "part-oxia-suffix"],
    introducesTermIds: [
      "term-tachypnea",
      "term-bradypnea",
      "term-dyspnea",
      "term-hypoxia"
    ],
    reinforcesTermIds: ["term-tachycardia", "term-bradycardia", "term-hypotension"],
    exerciseSetIds: ["exercise-respiratory-status-1", "exercise-respiratory-status-2"],
    estimatedMinutes: 7,
    status: "shipped",
  },
  {
    id: "lesson-unit2-gastrointestinal-inflammation",
    title: "Gastrointestinal Inflammation Terms",
    unitId: "unit-2",
    objective: "Recognize inflammation terms across stomach, intestine, colon, and esophagus language.",
    whyItMatters: "Digestive complaints are common, and many GI words reuse a small set of predictable building blocks.",
    prerequisiteLessonIds: ["lesson-unit1-common-suffixes", "lesson-unit1-core-body-roots"],
    introducesPartIds: ["part-enter-combining", "part-esophag-combining"],
    introducesTermIds: [
      "term-enteritis",
      "term-gastroenteritis",
      "term-esophagitis",
      "term-colitis"
    ],
    reinforcesTermIds: ["term-gastritis", "term-hepatitis"],
    exerciseSetIds: ["exercise-gastro-inflammation-1", "exercise-gastro-inflammation-2"],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit2-gastrointestinal-procedures",
    title: "Gastrointestinal Procedure Language",
    unitId: "unit-2",
    objective: "Extend procedure decoding into gallbladder and digestive-system terms.",
    whyItMatters: "Procedure terms often sound intimidating, but they become readable once the organ root and action suffix are separated.",
    prerequisiteLessonIds: [
      "lesson-unit2-gastrointestinal-inflammation",
      "lesson-unit1-procedure-language"
    ],
    introducesPartIds: ["part-cholecyst-combining"],
    introducesTermIds: ["term-cholecystectomy"],
    reinforcesTermIds: ["term-colonoscopy", "term-appendectomy", "term-gastrotomy"],
    exerciseSetIds: ["exercise-gastro-procedures-1"],
    estimatedMinutes: 6,
    status: "shipped",
  },
  {
    id: "lesson-unit2-musculoskeletal-pain-and-repair",
    title: "Musculoskeletal Pain and Repair Language",
    unitId: "unit-2",
    objective: "Recognize common muscle and joint terms for pain, disorder, and repair.",
    whyItMatters: "Bone, joint, and muscle language shows up often in imaging, surgery, rehab, and everyday injury talk.",
    prerequisiteLessonIds: [
      "lesson-unit2-gastrointestinal-procedures",
      "lesson-unit1-core-body-roots"
    ],
    introducesPartIds: [
      "part-my-combining",
      "part-pathy-suffix",
      "part-plasty-suffix"
    ],
    introducesTermIds: [
      "term-myalgia",
      "term-myopathy",
      "term-arthropathy",
      "term-arthroplasty"
    ],
    reinforcesTermIds: ["term-arthritis", "term-neuralgia"],
    exerciseSetIds: [
      "exercise-musculoskeletal-1",
      "exercise-musculoskeletal-2",
      "exercise-musculoskeletal-3"
    ],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit2-renal-urinary-language",
    title: "Renal and Urinary Language",
    unitId: "unit-2",
    objective: "Decode common kidney, bladder, urine, and urinary-procedure terms.",
    whyItMatters: "Urinary terms appear in urgent care, lab results, imaging notes, and procedure instructions.",
    prerequisiteLessonIds: [
      "lesson-unit2-musculoskeletal-pain-and-repair",
      "lesson-unit1-procedure-language"
    ],
    introducesPartIds: ["part-cyst-combining", "part-uria-suffix"],
    introducesTermIds: [
      "term-nephritis",
      "term-cystitis",
      "term-cystoscopy",
      "term-hematuria"
    ],
    reinforcesTermIds: ["term-nephrology", "term-hematology", "term-colonoscopy"],
    exerciseSetIds: ["exercise-renal-1", "exercise-renal-2", "exercise-renal-3"],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit3-symptoms-signs-status-language",
    title: "Symptoms, Signs, and Status Language",
    unitId: "unit-3",
    objective: "Decode common clinical status words that describe complaints and observed findings.",
    whyItMatters: "These words show up in triage notes, assessment sections, and discharge instructions.",
    prerequisiteLessonIds: [
      "lesson-unit2-renal-urinary-language",
      "lesson-unit1-core-body-roots",
      "lesson-unit1-common-prefixes"
    ],
    introducesPartIds: ["part-megaly-suffix", "part-emia-suffix"],
    introducesTermIds: [
      "term-cardiomegaly",
      "term-hepatomegaly",
      "term-anemia",
      "term-edema"
    ],
    reinforcesTermIds: ["term-dyspnea", "term-hypoxia", "term-neuralgia"],
    exerciseSetIds: [
      "exercise-unit3-status-1",
      "exercise-unit3-status-2",
      "exercise-unit3-status-3"
    ],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit3-clinical-procedure-families",
    title: "Clinical Procedure Families Across Systems",
    unitId: "unit-3",
    objective: "Recognize repeating procedure and imaging patterns even when the organ root changes.",
    whyItMatters: "Charts and referral notes reuse the same action suffixes across specialties.",
    prerequisiteLessonIds: [
      "lesson-unit3-symptoms-signs-status-language",
      "lesson-unit2-musculoskeletal-pain-and-repair",
      "lesson-unit2-gastrointestinal-procedures"
    ],
    introducesPartIds: ["part-graphy-suffix"],
    introducesTermIds: [
      "term-angioplasty",
      "term-angiography",
      "term-cardiography",
      "term-arthroscopy",
      "term-osteotomy"
    ],
    reinforcesTermIds: [
      "term-bronchoscopy",
      "term-colonoscopy",
      "term-tracheotomy",
      "term-cholecystectomy",
      "term-angiogram"
    ],
    exerciseSetIds: [
      "exercise-unit3-procedures-1",
      "exercise-unit3-procedures-2",
      "exercise-unit3-procedures-3"
    ],
    estimatedMinutes: 9,
    status: "shipped",
  },
  {
    id: "lesson-unit4-scheduling-and-followup",
    title: "Scheduling and Follow-Up Language",
    unitId: "unit-4",
    objective: "Recognize the most common appointment and care-transition phrases.",
    whyItMatters: "Learners see this language in portals, paperwork, referral messages, and discharge planning.",
    prerequisiteLessonIds: ["lesson-unit3-clinical-procedure-families"],
    introducesPartIds: ["part-pre-prefix", "part-post-prefix"],
    introducesTermIds: [
      "term-follow-up",
      "term-outpatient",
      "term-inpatient",
      "term-preoperative",
      "term-postoperative"
    ],
    reinforcesTermIds: [
      "term-appendectomy",
      "term-bronchoscopy",
      "term-cholecystectomy"
    ],
    exerciseSetIds: [
      "exercise-unit4-scheduling-1",
      "exercise-unit4-scheduling-2",
      "exercise-unit4-scheduling-3"
    ],
    estimatedMinutes: 7,
    status: "shipped",
  },
  {
    id: "lesson-unit4-records-orders-and-authorization",
    title: "Records, Orders, and Authorization Language",
    unitId: "unit-4",
    objective: "Decode common record, approval, and take-home document phrases without forcing fake decomposition.",
    whyItMatters: "This language appears in portals, insurer notices, chart summaries, and office communication.",
    prerequisiteLessonIds: ["lesson-unit4-scheduling-and-followup"],
    introducesPartIds: ["part-contra-prefix"],
    introducesTermIds: [
      "term-prior-authorization",
      "term-referral",
      "term-documentation",
      "term-contraindication",
      "term-discharge-instructions"
    ],
    reinforcesTermIds: ["term-dyspnea", "term-hypoxia", "term-bronchoscopy"],
    exerciseSetIds: [
      "exercise-unit4-records-1",
      "exercise-unit4-records-2",
      "exercise-unit4-records-3"
    ],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit2-nervous-system-disorder-language",
    title: "Nervous System Disorder Language",
    unitId: "unit-2",
    objective: "Decode common nerve and brain disorder terms that recur in neurology and general clinical notes.",
    whyItMatters: "Nervous-system vocabulary often looks dense, but a few roots and suffixes make many high-yield terms readable.",
    prerequisiteLessonIds: [
      "lesson-unit2-renal-urinary-language",
      "lesson-unit2-musculoskeletal-pain-and-repair",
      "lesson-unit1-core-body-roots"
    ],
    introducesPartIds: [
      "part-encephal-combining",
      "part-hemi-prefix",
      "part-plegia-suffix"
    ],
    introducesTermIds: [
      "term-neuropathy",
      "term-encephalitis",
      "term-encephalopathy",
      "term-hemiplegia"
    ],
    reinforcesTermIds: ["term-neuralgia", "term-myopathy", "term-dyspnea"],
    exerciseSetIds: ["exercise-nervous-1", "exercise-nervous-2", "exercise-nervous-3"],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit3-chart-style-phrasing",
    title: "Chart-Style Phrasing",
    unitId: "unit-3",
    objective: "Recognize common note-section language and status phrasing that appear across clinical documentation.",
    whyItMatters: "Learners regularly meet note labels before they understand them, and these words are essential for reading real charts.",
    prerequisiteLessonIds: [
      "lesson-unit3-clinical-procedure-families",
      "lesson-unit2-nervous-system-disorder-language"
    ],
    introducesPartIds: [],
    introducesTermIds: [
      "term-assessment",
      "term-plan",
      "term-monitoring",
      "term-stable"
    ],
    reinforcesTermIds: ["term-edema", "term-dyspnea", "term-contraindication"],
    exerciseSetIds: [
      "exercise-unit3-chart-1",
      "exercise-unit3-chart-2",
      "exercise-unit3-chart-3"
    ],
    estimatedMinutes: 7,
    status: "shipped",
  },
  {
    id: "lesson-unit3-admissions-discharge-and-workflow",
    title: "Admissions, Discharge, and Workflow Language",
    unitId: "unit-3",
    objective: "Recognize the core workflow words that describe entering, moving through, and leaving care settings.",
    whyItMatters: "These words appear constantly in handoffs, discharge summaries, admission notes, and care transitions.",
    prerequisiteLessonIds: ["lesson-unit3-chart-style-phrasing"],
    introducesPartIds: [],
    introducesTermIds: [
      "term-admission",
      "term-discharge",
      "term-transfer",
      "term-consult"
    ],
    reinforcesTermIds: [
      "term-follow-up",
      "term-discharge-instructions",
      "term-outpatient",
      "term-inpatient"
    ],
    exerciseSetIds: [
      "exercise-unit3-workflow-1",
      "exercise-unit3-workflow-2",
      "exercise-unit3-workflow-3"
    ],
    estimatedMinutes: 7,
    status: "shipped",
  },
  {
    id: "lesson-unit4-intake-form-language",
    title: "Intake Form Language",
    unitId: "unit-4",
    objective: "Read the most common intake and registration form phrases without forcing fake decomposition.",
    whyItMatters: "Patients and learners see this paperwork early and often, so direct recognition matters.",
    prerequisiteLessonIds: [
      "lesson-unit4-records-orders-and-authorization",
      "lesson-unit3-admissions-discharge-and-workflow"
    ],
    introducesPartIds: [],
    introducesTermIds: [
      "term-chief-complaint",
      "term-medical-history",
      "term-medication-list",
      "term-allergies",
      "term-consent-form"
    ],
    reinforcesTermIds: ["term-documentation", "term-contraindication", "term-follow-up"],
    exerciseSetIds: [
      "exercise-unit4-intake-1",
      "exercise-unit4-intake-2",
      "exercise-unit4-intake-3"
    ],
    estimatedMinutes: 7,
    status: "shipped",
  },
  {
    id: "lesson-unit4-coverage-and-billing-language",
    title: "Coverage and Billing Language",
    unitId: "unit-4",
    objective: "Recognize the most common insurance and payment words that appear in portals, offices, and billing notices.",
    whyItMatters: "This language creates real friction for learners and patients, so the app should make it readable early.",
    prerequisiteLessonIds: ["lesson-unit4-intake-form-language"],
    introducesPartIds: [],
    introducesTermIds: [
      "term-coverage",
      "term-claim",
      "term-copay",
      "term-deductible",
      "term-denial"
    ],
    reinforcesTermIds: [
      "term-prior-authorization",
      "term-referral",
      "term-documentation"
    ],
    exerciseSetIds: [
      "exercise-unit4-billing-1",
      "exercise-unit4-billing-2",
      "exercise-unit4-billing-3"
    ],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit2-endocrine-and-glycemic-language",
    title: "Endocrine and Glycemic Language",
    unitId: "unit-2",
    objective: "Decode common thyroid and blood-sugar terms that show up in primary care, urgent care, and routine lab discussions.",
    whyItMatters: "Endocrine vocabulary becomes much easier once learners can separate sugar, thyroid, inflammation, and procedure patterns.",
    prerequisiteLessonIds: [
      "lesson-unit2-nervous-system-disorder-language",
      "lesson-unit1-common-prefixes",
      "lesson-unit1-common-suffixes",
      "lesson-unit1-procedure-language"
    ],
    introducesPartIds: ["part-glyc-combining", "part-thyroid-combining"],
    introducesTermIds: [
      "term-hyperglycemia",
      "term-hypoglycemia",
      "term-thyroiditis",
      "term-thyroidectomy",
      "term-insulin"
    ],
    reinforcesTermIds: ["term-hypertension", "term-hypotension"],
    exerciseSetIds: ["exercise-endocrine-1", "exercise-endocrine-2", "exercise-endocrine-3"],
    estimatedMinutes: 8,
    status: "shipped",
  },
  {
    id: "lesson-unit3-diagnostic-and-imaging-language",
    title: "Diagnostic and Imaging Language",
    unitId: "unit-3",
    objective: "Recognize high-frequency report and testing language without requiring specialist knowledge.",
    whyItMatters: "Learners often read report summaries and test labels before they know what the report is actually saying.",
    prerequisiteLessonIds: [
      "lesson-unit3-chart-style-phrasing",
      "lesson-unit3-clinical-procedure-families"
    ],
    introducesPartIds: [],
    introducesTermIds: [
      "term-biopsy",
      "term-specimen",
      "term-ultrasound",
      "term-findings",
      "term-impression"
    ],
    reinforcesTermIds: ["term-angiography", "term-cardiography", "term-assessment"],
    exerciseSetIds: [
      "exercise-unit3-diagnostics-1",
      "exercise-unit3-diagnostics-2",
      "exercise-unit3-diagnostics-3"
    ],
    estimatedMinutes: 7,
    status: "shipped",
  },
  {
    id: "lesson-unit3-medication-and-administration-basics",
    title: "Medication and Administration Basics",
    unitId: "unit-3",
    objective: "Recognize the most common route and medication-use words that appear in instructions and charts.",
    whyItMatters: "Medication language is constant in healthcare text, and a small core set removes a lot of confusion fast.",
    prerequisiteLessonIds: [
      "lesson-unit3-diagnostic-and-imaging-language",
      "lesson-unit2-cardiovascular-starter"
    ],
    introducesPartIds: ["part-intra-prefix"],
    introducesTermIds: [
      "term-oral",
      "term-topical",
      "term-intravenous",
      "term-injection",
      "term-dosage"
    ],
    reinforcesTermIds: ["term-plan", "term-monitoring"],
    exerciseSetIds: [
      "exercise-unit3-medications-1",
      "exercise-unit3-medications-2",
      "exercise-unit3-medications-3"
    ],
    estimatedMinutes: 7,
    status: "shipped",
  },
  {
    id: "lesson-unit4-portal-results-and-reminders",
    title: "Portal, Results, and Reminder Language",
    unitId: "unit-4",
    objective: "Read common portal messages, result notices, and reminder language with minimal friction.",
    whyItMatters: "This is where patients and learners encounter administrative wording in the wild, often as short portal notifications or message headers.",
    prerequisiteLessonIds: [
      "lesson-unit4-coverage-and-billing-language",
      "lesson-unit3-diagnostic-and-imaging-language"
    ],
    introducesPartIds: [],
    introducesTermIds: [
      "term-patient-portal",
      "term-test-results",
      "term-after-visit-summary",
      "term-refill-request",
      "term-appointment-reminder"
    ],
    reinforcesTermIds: [
      "term-follow-up",
      "term-documentation",
      "term-discharge-instructions"
    ],
    exerciseSetIds: [
      "exercise-unit4-portal-1",
      "exercise-unit4-portal-2",
      "exercise-unit4-portal-3"
    ],
    estimatedMinutes: 7,
    status: "shipped",
  }
];
