import type { Exercise, Lesson } from "../../types/content";

export const exercises: Exercise[] = [
  {
    id: "exercise-unit6-passage-b-imaging-1",
    type: "infer_meaning",
    prompt:
      "Chest imaging note: patient has cough and dyspnea. CT impression says stable postoperative changes, no acute infiltrate, and no new hypoxia. Plan: compare with prior scan, continue monitoring, and f/u with PCP if symptoms return. Which paraphrase best matches?",
    choices: [
      "The scan is mostly reassuring, but the team wants comparison with an earlier study and routine follow-up",
      "The scan shows an emergency finding that requires immediate surgery",
      "The note is mainly about billing because coverage was denied",
      "The patient is discharged without any further review or follow-up",
    ],
    answer:
      "The scan is mostly reassuring, but the team wants comparison with an earlier study and routine follow-up",
    linkedTermIds: [
      "term-dyspnea",
      "term-hypoxia",
      "term-impression",
      "term-postoperative",
      "term-stable",
      "term-compare-with-prior",
      "term-monitoring",
      "term-follow-up",
      "term-consult",
      "term-referral",
    ],
    linkedPartIds: [],
    linkedAbbreviationIds: ["abbr-ct", "abbr-fu", "abbr-pcp"],
  },
  {
    id: "exercise-unit6-passage-b-imaging-2",
    type: "cloze",
    prompt:
      "In that chest note, what does `impression` mean?",
    choices: [
      "the radiology team's bottom-line interpretation",
      "the patient's insurance estimate",
      "the medication list that was reviewed",
      "the follow-up appointment reminder",
    ],
    answer: "the radiology team's bottom-line interpretation",
    linkedTermIds: ["term-impression", "term-test-results", "term-documentation"],
    linkedPartIds: [],
    linkedAbbreviationIds: ["abbr-ct"],
  },
  {
    id: "exercise-unit6-passage-b-imaging-3",
    type: "infer_meaning",
    prompt:
      "Why does the note say to compare with the prior scan before deciding anything else?",
    choices: [
      "To see whether the finding is new or whether it matches an earlier baseline",
      "To switch the patient to a different portal account",
      "To cancel the follow-up visit because stable findings do not matter",
      "To rewrite the medication list before discharge",
    ],
    answer: "To see whether the finding is new or whether it matches an earlier baseline",
    linkedTermIds: ["term-compare-with-prior", "term-monitoring", "term-follow-up"],
    linkedPartIds: [],
    linkedAbbreviationIds: ["abbr-ct", "abbr-fu"],
  },
  {
    id: "exercise-unit6-passage-b-medrec-1",
    type: "infer_meaning",
    prompt:
      "Discharge note after bronchoscopy: medication list was reviewed, NPO was lifted, and the patient was told to take PO meds BID, use the inhaler PRN, and follow the AVS. The note says the patient is stable for discharge, should keep the prep instructions for the next study, and call the PCP if cough, fever, or SOB returns. Which paraphrase best matches?",
    choices: [
      "The patient is going home with a simplified medication plan and clear precautions if symptoms come back",
      "The patient is being admitted because the medication list is incomplete",
      "The note is mainly about insurance approval and a claim problem",
      "The patient should stop all medication until the specialist calls",
    ],
    answer:
      "The patient is going home with a simplified medication plan and clear precautions if symptoms come back",
    linkedTermIds: [
      "term-medication-list",
      "term-preparation-instructions",
      "term-after-visit-summary",
      "term-discharge-instructions",
      "term-bronchoscopy",
      "term-stable",
      "term-discharge",
      "term-follow-up",
      "term-referral",
    ],
    linkedPartIds: [],
    linkedAbbreviationIds: ["abbr-npo", "abbr-po", "abbr-bid", "abbr-prn", "abbr-avs", "abbr-pcp", "abbr-sob"],
  },
  {
    id: "exercise-unit6-passage-b-medrec-2",
    type: "cloze",
    prompt:
      "In that discharge note, what does `AVS` mean?",
    choices: [
      "after-visit summary",
      "acute vascular study",
      "approved visit sheet",
      "as needed symptom",
    ],
    answer: "after-visit summary",
    linkedTermIds: ["term-after-visit-summary", "term-discharge-instructions"],
    linkedPartIds: [],
    linkedAbbreviationIds: ["abbr-avs"],
  },
  {
    id: "exercise-unit6-passage-b-medrec-3",
    type: "infer_meaning",
    prompt:
      "Why does the note review the medication list before discharge?",
    choices: [
      "To reconcile what the patient actually takes with what the chart should show",
      "To delay the follow-up visit until billing is complete",
      "To replace the imaging impression with a new diagnosis",
      "To prove that the patient no longer needs any after-visit instructions",
    ],
    answer: "To reconcile what the patient actually takes with what the chart should show",
    linkedTermIds: ["term-medication-list", "term-documentation", "term-assessment", "term-plan"],
    linkedPartIds: [],
    linkedAbbreviationIds: ["abbr-po", "abbr-bid", "abbr-prn"],
  },
  {
    id: "exercise-unit6-passage-b-workflow-1",
    type: "infer_meaning",
    prompt:
      "Clinic workflow note: consult request sent to nephrology, documentation updated, and verification of DOB plus ROI completed. Prior-authorization notice is still pending, so the claim is on hold until coverage clears. Estimate and balance due were updated, an appt reminder was sent, and test results will post to the patient portal after the impression is signed. Which paraphrase best matches?",
    choices: [
      "The office is moving a chart through consult, authorization, and portal steps before final results and billing are released",
      "The patient has already been discharged and no further office work is needed",
      "The note means the imaging report is wrong and must be rewritten from scratch",
      "The office is only changing the medication list and has no role in the results",
    ],
    answer:
      "The office is moving a chart through consult, authorization, and portal steps before final results and billing are released",
    linkedTermIds: [
      "term-consult",
      "term-nephrology",
      "term-documentation",
      "term-verification",
      "term-prior-authorization-notice",
      "term-coverage",
      "term-claim",
      "term-estimate",
      "term-balance-due",
      "term-appointment-reminder",
      "term-test-results",
      "term-impression",
      "term-patient-portal",
    ],
    linkedPartIds: [],
    linkedAbbreviationIds: ["abbr-dob", "abbr-roi", "abbr-appt"],
  },
  {
    id: "exercise-unit6-passage-b-workflow-2",
    type: "cloze",
    prompt:
      "In that workflow note, what does `ROI` mean?",
    choices: [
      "release of information",
      "results on imaging",
      "routine office intake",
      "return on illness",
    ],
    answer: "release of information",
    linkedTermIds: ["term-documentation", "term-patient-portal", "term-verification"],
    linkedPartIds: [],
    linkedAbbreviationIds: ["abbr-roi"],
  },
  {
    id: "exercise-unit6-passage-b-workflow-3",
    type: "infer_meaning",
    prompt:
      "Why are the results held until the impression is signed off and authorization clears?",
    choices: [
      "Because the office is waiting on the final review and the administrative gate before releasing the next step",
      "Because the patient is too stable to ever receive results",
      "Because the medication list must be rewritten before any portal update",
      "Because the PCP is no longer allowed to see the chart",
    ],
    answer:
      "Because the office is waiting on the final review and the administrative gate before releasing the next step",
    linkedTermIds: [
      "term-prior-authorization-notice",
      "term-coverage",
      "term-claim",
      "term-impression",
      "term-test-results",
      "term-patient-portal",
      "term-follow-up",
    ],
    linkedPartIds: [],
    linkedAbbreviationIds: ["abbr-dob", "abbr-roi", "abbr-appt"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-unit6-passage-imaging-impression",
    title: "Imaging Impression and Recheck",
    unitId: "unit-6",
    objective: "Read a chest-imaging note and identify the actual next step.",
    whyItMatters: "Imaging notes often compress the finding, the interpretation, and the follow-up plan into one short line.",
    prerequisiteLessonIds: [
      "lesson-unit6-urgent-and-imaging-synthesis",
      "lesson-unit5-imaging-and-urgency-abbreviations",
    ],
    introducesPartIds: [],
    introducesTermIds: [],
    reinforcesTermIds: [
      "term-dyspnea",
      "term-hypoxia",
      "term-impression",
      "term-postoperative",
      "term-stable",
      "term-compare-with-prior",
      "term-monitoring",
      "term-follow-up",
      "term-consult",
      "term-referral",
      "term-documentation",
    ],
    reinforcesAbbreviationIds: ["abbr-ct", "abbr-fu", "abbr-pcp"],
    exerciseSetIds: [
      "exercise-unit6-passage-b-imaging-1",
      "exercise-unit6-passage-b-imaging-2",
      "exercise-unit6-passage-b-imaging-3",
    ],
    estimatedMinutes: 9,
    status: "drafted",
  },
  {
    id: "lesson-unit6-passage-med-reconciliation",
    title: "Medication Reconciliation and Precautions",
    unitId: "unit-6",
    objective: "Read a discharge-and-medication note without overreading the shorthand.",
    whyItMatters: "Medication notes often mix route, timing, and return precautions in a small space.",
    prerequisiteLessonIds: ["lesson-unit6-passage-imaging-impression"],
    introducesPartIds: [],
    introducesTermIds: [],
    reinforcesTermIds: [
      "term-medication-list",
      "term-preparation-instructions",
      "term-after-visit-summary",
      "term-discharge-instructions",
      "term-bronchoscopy",
      "term-stable",
      "term-discharge",
      "term-follow-up",
      "term-referral",
      "term-patient-portal",
    ],
    reinforcesAbbreviationIds: ["abbr-npo", "abbr-po", "abbr-bid", "abbr-prn", "abbr-avs", "abbr-pcp", "abbr-sob"],
    exerciseSetIds: [
      "exercise-unit6-passage-b-medrec-1",
      "exercise-unit6-passage-b-medrec-2",
      "exercise-unit6-passage-b-medrec-3",
    ],
    estimatedMinutes: 9,
    status: "drafted",
  },
  {
    id: "lesson-unit6-passage-consult-handoff",
    title: "Consult, Authorization, and Portal Workflow",
    unitId: "unit-6",
    objective: "Read a clinic workflow note that mixes consults, authorization, and portal updates.",
    whyItMatters: "These notes are where clinical language and administrative language overlap most tightly.",
    prerequisiteLessonIds: ["lesson-unit6-passage-med-reconciliation"],
    introducesPartIds: [],
    introducesTermIds: [],
    reinforcesTermIds: [
      "term-consult",
      "term-nephrology",
      "term-documentation",
      "term-verification",
      "term-prior-authorization-notice",
      "term-coverage",
      "term-claim",
      "term-estimate",
      "term-balance-due",
      "term-appointment-reminder",
      "term-test-results",
      "term-impression",
      "term-patient-portal",
      "term-follow-up",
    ],
    reinforcesAbbreviationIds: ["abbr-dob", "abbr-roi", "abbr-appt"],
    exerciseSetIds: [
      "exercise-unit6-passage-b-workflow-1",
      "exercise-unit6-passage-b-workflow-2",
      "exercise-unit6-passage-b-workflow-3",
    ],
    estimatedMinutes: 10,
    status: "drafted",
  },
];
