import type { Term } from "../../types/content";

export const lessonExpansionAppliedTerms: Term[] = [
  {
    id: "term-expansion-tracheitis",
    term: "tracheitis",
    normalizedTerm: "tracheitis",
    pronunciationText: "tray-kee-EYE-tis",
    plainMeaning: "inflammation of the trachea",
    shortDefinition: "irritation or inflammation affecting the windpipe",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-trache-combining", text: "trache/o", meaning: "trachea" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-trache-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-upper-airway-and-throat-language"],
    lessonIds: ["lesson-unit2-upper-airway-and-throat-language"],
    tags: ["unit-2", "respiratory", "upper-airway"],
  },
  {
    id: "term-expansion-stridor",
    term: "stridor",
    normalizedTerm: "stridor",
    pronunciationText: "STRY-dor",
    plainMeaning: "a harsh breathing sound",
    shortDefinition: "a high-pitched, rough sound made while breathing",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-upper-airway-and-throat-language"],
    lessonIds: ["lesson-unit2-upper-airway-and-throat-language"],
    tags: ["unit-2", "respiratory", "upper-airway"],
  },
  {
    id: "term-expansion-hoarseness",
    term: "hoarseness",
    normalizedTerm: "hoarseness",
    pronunciationText: "HORS-ness",
    plainMeaning: "a rough or strained voice",
    shortDefinition: "voice quality that sounds rough, weak, or strained",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-upper-airway-and-throat-language"],
    lessonIds: ["lesson-unit2-upper-airway-and-throat-language"],
    tags: ["unit-2", "respiratory", "upper-airway"],
  },
  {
    id: "term-expansion-cough",
    term: "cough",
    normalizedTerm: "cough",
    pronunciationText: "KAWF",
    plainMeaning: "a forceful clearing of the airways",
    shortDefinition: "an action that forcefully pushes air out of the lungs and throat",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-expansion-sputum",
    term: "sputum",
    normalizedTerm: "sputum",
    pronunciationText: "SPYOO-tum",
    plainMeaning: "mucus coughed up from the lungs or airways",
    shortDefinition: "material brought up from the lower airways when coughing",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-expansion-wheezing",
    term: "wheezing",
    normalizedTerm: "wheezing",
    pronunciationText: "WHEE-zing",
    plainMeaning: "a whistling breathing sound",
    shortDefinition: "a high-pitched sound during breathing, often from narrowed airways",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-expansion-shortness-of-breath",
    term: "shortness of breath",
    normalizedTerm: "shortness of breath",
    pronunciationText: "SHORT-ness uhv BRETH",
    plainMeaning: "trouble breathing comfortably",
    shortDefinition: "breathing that feels hard, shallow, or unsatisfying",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-expansion-respiratory-distress",
    term: "respiratory distress",
    normalizedTerm: "respiratory distress",
    pronunciationText: "res-puh-RAT-or-ee dih-STRES",
    plainMeaning: "serious trouble breathing",
    shortDefinition: "breathing difficulty serious enough to need close attention",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-expansion-apnea",
    term: "apnea",
    normalizedTerm: "apnea",
    pronunciationText: "AP-nee-uh",
    plainMeaning: "a pause in breathing",
    shortDefinition: "a temporary stop or pause in breathing",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-expansion-oxygen-saturation",
    term: "oxygen saturation",
    normalizedTerm: "oxygen saturation",
    pronunciationText: "OK-sih-jen sat-yuh-RAY-shun",
    plainMeaning: "how much oxygen is being carried in the blood",
    shortDefinition: "a measurement that shows how well oxygen is being carried",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory", "status"],
  },
  {
    id: "term-expansion-pleural-effusion",
    term: "pleural effusion",
    normalizedTerm: "pleural effusion",
    pronunciationText: "PLOOR-uhl ih-FYOO-zhun",
    plainMeaning: "extra fluid around the lungs",
    shortDefinition: "fluid buildup in the space around a lung",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-pleural-and-chest-language"],
    lessonIds: ["lesson-unit2-pleural-and-chest-language"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-expansion-pneumothorax",
    term: "pneumothorax",
    normalizedTerm: "pneumothorax",
    pronunciationText: "new-moh-THOR-aks",
    plainMeaning: "air around a lung",
    shortDefinition: "air that leaks into the space around the lung",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-pleural-and-chest-language"],
    lessonIds: ["lesson-unit2-pleural-and-chest-language"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-expansion-hemothorax",
    term: "hemothorax",
    normalizedTerm: "hemothorax",
    pronunciationText: "HEE-moh-THOR-aks",
    plainMeaning: "blood around a lung",
    shortDefinition: "blood that collects in the space around a lung",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-pleural-and-chest-language"],
    lessonIds: ["lesson-unit2-pleural-and-chest-language"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-expansion-chest-tube",
    term: "chest tube",
    normalizedTerm: "chest tube",
    pronunciationText: "chest toob",
    plainMeaning: "a tube placed in the chest to drain air or fluid",
    shortDefinition: "a drain inserted into the chest to remove air or fluid",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-pleural-and-chest-language"],
    lessonIds: ["lesson-unit2-pleural-and-chest-language"],
    tags: ["unit-2", "respiratory", "procedures"],
  },
  {
    id: "term-expansion-esophagoscopy",
    term: "esophagoscopy",
    normalizedTerm: "esophagoscopy",
    pronunciationText: "ee-sof-uh-GOS-koh-pee",
    plainMeaning: "viewing the esophagus with a scope",
    shortDefinition: "a scoped look into the esophagus",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-esophag-combining", text: "esophag/o", meaning: "esophagus" },
      { partId: "part-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" },
    ],
    prerequisiteIds: ["part-esophag-combining", "part-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-gastrointestinal-procedures"],
    lessonIds: ["lesson-unit2-gastrointestinal-procedures"],
    tags: ["unit-2", "gastrointestinal", "procedures"],
  },
  {
    id: "term-expansion-enteroscopy",
    term: "enteroscopy",
    normalizedTerm: "enteroscopy",
    pronunciationText: "EN-ter-OS-koh-pee",
    plainMeaning: "viewing the intestine with a scope",
    shortDefinition: "a scoped look into the intestine",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-enter-combining", text: "enter/o", meaning: "intestine" },
      { partId: "part-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" },
    ],
    prerequisiteIds: ["part-enter-combining", "part-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-gastrointestinal-procedures"],
    lessonIds: ["lesson-unit2-gastrointestinal-procedures"],
    tags: ["unit-2", "gastrointestinal", "procedures"],
  },
  {
    id: "term-expansion-sigmoidoscopy",
    term: "sigmoidoscopy",
    normalizedTerm: "sigmoidoscopy",
    pronunciationText: "sig-moy-DOS-koh-pee",
    plainMeaning: "viewing the sigmoid colon with a scope",
    shortDefinition: "a scope-based exam of the sigmoid colon",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-gastrointestinal-procedures"],
    lessonIds: ["lesson-unit2-gastrointestinal-procedures"],
    tags: ["unit-2", "gastrointestinal", "procedures"],
  },
  {
    id: "term-expansion-urinary-retention",
    term: "urinary retention",
    normalizedTerm: "urinary retention",
    pronunciationText: "YOOR-uh-nair-ee ree-TEN-shun",
    plainMeaning: "trouble emptying the bladder",
    shortDefinition: "inability to empty the bladder normally",
    bodySystem: "urinary",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-renal-urinary-language"],
    lessonIds: ["lesson-unit2-renal-urinary-language"],
    tags: ["unit-2", "urinary"],
  },
  {
    id: "term-expansion-catheterization",
    term: "catheterization",
    normalizedTerm: "catheterization",
    pronunciationText: "KATH-eh-ter-ih-ZAY-shun",
    plainMeaning: "placing a catheter into the body",
    shortDefinition: "the placement of a catheter for drainage, access, or monitoring",
    bodySystem: "urinary",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-renal-urinary-language"],
    lessonIds: ["lesson-unit2-renal-urinary-language"],
    tags: ["unit-2", "urinary", "procedures"],
  },
  {
    id: "term-expansion-bladder-scan",
    term: "bladder scan",
    normalizedTerm: "bladder scan",
    pronunciationText: "BLAD-er skan",
    plainMeaning: "an ultrasound check of the bladder",
    shortDefinition: "a scan used to estimate bladder volume or leftover urine",
    bodySystem: "urinary",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit2-renal-urinary-language"],
    lessonIds: ["lesson-unit2-renal-urinary-language"],
    tags: ["unit-2", "urinary", "testing"],
  },
  {
    id: "term-expansion-cystogram",
    term: "cystogram",
    normalizedTerm: "cystogram",
    pronunciationText: "SIS-toh-gram",
    plainMeaning: "an image or record of the bladder",
    shortDefinition: "an imaging record of the bladder",
    bodySystem: "urinary",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-cyst-combining", text: "cyst/o", meaning: "bladder or sac" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-cyst-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-renal-urinary-language"],
    lessonIds: ["lesson-unit2-renal-urinary-language"],
    tags: ["unit-2", "urinary", "testing"],
  },
  {
    id: "term-expansion-pending",
    term: "pending",
    normalizedTerm: "pending",
    pronunciationText: "PEN-ding",
    plainMeaning: "not finished yet",
    shortDefinition: "used for a result or order that is still in progress",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-results-and-interpretation-language"],
    lessonIds: ["lesson-unit3-results-and-interpretation-language"],
    tags: ["unit-3", "diagnostics", "results"],
  },
  {
    id: "term-expansion-preliminary",
    term: "preliminary",
    normalizedTerm: "preliminary",
    pronunciationText: "preh-LIM-ih-nair-ee",
    plainMeaning: "first or not final",
    shortDefinition: "used for an early version or first read before the final result",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-results-and-interpretation-language"],
    lessonIds: ["lesson-unit3-results-and-interpretation-language"],
    tags: ["unit-3", "diagnostics", "results"],
  },
  {
    id: "term-expansion-final",
    term: "final",
    normalizedTerm: "final",
    pronunciationText: "FY-nul",
    plainMeaning: "complete and official",
    shortDefinition: "used for the completed version of a result or report",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-results-and-interpretation-language"],
    lessonIds: ["lesson-unit3-results-and-interpretation-language"],
    tags: ["unit-3", "diagnostics", "results"],
  },
  {
    id: "term-expansion-critical",
    term: "critical",
    normalizedTerm: "critical",
    pronunciationText: "KRIT-ih-kul",
    plainMeaning: "serious enough to need urgent attention",
    shortDefinition: "used for a result or condition that needs prompt attention",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-results-and-interpretation-language"],
    lessonIds: ["lesson-unit3-results-and-interpretation-language"],
    tags: ["unit-3", "diagnostics", "results"],
  },
  {
    id: "term-expansion-unchanged",
    term: "unchanged",
    normalizedTerm: "unchanged",
    pronunciationText: "un-CHAYNJD",
    plainMeaning: "not different from before",
    shortDefinition: "used when a finding has not changed compared with earlier results",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-results-and-interpretation-language"],
    lessonIds: ["lesson-unit3-results-and-interpretation-language"],
    tags: ["unit-3", "diagnostics", "results"],
  },
  {
    id: "term-expansion-worsening",
    term: "worsening",
    normalizedTerm: "worsening",
    pronunciationText: "WUR-sen-ing",
    plainMeaning: "getting worse",
    shortDefinition: "used when a finding or symptom is becoming more severe",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-results-and-interpretation-language"],
    lessonIds: ["lesson-unit3-results-and-interpretation-language"],
    tags: ["unit-3", "diagnostics", "results"],
  },
  {
    id: "term-expansion-consistent-with",
    term: "consistent with",
    normalizedTerm: "consistent with",
    pronunciationText: "kun-SIS-tent with",
    plainMeaning: "fits the pattern of",
    shortDefinition: "used when a finding matches or fits a suspected condition",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-report-comparison-language"],
    lessonIds: ["lesson-unit3-report-comparison-language"],
    tags: ["unit-3", "diagnostics", "comparison"],
  },
  {
    id: "term-expansion-compatible-with",
    term: "compatible with",
    normalizedTerm: "compatible with",
    pronunciationText: "kom-PAT-ih-bul with",
    plainMeaning: "can be explained by",
    shortDefinition: "used when a result can fit the expected diagnosis or condition",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-report-comparison-language"],
    lessonIds: ["lesson-unit3-report-comparison-language"],
    tags: ["unit-3", "diagnostics", "comparison"],
  },
  {
    id: "term-expansion-suggestive-of",
    term: "suggestive of",
    normalizedTerm: "suggestive of",
    pronunciationText: "suh-JES-tiv uhv",
    plainMeaning: "points toward",
    shortDefinition: "used when a finding points toward a likely explanation",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-report-comparison-language"],
    lessonIds: ["lesson-unit3-report-comparison-language"],
    tags: ["unit-3", "diagnostics", "comparison"],
  },
  {
    id: "term-expansion-cannot-exclude",
    term: "cannot exclude",
    normalizedTerm: "cannot exclude",
    pronunciationText: "KAN-not ex-KLOOD",
    plainMeaning: "cannot rule out",
    shortDefinition: "used when a finding cannot be ruled out with certainty",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit3-report-comparison-language"],
    lessonIds: ["lesson-unit3-report-comparison-language"],
    tags: ["unit-3", "diagnostics", "comparison"],
  },
  {
    id: "term-expansion-appointment",
    term: "appointment",
    normalizedTerm: "appointment",
    pronunciationText: "uh-POINT-ment",
    plainMeaning: "a scheduled visit",
    shortDefinition: "a planned time to see a clinician or attend a visit",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-scheduling-and-followup"],
    lessonIds: ["lesson-unit4-scheduling-and-followup"],
    tags: ["unit-4", "administrative", "scheduling"],
  },
  {
    id: "term-expansion-cancellation",
    term: "cancellation",
    normalizedTerm: "cancellation",
    pronunciationText: "kan-suh-LAY-shun",
    plainMeaning: "a visit or service being called off",
    shortDefinition: "the act of ending a planned appointment or service before it happens",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-scheduling-and-followup"],
    lessonIds: ["lesson-unit4-scheduling-and-followup"],
    tags: ["unit-4", "administrative", "scheduling"],
  },
  {
    id: "term-expansion-waitlist",
    term: "waitlist",
    normalizedTerm: "waitlist",
    pronunciationText: "WAYT-list",
    plainMeaning: "a list of people waiting for an opening",
    shortDefinition: "a list used when a visit is not available yet but a slot may open later",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-scheduling-and-followup"],
    lessonIds: ["lesson-unit4-scheduling-and-followup"],
    tags: ["unit-4", "administrative", "scheduling"],
  },
  {
    id: "term-expansion-confirmation",
    term: "confirmation",
    normalizedTerm: "confirmation",
    pronunciationText: "kon-fer-MAY-shun",
    plainMeaning: "a notice that something is set or verified",
    shortDefinition: "a message or notice that an appointment or detail has been verified",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-scheduling-and-followup"],
    lessonIds: ["lesson-unit4-scheduling-and-followup"],
    tags: ["unit-4", "administrative", "scheduling"],
  },
  {
    id: "term-expansion-authorization",
    term: "authorization",
    normalizedTerm: "authorization",
    pronunciationText: "or-ih-zay-ZAY-shun",
    plainMeaning: "approval before a service or payment",
    shortDefinition: "approval needed before a service, medicine, or payment can proceed",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-records-orders-and-authorization"],
    lessonIds: ["lesson-unit4-records-orders-and-authorization"],
    tags: ["unit-4", "administrative", "workflow"],
  },
  {
    id: "term-expansion-release-of-information",
    term: "release of information",
    normalizedTerm: "release of information",
    pronunciationText: "ree-LEES uhv in-fer-MAY-shun",
    plainMeaning: "permission to send records or details",
    shortDefinition: "a permission process for sharing medical records or other information",
    bodySystem: "administrative",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-records-orders-and-authorization"],
    lessonIds: ["lesson-unit4-records-orders-and-authorization"],
    tags: ["unit-4", "administrative", "records"],
  },
  {
    id: "term-expansion-order-status",
    term: "order status",
    normalizedTerm: "order status",
    pronunciationText: "OR-der STAY-tus",
    plainMeaning: "the current state of a request or order",
    shortDefinition: "the step or state a request is currently in",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-records-orders-and-authorization"],
    lessonIds: ["lesson-unit4-records-orders-and-authorization"],
    tags: ["unit-4", "administrative", "records"],
  },
  {
    id: "term-expansion-premium",
    term: "premium",
    normalizedTerm: "premium",
    pronunciationText: "PREE-mee-um",
    plainMeaning: "the regular insurance payment",
    shortDefinition: "the amount paid regularly to keep an insurance plan active",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-coverage-and-billing-language"],
    lessonIds: ["lesson-unit4-coverage-and-billing-language"],
    tags: ["unit-4", "administrative", "billing"],
  },
  {
    id: "term-expansion-member-id",
    term: "member ID",
    normalizedTerm: "member id",
    pronunciationText: "MEM-ber eye-DEE",
    plainMeaning: "the insurance member number",
    shortDefinition: "the identifying number used for an insurance member or policy",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-coverage-and-billing-language"],
    lessonIds: ["lesson-unit4-coverage-and-billing-language"],
    tags: ["unit-4", "administrative", "billing"],
  },
  {
    id: "term-expansion-out-of-pocket-maximum",
    term: "out-of-pocket maximum",
    normalizedTerm: "out-of-pocket maximum",
    pronunciationText: "out-uhv-POK-it MAK-suh-mum",
    plainMeaning: "the most a person pays in a year before the plan covers more",
    shortDefinition: "the yearly cap on what the patient pays themselves",
    bodySystem: "administrative",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-coverage-and-billing-language"],
    lessonIds: ["lesson-unit4-coverage-and-billing-language"],
    tags: ["unit-4", "administrative", "billing"],
  },
  {
    id: "term-expansion-benefit",
    term: "benefit",
    normalizedTerm: "benefit",
    pronunciationText: "BEN-uh-fit",
    plainMeaning: "a service or cost the plan covers",
    shortDefinition: "a covered service, feature, or payment the plan includes",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-coverage-and-billing-language"],
    lessonIds: ["lesson-unit4-coverage-and-billing-language"],
    tags: ["unit-4", "administrative", "billing"],
  },
  {
    id: "term-expansion-notification",
    term: "notification",
    normalizedTerm: "notification",
    pronunciationText: "noh-tih-fih-KAY-shun",
    plainMeaning: "a notice sent through a system or portal",
    shortDefinition: "a message or notice that something has happened or needs attention",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-portal-results-and-reminders"],
    lessonIds: ["lesson-unit4-portal-results-and-reminders"],
    tags: ["unit-4", "administrative", "portal"],
  },
  {
    id: "term-expansion-message",
    term: "message",
    normalizedTerm: "message",
    pronunciationText: "MESS-ij",
    plainMeaning: "a written or sent communication",
    shortDefinition: "a message sent through a portal, office system, or written notice",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-portal-results-and-reminders"],
    lessonIds: ["lesson-unit4-portal-results-and-reminders"],
    tags: ["unit-4", "administrative", "portal"],
  },
  {
    id: "term-expansion-result-note",
    term: "result note",
    normalizedTerm: "result note",
    pronunciationText: "rih-ZULT noht",
    plainMeaning: "a note that summarizes a result",
    shortDefinition: "a short note that explains the meaning or status of a result",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-portal-results-and-reminders"],
    lessonIds: ["lesson-unit4-portal-results-and-reminders"],
    tags: ["unit-4", "administrative", "portal"],
  },
  {
    id: "term-expansion-posted-result",
    term: "posted result",
    normalizedTerm: "posted result",
    pronunciationText: "POH-stid rih-ZULT",
    plainMeaning: "a result that has been released into the portal",
    shortDefinition: "a result that has been published or made available for viewing",
    bodySystem: "administrative",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit4-portal-results-and-reminders"],
    lessonIds: ["lesson-unit4-portal-results-and-reminders"],
    tags: ["unit-4", "administrative", "portal"],
  },
];
