import type { Term } from "../../types/content";

export const lessonExpansionCoreTerms: Term[] = [
  {
    id: "term-osteology",
    term: "osteology",
    normalizedTerm: "osteology",
    pronunciationText: "os-tee-OL-uh-jee",
    plainMeaning: "the study of bone",
    shortDefinition: "the branch of anatomy focused on bone structure",
    bodySystem: "musculoskeletal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-osteo-combining", text: "oste/o", meaning: "bone" },
      { partId: "part-ology-suffix", text: "-logy", meaning: "study of" },
    ],
    prerequisiteIds: ["part-osteo-combining", "part-ology-suffix"],
    prerequisiteLessonIds: ["lesson-unit0-word-parts"],
    lessonIds: ["lesson-unit0-word-parts", "lesson-unit0-combining-vowels"],
    tags: ["unit-0", "decoding"],
  },
  {
    id: "term-osteitis",
    term: "osteitis",
    normalizedTerm: "osteitis",
    pronunciationText: "os-tee-EYE-tis",
    plainMeaning: "bone inflammation",
    shortDefinition: "inflammation affecting bone tissue",
    bodySystem: "musculoskeletal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-osteo-combining", text: "oste/o", meaning: "bone" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-osteo-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-common-suffixes"],
    lessonIds: ["lesson-unit1-common-suffixes"],
    tags: ["unit-1", "suffix", "roots"],
  },
  {
    id: "term-carditis",
    term: "carditis",
    normalizedTerm: "carditis",
    pronunciationText: "kar-DYE-tis",
    plainMeaning: "heart inflammation",
    shortDefinition: "inflammation affecting the heart",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-cardi-root", text: "cardi", meaning: "heart" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-cardi-root", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-common-suffixes"],
    lessonIds: ["lesson-unit1-common-suffixes"],
    tags: ["unit-1", "suffix", "roots"],
  },
  {
    id: "term-arthralgia",
    term: "arthralgia",
    normalizedTerm: "arthralgia",
    pronunciationText: "ar-THRAL-jee-uh",
    plainMeaning: "joint pain",
    shortDefinition: "pain in a joint",
    bodySystem: "musculoskeletal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-arthr-combining", text: "arthr/o", meaning: "joint" },
      { partId: "part-algia-suffix", text: "-algia", meaning: "pain" },
    ],
    prerequisiteIds: ["part-arthr-combining", "part-algia-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    lessonIds: ["lesson-unit1-core-body-roots"],
    tags: ["unit-1", "roots", "condition"],
  },
  {
    id: "term-gastralgia",
    term: "gastralgia",
    normalizedTerm: "gastralgia",
    pronunciationText: "gas-TRAL-jee-uh",
    plainMeaning: "stomach pain",
    shortDefinition: "pain in the stomach area",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-gastr-root", text: "gastr", meaning: "stomach" },
      { partId: "part-algia-suffix", text: "-algia", meaning: "pain" },
    ],
    prerequisiteIds: ["part-gastr-root", "part-algia-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    lessonIds: ["lesson-unit1-core-body-roots"],
    tags: ["unit-1", "roots", "condition"],
  },
  {
    id: "term-hepatology",
    term: "hepatology",
    normalizedTerm: "hepatology",
    pronunciationText: "hep-uh-TOL-uh-jee",
    plainMeaning: "the study of the liver",
    shortDefinition: "the medical study or specialty focused on the liver",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-hepat-combining", text: "hepat/o", meaning: "liver" },
      { partId: "part-ology-suffix", text: "-logy", meaning: "study of" },
    ],
    prerequisiteIds: ["part-hepat-combining", "part-ology-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    lessonIds: ["lesson-unit1-core-body-roots"],
    tags: ["unit-1", "roots", "specialty"],
  },
  {
    id: "term-nephroma",
    term: "nephroma",
    normalizedTerm: "nephroma",
    pronunciationText: "neh-FROH-muh",
    plainMeaning: "kidney mass or tumor",
    shortDefinition: "a mass or tumor involving the kidney",
    bodySystem: "urinary",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-nephr-combining", text: "nephr/o", meaning: "kidney" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor" },
    ],
    prerequisiteIds: ["part-nephr-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-condition-suffixes"],
    lessonIds: ["lesson-unit1-condition-suffixes"],
    tags: ["unit-1", "suffix", "condition"],
  },
  {
    id: "term-gastrectomy",
    term: "gastrectomy",
    normalizedTerm: "gastrectomy",
    pronunciationText: "gas-TREK-tuh-mee",
    plainMeaning: "surgical removal of the stomach",
    shortDefinition: "an operation to remove part or all of the stomach",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-gastr-root", text: "gastr", meaning: "stomach" },
      { partId: "part-ectomy-suffix", text: "-ectomy", meaning: "surgical removal" },
    ],
    prerequisiteIds: ["part-gastr-root", "part-ectomy-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-procedure-language"],
    lessonIds: ["lesson-unit1-procedure-language"],
    tags: ["unit-1", "procedures"],
  },
  {
    id: "term-colectomy",
    term: "colectomy",
    normalizedTerm: "colectomy",
    pronunciationText: "koh-LEK-tuh-mee",
    plainMeaning: "surgical removal of the colon",
    shortDefinition: "an operation to remove part or all of the colon",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-col-combining", text: "col/o", meaning: "colon" },
      { partId: "part-ectomy-suffix", text: "-ectomy", meaning: "surgical removal" },
    ],
    prerequisiteIds: ["part-col-combining", "part-ectomy-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-procedure-language"],
    lessonIds: ["lesson-unit1-procedure-language"],
    tags: ["unit-1", "procedures"],
  },
  {
    id: "term-colotomy",
    term: "colotomy",
    normalizedTerm: "colotomy",
    pronunciationText: "koh-LOT-uh-mee",
    plainMeaning: "incision into the colon",
    shortDefinition: "a surgical cut into the colon",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-col-combining", text: "col/o", meaning: "colon" },
      { partId: "part-otomy-suffix", text: "-otomy", meaning: "incision into" },
    ],
    prerequisiteIds: ["part-col-combining", "part-otomy-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-procedure-language"],
    lessonIds: ["lesson-unit1-procedure-language"],
    tags: ["unit-1", "procedures"],
  },
  {
    id: "term-arthrotomy",
    term: "arthrotomy",
    normalizedTerm: "arthrotomy",
    pronunciationText: "ar-THROT-uh-mee",
    plainMeaning: "incision into a joint",
    shortDefinition: "a surgical cut into a joint",
    bodySystem: "musculoskeletal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-arthr-combining", text: "arthr/o", meaning: "joint" },
      { partId: "part-otomy-suffix", text: "-otomy", meaning: "incision into" },
    ],
    prerequisiteIds: ["part-arthr-combining", "part-otomy-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-procedure-language"],
    lessonIds: ["lesson-unit1-procedure-language"],
    tags: ["unit-1", "procedures"],
  },
  {
    id: "term-nephrotomy",
    term: "nephrotomy",
    normalizedTerm: "nephrotomy",
    pronunciationText: "neh-FROT-uh-mee",
    plainMeaning: "incision into the kidney",
    shortDefinition: "a surgical cut into the kidney",
    bodySystem: "urinary",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-nephr-combining", text: "nephr/o", meaning: "kidney" },
      { partId: "part-otomy-suffix", text: "-otomy", meaning: "incision into" },
    ],
    prerequisiteIds: ["part-nephr-combining", "part-otomy-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-procedure-language"],
    lessonIds: ["lesson-unit1-procedure-language"],
    tags: ["unit-1", "procedures"],
  },
  {
    id: "term-tachycardic",
    term: "tachycardic",
    normalizedTerm: "tachycardic",
    pronunciationText: "tak-ee-KAR-dik",
    plainMeaning: "having a fast heart rate",
    shortDefinition: "describing a heart rate that is too fast",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "partial",
    parts: [
      { partId: "part-tachy-prefix", text: "tachy-", meaning: "fast" },
      { partId: "part-cardi-root", text: "cardi", meaning: "heart" },
    ],
    prerequisiteIds: ["part-tachy-prefix", "part-cardi-root"],
    prerequisiteLessonIds: ["lesson-unit1-rate-prefixes"],
    lessonIds: ["lesson-unit1-rate-prefixes"],
    tags: ["unit-1", "prefix", "cardiovascular"],
  },
  {
    id: "term-bradycardic",
    term: "bradycardic",
    normalizedTerm: "bradycardic",
    pronunciationText: "bray-dee-KAR-dik",
    plainMeaning: "having a slow heart rate",
    shortDefinition: "describing a heart rate that is too slow",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "partial",
    parts: [
      { partId: "part-brady-prefix", text: "brady-", meaning: "slow" },
      { partId: "part-cardi-root", text: "cardi", meaning: "heart" },
    ],
    prerequisiteIds: ["part-brady-prefix", "part-cardi-root"],
    prerequisiteLessonIds: ["lesson-unit1-rate-prefixes"],
    lessonIds: ["lesson-unit1-rate-prefixes"],
    tags: ["unit-1", "prefix", "cardiovascular"],
  },
];
