import type { Term } from "../../types/content";

export const terms: Term[] = [
  {
    id: "term-batch-growthmass-metaplastic",
    term: "metaplastic",
    normalizedTerm: "metaplastic",
    pronunciationText: "meh-tuh-PLAS-tik",
    plainMeaning: "showing a changed tissue type",
    shortDefinition: "relating to a tissue that has changed from one mature cell type to another",
    bodySystem: "pathology",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-batch-inflammatory-meta-prefix", text: "meta-", meaning: "change; after" },
      { partId: "part-plasia-suffix", text: "-plasia", meaning: "formation; growth" },
      { partId: "part-batch-definflam-ic-suffix", text: "-ic", meaning: "pertaining to" },
    ],
    prerequisiteIds: [
      "part-batch-inflammatory-meta-prefix",
      "part-plasia-suffix",
      "part-batch-definflam-ic-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-growthmass-formation-shifts"],
    lessonIds: ["lesson-batch-growthmass-formation-shifts"],
    tags: ["unit-1", "growth-family", "pathology"],
  },
  {
    id: "term-batch-growthmass-neoplastic",
    term: "neoplastic",
    normalizedTerm: "neoplastic",
    pronunciationText: "nee-oh-PLAS-tik",
    plainMeaning: "pertaining to new abnormal growth",
    shortDefinition: "relating to a neoplasm or abnormal tissue growth",
    bodySystem: "oncologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-batch-inflammatory-neo-prefix", text: "neo-", meaning: "new" },
      { partId: "part-batch-growthmass-plasm-combining", text: "plasm/o", meaning: "formation; growth" },
      { partId: "part-batch-definflam-ic-suffix", text: "-ic", meaning: "pertaining to" },
    ],
    prerequisiteIds: [
      "part-batch-inflammatory-neo-prefix",
      "part-batch-growthmass-plasm-combining",
      "part-batch-definflam-ic-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-growthmass-formation-shifts"],
    lessonIds: ["lesson-batch-growthmass-formation-shifts"],
    tags: ["unit-1", "growth-family", "oncologic"],
  },
  {
    id: "term-batch-growthmass-hyperplastic",
    term: "hyperplastic",
    normalizedTerm: "hyperplastic",
    pronunciationText: "hy-per-PLAS-tik",
    plainMeaning: "showing too much tissue growth",
    shortDefinition: "relating to excessive cell or tissue growth",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-hyper-prefix", text: "hyper-", meaning: "too much; above normal" },
      { partId: "part-plasia-suffix", text: "-plasia", meaning: "formation; growth" },
      { partId: "part-batch-definflam-ic-suffix", text: "-ic", meaning: "pertaining to" },
    ],
    prerequisiteIds: ["part-hyper-prefix", "part-plasia-suffix", "part-batch-definflam-ic-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-formation-shifts"],
    lessonIds: ["lesson-batch-growthmass-formation-shifts"],
    tags: ["unit-1", "growth-family", "adjective-family"],
  },
  {
    id: "term-batch-growthmass-hypoplastic",
    term: "hypoplastic",
    normalizedTerm: "hypoplastic",
    pronunciationText: "hy-poh-PLAS-tik",
    plainMeaning: "showing too little tissue growth",
    shortDefinition: "relating to incomplete or underdeveloped tissue growth",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-hypo-prefix", text: "hypo-", meaning: "too little; below normal" },
      { partId: "part-plasia-suffix", text: "-plasia", meaning: "formation; growth" },
      { partId: "part-batch-definflam-ic-suffix", text: "-ic", meaning: "pertaining to" },
    ],
    prerequisiteIds: ["part-hypo-prefix", "part-plasia-suffix", "part-batch-definflam-ic-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-formation-shifts"],
    lessonIds: ["lesson-batch-growthmass-formation-shifts"],
    tags: ["unit-1", "growth-family", "adjective-family"],
  },
  {
    id: "term-batch-growthmass-dysplastic",
    term: "dysplastic",
    normalizedTerm: "dysplastic",
    pronunciationText: "dis-PLAS-tik",
    plainMeaning: "showing abnormal tissue growth",
    shortDefinition: "relating to disordered or abnormal tissue development",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-dys-prefix", text: "dys-", meaning: "bad; difficult; abnormal" },
      { partId: "part-plasia-suffix", text: "-plasia", meaning: "formation; growth" },
      { partId: "part-batch-definflam-ic-suffix", text: "-ic", meaning: "pertaining to" },
    ],
    prerequisiteIds: ["part-dys-prefix", "part-plasia-suffix", "part-batch-definflam-ic-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-formation-shifts"],
    lessonIds: ["lesson-batch-growthmass-formation-shifts"],
    tags: ["unit-1", "growth-family", "adjective-family"],
  },
  {
    id: "term-batch-growthmass-adenoma",
    term: "adenoma",
    normalizedTerm: "adenoma",
    pronunciationText: "ad-eh-NOH-muh",
    plainMeaning: "gland tumor",
    shortDefinition: "a tumor that arises from glandular tissue",
    bodySystem: "oncologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-aden-combining", text: "aden/o", meaning: "gland; node" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-aden-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-masses"],
    lessonIds: ["lesson-batch-growthmass-common-masses"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-adenocarcinoma",
    term: "adenocarcinoma",
    normalizedTerm: "adenocarcinoma",
    pronunciationText: "ad-eh-noh-kar-sih-NOH-muh",
    plainMeaning: "gland-forming cancer",
    shortDefinition: "a carcinoma that develops from glandular tissue",
    bodySystem: "oncologic",
    difficulty: 3,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-aden-combining", text: "aden/o", meaning: "gland; node" },
      { partId: "part-carcin-combining", text: "carcin/o", meaning: "cancer" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-aden-combining", "part-carcin-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-masses"],
    lessonIds: ["lesson-batch-growthmass-common-masses"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-melanoma",
    term: "melanoma",
    normalizedTerm: "melanoma",
    pronunciationText: "mel-uh-NOH-muh",
    plainMeaning: "dark-pigment tumor",
    shortDefinition: "a usually malignant tumor of pigment-forming cells",
    bodySystem: "oncologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-melan-combining", text: "melan/o", meaning: "black; dark pigment" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-growthmass-melan-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-masses"],
    lessonIds: ["lesson-batch-growthmass-common-masses"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-lipoma",
    term: "lipoma",
    normalizedTerm: "lipoma",
    pronunciationText: "lih-POH-muh",
    plainMeaning: "fatty tumor",
    shortDefinition: "a benign tumor made of fat tissue",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-lip-combining", text: "lip/o", meaning: "fat" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-growthmass-lip-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-masses"],
    lessonIds: ["lesson-batch-growthmass-common-masses"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-myeloma",
    term: "myeloma",
    normalizedTerm: "myeloma",
    pronunciationText: "my-eh-LOH-muh",
    plainMeaning: "marrow tumor",
    shortDefinition: "a tumor of bone marrow cells, often used for blood-cancer contexts",
    bodySystem: "hematologic",
    difficulty: 3,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-myel-combining", text: "myel/o", meaning: "marrow; spinal cord" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-growthmass-myel-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-masses"],
    lessonIds: ["lesson-batch-growthmass-common-masses"],
    tags: ["unit-1", "growth-family", "hematologic"],
  },
  {
    id: "term-batch-growthmass-granuloma",
    term: "granuloma",
    normalizedTerm: "granuloma",
    pronunciationText: "gran-yoo-LOH-muh",
    plainMeaning: "small grain-like inflammatory lump",
    shortDefinition: "a small nodular inflammatory mass formed by immune cells",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-granul-combining", text: "granul/o", meaning: "granule; small grain-like lump" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-growthmass-granul-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-tissue-masses"],
    lessonIds: ["lesson-batch-growthmass-tissue-masses"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-fibroma",
    term: "fibroma",
    normalizedTerm: "fibroma",
    pronunciationText: "fye-BROH-muh",
    plainMeaning: "fibrous tissue tumor",
    shortDefinition: "a benign tumor made mainly of fibrous tissue",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-fibr-combining", text: "fibr/o", meaning: "fiber; fibrous tissue" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-growthmass-fibr-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-tissue-masses"],
    lessonIds: ["lesson-batch-growthmass-tissue-masses"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-glioma",
    term: "glioma",
    normalizedTerm: "glioma",
    pronunciationText: "glee-OH-muh",
    plainMeaning: "glial-tissue tumor",
    shortDefinition: "a tumor that arises from glial support tissue in the nervous system",
    bodySystem: "neurologic",
    difficulty: 3,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-gli-combining", text: "gli/o", meaning: "glial tissue; glue-like support tissue" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-growthmass-gli-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-tissue-masses"],
    lessonIds: ["lesson-batch-growthmass-tissue-masses"],
    tags: ["unit-1", "growth-family", "neurologic"],
  },
  {
    id: "term-batch-growthmass-papilloma",
    term: "papilloma",
    normalizedTerm: "papilloma",
    pronunciationText: "pap-ih-LOH-muh",
    plainMeaning: "papilla-like growth",
    shortDefinition: "a benign epithelial tumor that forms a small projecting growth",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-papill-combining", text: "papill/o", meaning: "nipple-like projection; papilla" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-growthmass-papill-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-tissue-masses"],
    lessonIds: ["lesson-batch-growthmass-tissue-masses"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-sarcoma",
    term: "sarcoma",
    normalizedTerm: "sarcoma",
    pronunciationText: "sar-KOH-muh",
    plainMeaning: "connective-tissue cancer",
    shortDefinition: "a malignant tumor that arises from connective tissue such as bone or muscle",
    bodySystem: "oncologic",
    difficulty: 3,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-sarc-combining", text: "sarc/o", meaning: "flesh; connective tissue" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-growthmass-sarc-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-tissue-masses"],
    lessonIds: ["lesson-batch-growthmass-tissue-masses"],
    tags: ["unit-1", "growth-family", "oncologic"],
  },
  {
    id: "term-batch-growthmass-osteoma",
    term: "osteoma",
    normalizedTerm: "osteoma",
    pronunciationText: "os-tee-OH-muh",
    plainMeaning: "bone tumor",
    shortDefinition: "a benign tumor formed from bone tissue",
    bodySystem: "musculoskeletal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-osteo-combining", text: "oste/o", meaning: "bone" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-osteo-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    lessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-myoma",
    term: "myoma",
    normalizedTerm: "myoma",
    pronunciationText: "my-OH-muh",
    plainMeaning: "muscle tumor",
    shortDefinition: "a tumor made of muscle tissue, often used for uterine fibroid contexts",
    bodySystem: "musculoskeletal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-my-combining", text: "my/o", meaning: "muscle" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-my-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    lessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-hemangioma",
    term: "hemangioma",
    normalizedTerm: "hemangioma",
    pronunciationText: "hee-man-jee-OH-muh",
    plainMeaning: "blood-vessel tumor",
    shortDefinition: "a benign growth made of blood vessels",
    bodySystem: "vascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-hem-combining", text: "hem/o", meaning: "blood" },
      { partId: "part-angi-combining", text: "angi/o", meaning: "vessel" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-hem-combining", "part-angi-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    lessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    tags: ["unit-1", "growth-family", "vascular"],
  },
  {
    id: "term-batch-growthmass-fibroadenoma",
    term: "fibroadenoma",
    normalizedTerm: "fibroadenoma",
    pronunciationText: "fye-broh-ad-eh-NOH-muh",
    plainMeaning: "fibrous gland tumor",
    shortDefinition: "a benign breast tumor with fibrous and glandular tissue",
    bodySystem: "general",
    difficulty: 3,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-batch-growthmass-fibr-combining", text: "fibr/o", meaning: "fiber; fibrous tissue" },
      { partId: "part-aden-combining", text: "aden/o", meaning: "gland; node" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-growthmass-fibr-combining", "part-aden-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    lessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    tags: ["unit-1", "growth-family", "mass-family"],
  },
  {
    id: "term-batch-growthmass-meningioma",
    term: "meningioma",
    normalizedTerm: "meningioma",
    pronunciationText: "meh-nin-jee-OH-muh",
    plainMeaning: "tumor of the meninges",
    shortDefinition: "a tumor arising from the membranes around the brain and spinal cord",
    bodySystem: "neurologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-mening-combining", text: "mening/o", meaning: "meninges" },
      { partId: "part-oma-suffix", text: "-oma", meaning: "mass; tumor; swelling" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-mening-combining", "part-oma-suffix"],
    prerequisiteLessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    lessonIds: ["lesson-batch-growthmass-common-oma-patterns"],
    tags: ["unit-1", "growth-family", "neurologic"],
  },
];
