import type { Term } from "../../types/content";

export const terms: Term[] = [
  {
    id: "term-leukopenia",
    term: "leukopenia",
    normalizedTerm: "leukopenia",
    pronunciationText: "loo-koh-PEE-nee-uh",
    plainMeaning: "low white blood cell count",
    shortDefinition: "too few white blood cells in the blood",
    bodySystem: "hematologic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-leuk-combining", text: "leuk/o", meaning: "white" },
      { partId: "part-penia-suffix", text: "-penia", meaning: "deficiency; low count" },
    ],
    prerequisiteIds: ["part-leuk-combining", "part-penia-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-white-cell-family"],
    lessonIds: ["lesson-root-bloodcounts-white-cell-family"],
    tags: ["unit-1", "hematologic", "count-family"],
  },
  {
    id: "term-leukemia",
    term: "leukemia",
    normalizedTerm: "leukemia",
    pronunciationText: "loo-KEE-mee-uh",
    plainMeaning: "a blood cancer affecting white cells",
    shortDefinition: "a cancer of blood-forming tissue that often involves white cells",
    bodySystem: "hematologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-white-cell-family"],
    lessonIds: ["lesson-root-bloodcounts-white-cell-family"],
    tags: ["unit-1", "hematologic", "recognition-first"],
  },
  {
    id: "term-thrombocyte",
    term: "thrombocyte",
    normalizedTerm: "thrombocyte",
    pronunciationText: "THROM-boh-site",
    plainMeaning: "platelet",
    shortDefinition: "a platelet or clotting cell fragment in the bloodstream",
    bodySystem: "hematologic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "partial",
    parts: [
      { partId: "part-thromb-combining", text: "thromb/o", meaning: "clot; platelet" },
      { partId: "part-cyte-suffix", text: "-cyte", meaning: "cell" },
    ],
    prerequisiteIds: ["part-thromb-combining", "part-cyte-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-platelet-family"],
    lessonIds: ["lesson-root-bloodcounts-platelet-family"],
    tags: ["unit-1", "hematologic", "platelet-family"],
  },
  {
    id: "term-thrombocytopenia",
    term: "thrombocytopenia",
    normalizedTerm: "thrombocytopenia",
    pronunciationText: "throm-boh-sy-toh-PEE-nee-uh",
    plainMeaning: "low platelet count",
    shortDefinition: "too few platelets in the blood",
    bodySystem: "hematologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-thromb-combining", text: "thromb/o", meaning: "clot; platelet" },
      { partId: "part-cyt-combining", text: "cyt/o", meaning: "cell" },
      { partId: "part-penia-suffix", text: "-penia", meaning: "deficiency; low count" },
    ],
    prerequisiteIds: ["part-thromb-combining", "part-cyt-combining", "part-penia-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-platelet-family"],
    lessonIds: ["lesson-root-bloodcounts-platelet-family"],
    tags: ["unit-1", "hematologic", "platelet-family"],
  },
  {
    id: "term-thrombocytosis",
    term: "thrombocytosis",
    normalizedTerm: "thrombocytosis",
    pronunciationText: "throm-boh-sy-TOH-sis",
    plainMeaning: "high platelet count",
    shortDefinition: "an increased number of platelets",
    bodySystem: "hematologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-thromb-combining", text: "thromb/o", meaning: "clot; platelet" },
      { partId: "part-cyt-combining", text: "cyt/o", meaning: "cell" },
      { partId: "part-osis-suffix", text: "-osis", meaning: "abnormal condition" },
    ],
    prerequisiteIds: ["part-thromb-combining", "part-cyt-combining", "part-osis-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-platelet-family"],
    lessonIds: ["lesson-root-bloodcounts-platelet-family"],
    tags: ["unit-1", "hematologic", "platelet-family"],
  },
  {
    id: "term-erythrocytosis",
    term: "erythrocytosis",
    normalizedTerm: "erythrocytosis",
    pronunciationText: "eh-rith-roh-sy-TOH-sis",
    plainMeaning: "high red blood cell count",
    shortDefinition: "an increased number of red blood cells",
    bodySystem: "hematologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-erythr-combining", text: "erythr/o", meaning: "red" },
      { partId: "part-cyt-combining", text: "cyt/o", meaning: "cell" },
      { partId: "part-osis-suffix", text: "-osis", meaning: "abnormal condition" },
    ],
    prerequisiteIds: ["part-erythr-combining", "part-cyt-combining", "part-osis-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-red-cell-family"],
    lessonIds: ["lesson-root-bloodcounts-red-cell-family"],
    tags: ["unit-1", "hematologic", "red-cell-family"],
  },
  {
    id: "term-polycythemia",
    term: "polycythemia",
    normalizedTerm: "polycythemia",
    pronunciationText: "pol-ee-sy-THEE-mee-uh",
    plainMeaning: "too many red blood cells",
    shortDefinition: "a condition with excess red blood cells in the blood",
    bodySystem: "hematologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-poly-prefix", text: "poly-", meaning: "many; much" },
      { partId: "part-cyt-combining", text: "cyt/o", meaning: "cell" },
      { partId: "part-emia-suffix", text: "-emia", meaning: "blood condition" },
    ],
    prerequisiteIds: ["part-poly-prefix", "part-cyt-combining", "part-emia-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-red-cell-family"],
    lessonIds: ["lesson-root-bloodcounts-red-cell-family"],
    tags: ["unit-1", "hematologic", "red-cell-family"],
  },
  {
    id: "term-cytology",
    term: "cytology",
    normalizedTerm: "cytology",
    pronunciationText: "sy-TOH-luh-jee",
    plainMeaning: "study of cells",
    shortDefinition: "the study or examination of cells",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-cyt-combining", text: "cyt/o", meaning: "cell" },
      { partId: "part-ology-suffix", text: "-logy", meaning: "study of" },
    ],
    prerequisiteIds: ["part-cyt-combining", "part-ology-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    lessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    tags: ["unit-1", "cell-family", "study"],
  },
  {
    id: "term-cytopenia",
    term: "cytopenia",
    normalizedTerm: "cytopenia",
    pronunciationText: "sy-toh-PEE-nee-uh",
    plainMeaning: "low cell count",
    shortDefinition: "a deficiency of cells, often in the blood",
    bodySystem: "hematologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-cyt-combining", text: "cyt/o", meaning: "cell" },
      { partId: "part-penia-suffix", text: "-penia", meaning: "deficiency; low count" },
    ],
    prerequisiteIds: ["part-cyt-combining", "part-penia-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    lessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    tags: ["unit-1", "hematologic", "count-family"],
  },
  {
    id: "term-pancytopenia",
    term: "pancytopenia",
    normalizedTerm: "pancytopenia",
    pronunciationText: "pan-sy-toh-PEE-nee-uh",
    plainMeaning: "low counts across all blood cell lines",
    shortDefinition: "a deficiency of red cells, white cells, and platelets together",
    bodySystem: "hematologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-panc-prefix", text: "panc-", meaning: "all; entire" },
      { partId: "part-cyt-combining", text: "cyt/o", meaning: "cell" },
      { partId: "part-penia-suffix", text: "-penia", meaning: "deficiency; low count" },
    ],
    prerequisiteIds: ["part-panc-prefix", "part-cyt-combining", "part-penia-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    lessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    tags: ["unit-1", "hematologic", "count-family"],
  },
  {
    id: "term-hemogram",
    term: "hemogram",
    normalizedTerm: "hemogram",
    pronunciationText: "HEM-oh-gram",
    plainMeaning: "blood count record",
    shortDefinition: "a recorded blood count from lab work",
    bodySystem: "hematologic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-hem-combining", text: "hem/o", meaning: "blood" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record; image" },
    ],
    prerequisiteIds: ["part-hem-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    lessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    tags: ["unit-1", "hematologic", "record-family"],
  },
  {
    id: "term-hemolysis",
    term: "hemolysis",
    normalizedTerm: "hemolysis",
    pronunciationText: "hee-MOL-ih-sis",
    plainMeaning: "breakdown of blood cells",
    shortDefinition: "destruction or breakdown of red blood cells",
    bodySystem: "hematologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-hem-combining", text: "hem/o", meaning: "blood" },
      { partId: "part-lysis-suffix", text: "-lysis", meaning: "breakdown; destruction" },
    ],
    prerequisiteIds: ["part-hem-combining", "part-lysis-suffix"],
    prerequisiteLessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    lessonIds: ["lesson-root-bloodcounts-count-and-deficiency"],
    tags: ["unit-1", "hematologic", "record-family"],
  },
];
