import type { Term } from "../../types/content";

export const terms: Term[] = [
  {
    id: "term-batch-radiography",
    term: "radiography",
    normalizedTerm: "radiography",
    pronunciationText: "RAY-dee-OG-ruh-fee",
    plainMeaning: "the process of making X-ray images",
    shortDefinition: "the process of recording images with radiation",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-radi-combining", text: "radi/o", meaning: "radiation; X-ray" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-batch-imaging-radi-combining", "part-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["unit-1", "imaging"],
  },
  {
    id: "term-batch-sonogram",
    term: "sonogram",
    normalizedTerm: "sonogram",
    pronunciationText: "SOH-noh-gram",
    plainMeaning: "an image made with sound waves",
    shortDefinition: "a sound-based record or picture",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-son-combining", text: "son/o", meaning: "sound" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-imaging-son-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["unit-1", "imaging"],
  },
  {
    id: "term-batch-sonography",
    term: "sonography",
    normalizedTerm: "sonography",
    pronunciationText: "so-NOG-ruh-fee",
    plainMeaning: "the process of making sound-wave images",
    shortDefinition: "the process of recording images with sound",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-son-combining", text: "son/o", meaning: "sound" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-batch-imaging-son-combining", "part-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["unit-1", "imaging"],
  },
  {
    id: "term-batch-mammogram",
    term: "mammogram",
    normalizedTerm: "mammogram",
    pronunciationText: "MAM-oh-gram",
    plainMeaning: "an X-ray image of the breast",
    shortDefinition: "a breast image made with X-rays",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-mamm-combining", text: "mamm/o", meaning: "breast" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-imaging-mamm-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["unit-1", "imaging"],
  },
  {
    id: "term-batch-mammography",
    term: "mammography",
    normalizedTerm: "mammography",
    pronunciationText: "mam-OG-ruh-fee",
    plainMeaning: "the process of making breast images",
    shortDefinition: "the process of recording breast images with X-rays",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-mamm-combining", text: "mamm/o", meaning: "breast" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-batch-imaging-mamm-combining", "part-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["unit-1", "imaging"],
  },
  {
    id: "term-batch-cardiograph",
    term: "cardiograph",
    normalizedTerm: "cardiograph",
    pronunciationText: "KAR-dee-oh-graf",
    plainMeaning: "an instrument that records the heart",
    shortDefinition: "a device that records heart activity",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-batch-imaging-graph-suffix", text: "-graph", meaning: "instrument that records" },
    ],
    prerequisiteIds: ["part-batch-imaging-cardi-combining", "part-batch-imaging-graph-suffix"],
    prerequisiteLessonIds: ["lesson-batch-heart-and-contrast-records"],
    lessonIds: ["lesson-batch-heart-and-contrast-records"],
    tags: ["unit-1", "cardiac", "imaging"],
  },
  {
    id: "term-batch-electrocardiogram",
    term: "electrocardiogram",
    normalizedTerm: "electrocardiogram",
    pronunciationText: "ee-lek-troh-KAR-dee-oh-gram",
    plainMeaning: "a record of the heart's electrical activity",
    shortDefinition: "a heart tracing that records electrical activity",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-electr-combining", text: "electr/o", meaning: "electricity" },
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: [
      "part-batch-imaging-electr-combining",
      "part-batch-imaging-cardi-combining",
      "part-gram-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-heart-and-contrast-records"],
    lessonIds: ["lesson-batch-heart-and-contrast-records"],
    tags: ["unit-1", "cardiac", "imaging"],
  },
  {
    id: "term-batch-electrocardiograph",
    term: "electrocardiograph",
    normalizedTerm: "electrocardiograph",
    pronunciationText: "ee-lek-troh-KAR-dee-oh-graf",
    plainMeaning: "an instrument that records the heart's electrical activity",
    shortDefinition: "a device that records the electrical activity of the heart",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-electr-combining", text: "electr/o", meaning: "electricity" },
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-batch-imaging-graph-suffix", text: "-graph", meaning: "instrument that records" },
    ],
    prerequisiteIds: [
      "part-batch-imaging-electr-combining",
      "part-batch-imaging-cardi-combining",
      "part-batch-imaging-graph-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-heart-and-contrast-records"],
    lessonIds: ["lesson-batch-heart-and-contrast-records"],
    tags: ["unit-1", "cardiac", "imaging"],
  },
  {
    id: "term-batch-electrocardiography",
    term: "electrocardiography",
    normalizedTerm: "electrocardiography",
    pronunciationText: "ee-lek-troh-kar-dee-OG-ruh-fee",
    plainMeaning: "the process of recording the heart's electrical activity",
    shortDefinition: "the process of making a heart electrical tracing",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-electr-combining", text: "electr/o", meaning: "electricity" },
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: [
      "part-batch-imaging-electr-combining",
      "part-batch-imaging-cardi-combining",
      "part-graphy-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-heart-and-contrast-records"],
    lessonIds: ["lesson-batch-heart-and-contrast-records"],
    tags: ["unit-1", "cardiac", "imaging"],
  },
  {
    id: "term-batch-venography",
    term: "venography",
    normalizedTerm: "venography",
    pronunciationText: "vee-NOG-ruh-fee",
    plainMeaning: "the process of making vein images",
    shortDefinition: "the process of recording images of veins",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-ven-combining", text: "ven/o", meaning: "vein" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-ven-combining", "part-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-heart-and-contrast-records"],
    lessonIds: ["lesson-batch-heart-and-contrast-records"],
    tags: ["unit-1", "vascular", "imaging"],
  },
  {
    id: "term-batch-cystography",
    term: "cystography",
    normalizedTerm: "cystography",
    pronunciationText: "sis-TOG-ruh-fee",
    plainMeaning: "the process of making bladder images",
    shortDefinition: "the process of recording images of the bladder",
    bodySystem: "urinary",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-cyst-combining", text: "cyst/o", meaning: "bladder; sac" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-cyst-combining", "part-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-heart-and-contrast-records"],
    lessonIds: ["lesson-batch-heart-and-contrast-records"],
    tags: ["unit-1", "urinary", "imaging"],
  },
  {
    id: "term-batch-fluoroscopy",
    term: "fluoroscopy",
    normalizedTerm: "fluoroscopy",
    pronunciationText: "floor-OS-koh-pee",
    plainMeaning: "live imaging with a scope-like X-ray view",
    shortDefinition: "a moving X-ray style imaging technique used during procedures",
    bodySystem: "diagnostic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-fluor-combining", text: "fluor/o", meaning: "fluorescence; fluoroscopy" },
      { partId: "part-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" },
    ],
    prerequisiteIds: ["part-batch-imaging-fluor-combining", "part-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-live-and-scope-imaging"],
    lessonIds: ["lesson-batch-live-and-scope-imaging"],
    tags: ["unit-1", "imaging"],
  },
  {
    id: "term-batch-thoracoscopy",
    term: "thoracoscopy",
    normalizedTerm: "thoracoscopy",
    pronunciationText: "thor-uh-KOS-koh-pee",
    plainMeaning: "viewing the chest with a scope",
    shortDefinition: "a scoped look into the chest cavity",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-thorac-combining", text: "thorac/o", meaning: "chest" },
      { partId: "part-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" },
    ],
    prerequisiteIds: ["part-thorac-combining", "part-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-live-and-scope-imaging"],
    lessonIds: ["lesson-batch-live-and-scope-imaging"],
    tags: ["unit-1", "respiratory", "imaging"],
  },
  {
    id: "term-batch-laparoscopy",
    term: "laparoscopy",
    normalizedTerm: "laparoscopy",
    pronunciationText: "lap-ah-ROS-koh-pee",
    plainMeaning: "viewing the abdomen with a scope",
    shortDefinition: "a minimally invasive scoped look into the abdomen",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-lapar-combining", text: "lapar/o", meaning: "abdomen; abdominal wall" },
      { partId: "part-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" },
    ],
    prerequisiteIds: ["part-batch-imaging-lapar-combining", "part-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-live-and-scope-imaging"],
    lessonIds: ["lesson-batch-live-and-scope-imaging"],
    tags: ["unit-1", "gastrointestinal", "imaging"],
  },
];
