import type { Term } from "../../types/content";

export const terms: Term[] = [
  {
    id: "term-batch-antibiotic",
    term: "antibiotic",
    normalizedTerm: "antibiotic",
    pronunciationText: "an-tee-by-OT-ik",
    plainMeaning: "against bacteria",
    shortDefinition: "a medicine that fights bacterial infection",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "core",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-anti-prefix", text: "anti-", meaning: "against; opposed to" },
      { partId: "part-batch-definflam-bi-combining", text: "bi/o", meaning: "life" },
      { partId: "part-batch-definflam-otic-suffix", text: "-otic", meaning: "pertaining to" },
    ],
    prerequisiteIds: [
      "part-batch-definflam-anti-prefix",
      "part-batch-definflam-bi-combining",
      "part-batch-definflam-otic-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-definflam-prefix-shifts"],
    lessonIds: ["lesson-batch-definflam-prefix-shifts"],
    tags: ["unit-1", "prefix", "infection"],
  },
  {
    id: "term-batch-antiseptic",
    term: "antiseptic",
    normalizedTerm: "antiseptic",
    pronunciationText: "an-tee-SEP-tik",
    plainMeaning: "against infection",
    shortDefinition: "an agent that reduces infection risk",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-anti-prefix", text: "anti-", meaning: "against; opposed to" },
      { partId: "part-batch-definflam-septic-combining", text: "septic/o", meaning: "infection; putrefaction" },
      { partId: "part-batch-definflam-ic-suffix", text: "-ic", meaning: "pertaining to" },
    ],
    prerequisiteIds: [
      "part-batch-definflam-anti-prefix",
      "part-batch-definflam-septic-combining",
      "part-batch-definflam-ic-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-definflam-prefix-shifts"],
    lessonIds: ["lesson-batch-definflam-prefix-shifts"],
    tags: ["unit-1", "prefix", "infection"],
  },
  {
    id: "term-batch-antipyretic",
    term: "antipyretic",
    normalizedTerm: "antipyretic",
    pronunciationText: "an-tee-py-RET-ik",
    plainMeaning: "fever reducing",
    shortDefinition: "a medicine that lowers fever",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-anti-prefix", text: "anti-", meaning: "against; opposed to" },
      { partId: "part-batch-definflam-pyret-combining", text: "pyret/o", meaning: "fever" },
      { partId: "part-batch-definflam-ic-suffix", text: "-ic", meaning: "pertaining to" },
    ],
    prerequisiteIds: [
      "part-batch-definflam-anti-prefix",
      "part-batch-definflam-pyret-combining",
      "part-batch-definflam-ic-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-definflam-prefix-shifts"],
    lessonIds: ["lesson-batch-definflam-prefix-shifts"],
    tags: ["unit-1", "prefix", "fever"],
  },
  {
    id: "term-batch-antiemetic",
    term: "antiemetic",
    normalizedTerm: "antiemetic",
    pronunciationText: "an-tee-eh-MET-ik",
    plainMeaning: "against vomiting",
    shortDefinition: "a medicine that reduces nausea or vomiting",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-anti-prefix", text: "anti-", meaning: "against; opposed to" },
      { partId: "part-batch-definflam-emet-combining", text: "emet/o", meaning: "vomit" },
      { partId: "part-batch-definflam-ic-suffix", text: "-ic", meaning: "pertaining to" },
    ],
    prerequisiteIds: [
      "part-batch-definflam-anti-prefix",
      "part-batch-definflam-emet-combining",
      "part-batch-definflam-ic-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-definflam-prefix-shifts"],
    lessonIds: ["lesson-batch-definflam-prefix-shifts"],
    tags: ["unit-1", "prefix", "symptom"],
  },
  {
    id: "term-batch-eupnea",
    term: "eupnea",
    normalizedTerm: "eupnea",
    pronunciationText: "yoo-NEE-uh",
    plainMeaning: "normal breathing",
    shortDefinition: "easy, normal breathing",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-eu-prefix", text: "eu-", meaning: "good; normal" },
      { partId: "part-pnea-suffix", text: "-pnea", meaning: "breathing" },
    ],
    prerequisiteIds: ["part-batch-definflam-eu-prefix", "part-pnea-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-prefix-shifts"],
    lessonIds: ["lesson-batch-definflam-prefix-shifts"],
    tags: ["unit-1", "prefix", "respiratory"],
  },
  {
    id: "term-batch-malnutrition",
    term: "malnutrition",
    normalizedTerm: "malnutrition",
    pronunciationText: "mal-new-TRIH-shun",
    plainMeaning: "poor nutrition",
    shortDefinition: "a condition caused by inadequate nourishment",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-mal-prefix", text: "mal-", meaning: "bad; poor; faulty" },
      { partId: "part-batch-definflam-nutr-combining", text: "nutr/o", meaning: "nutrition; nourishment" },
      { partId: "part-batch-definflam-tion-suffix", text: "-tion", meaning: "act; process; result" },
    ],
    prerequisiteIds: [
      "part-batch-definflam-mal-prefix",
      "part-batch-definflam-nutr-combining",
      "part-batch-definflam-tion-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-definflam-prefix-shifts"],
    lessonIds: ["lesson-batch-definflam-prefix-shifts"],
    tags: ["unit-1", "prefix", "nutrition"],
  },
  {
    id: "term-batch-malabsorption",
    term: "malabsorption",
    normalizedTerm: "malabsorption",
    pronunciationText: "mal-ab-SORP-shun",
    plainMeaning: "poor absorption",
    shortDefinition: "impaired absorption of nutrients",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-mal-prefix", text: "mal-", meaning: "bad; poor; faulty" },
      { partId: "part-batch-definflam-absorpt-combining", text: "absorpt/o", meaning: "absorption" },
      { partId: "part-batch-definflam-tion-suffix", text: "-tion", meaning: "act; process; result" },
    ],
    prerequisiteIds: [
      "part-batch-definflam-mal-prefix",
      "part-batch-definflam-absorpt-combining",
      "part-batch-definflam-tion-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-definflam-prefix-shifts"],
    lessonIds: ["lesson-batch-definflam-prefix-shifts"],
    tags: ["unit-1", "prefix", "gastrointestinal"],
  },
  {
    id: "term-batch-dysphagia",
    term: "dysphagia",
    normalizedTerm: "dysphagia",
    pronunciationText: "dis-FAY-jee-uh",
    plainMeaning: "difficulty swallowing",
    shortDefinition: "trouble swallowing food or liquid",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-dys-prefix", text: "dys-", meaning: "difficult or abnormal" },
      { partId: "part-batch-definflam-phag-combining", text: "phag/o", meaning: "eat; swallow" },
      { partId: "part-batch-definflam-ia-suffix", text: "-ia", meaning: "condition; state" },
    ],
    prerequisiteIds: ["part-dys-prefix", "part-batch-definflam-phag-combining", "part-batch-definflam-ia-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-dysfunction-words"],
    lessonIds: ["lesson-batch-definflam-dysfunction-words"],
    tags: ["unit-1", "dys-", "gastrointestinal"],
  },
  {
    id: "term-batch-dysphonia",
    term: "dysphonia",
    normalizedTerm: "dysphonia",
    pronunciationText: "dis-FOH-nee-uh",
    plainMeaning: "voice difficulty",
    shortDefinition: "abnormal or difficult voice production",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-dys-prefix", text: "dys-", meaning: "difficult or abnormal" },
      { partId: "part-batch-definflam-phon-combining", text: "phon/o", meaning: "voice; sound" },
      { partId: "part-batch-definflam-ia-suffix", text: "-ia", meaning: "condition; state" },
    ],
    prerequisiteIds: ["part-dys-prefix", "part-batch-definflam-phon-combining", "part-batch-definflam-ia-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-dysfunction-words"],
    lessonIds: ["lesson-batch-definflam-dysfunction-words"],
    tags: ["unit-1", "dys-", "voice"],
  },
  {
    id: "term-batch-dysphasia",
    term: "dysphasia",
    normalizedTerm: "dysphasia",
    pronunciationText: "dis-FAY-zhuh",
    plainMeaning: "speech difficulty",
    shortDefinition: "difficulty with speech or language",
    bodySystem: "nervous",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-dys-prefix", text: "dys-", meaning: "difficult or abnormal" },
      { partId: "part-batch-definflam-phas-combining", text: "phas/o", meaning: "speech" },
      { partId: "part-batch-definflam-ia-suffix", text: "-ia", meaning: "condition; state" },
    ],
    prerequisiteIds: ["part-dys-prefix", "part-batch-definflam-phas-combining", "part-batch-definflam-ia-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-dysfunction-words"],
    lessonIds: ["lesson-batch-definflam-dysfunction-words"],
    tags: ["unit-1", "dys-", "speech"],
  },
  {
    id: "term-batch-dystonia",
    term: "dystonia",
    normalizedTerm: "dystonia",
    pronunciationText: "dis-TOH-nee-uh",
    plainMeaning: "abnormal muscle tone",
    shortDefinition: "a disorder of muscle tone or posture",
    bodySystem: "nervous",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-dys-prefix", text: "dys-", meaning: "difficult or abnormal" },
      { partId: "part-batch-definflam-ton-combining", text: "ton/o", meaning: "tone; tension" },
      { partId: "part-batch-definflam-ia-suffix", text: "-ia", meaning: "condition; state" },
    ],
    prerequisiteIds: ["part-dys-prefix", "part-batch-definflam-ton-combining", "part-batch-definflam-ia-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-dysfunction-words"],
    lessonIds: ["lesson-batch-definflam-dysfunction-words"],
    tags: ["unit-1", "dys-", "movement"],
  },
  {
    id: "term-batch-pathology",
    term: "pathology",
    normalizedTerm: "pathology",
    pronunciationText: "puh-THOL-uh-jee",
    plainMeaning: "study of disease",
    shortDefinition: "the study of disease and disease changes",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-path-combining", text: "path/o", meaning: "disease; suffering" },
      { partId: "part-ology-suffix", text: "-logy", meaning: "study of" },
    ],
    prerequisiteIds: ["part-batch-definflam-path-combining", "part-ology-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-path-and-stasis"],
    lessonIds: ["lesson-batch-definflam-path-and-stasis"],
    tags: ["unit-1", "disease"],
  },
  {
    id: "term-batch-pathogenic",
    term: "pathogenic",
    normalizedTerm: "pathogenic",
    pronunciationText: "path-oh-JEN-ik",
    plainMeaning: "causing disease",
    shortDefinition: "able to cause disease",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-path-combining", text: "path/o", meaning: "disease; suffering" },
      { partId: "part-batch-definflam-genic-suffix", text: "-genic", meaning: "producing; causing" },
    ],
    prerequisiteIds: ["part-batch-definflam-path-combining", "part-batch-definflam-genic-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-path-and-stasis"],
    lessonIds: ["lesson-batch-definflam-path-and-stasis"],
    tags: ["unit-1", "disease", "cause"],
  },
  {
    id: "term-batch-pathogenesis",
    term: "pathogenesis",
    normalizedTerm: "pathogenesis",
    pronunciationText: "path-oh-JEN-uh-sis",
    plainMeaning: "how a disease develops",
    shortDefinition: "the origin and development of disease",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-path-combining", text: "path/o", meaning: "disease; suffering" },
      { partId: "part-batch-definflam-genesis-suffix", text: "-genesis", meaning: "formation; origin" },
    ],
    prerequisiteIds: ["part-batch-definflam-path-combining", "part-batch-definflam-genesis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-path-and-stasis"],
    lessonIds: ["lesson-batch-definflam-path-and-stasis"],
    tags: ["unit-1", "disease", "cause"],
  },
  {
    id: "term-batch-hemostasis",
    term: "hemostasis",
    normalizedTerm: "hemostasis",
    pronunciationText: "hee-moh-STAY-sis",
    plainMeaning: "stopping bleeding",
    shortDefinition: "the process that stops blood flow after injury",
    bodySystem: "blood",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-hem-combining", text: "hem/o", meaning: "blood" },
      { partId: "part-batch-definflam-stasis-suffix", text: "-stasis", meaning: "standing still; stopping" },
    ],
    prerequisiteIds: ["part-hem-combining", "part-batch-definflam-stasis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-path-and-stasis"],
    lessonIds: ["lesson-batch-definflam-path-and-stasis"],
    tags: ["unit-1", "blood", "state"],
  },
  {
    id: "term-batch-homeostasis",
    term: "homeostasis",
    normalizedTerm: "homeostasis",
    pronunciationText: "hoh-mee-oh-STAY-sis",
    plainMeaning: "stable internal balance",
    shortDefinition: "the body keeping its internal conditions steady",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-definflam-homeo-prefix", text: "homeo-", meaning: "same; constant" },
      { partId: "part-batch-definflam-stasis-suffix", text: "-stasis", meaning: "standing still; stopping" },
    ],
    prerequisiteIds: ["part-batch-definflam-homeo-prefix", "part-batch-definflam-stasis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-path-and-stasis"],
    lessonIds: ["lesson-batch-definflam-path-and-stasis"],
    tags: ["unit-1", "balance", "state"],
  },
  {
    id: "term-batch-cholestasis",
    term: "cholestasis",
    normalizedTerm: "cholestasis",
    pronunciationText: "koh-luh-STAY-sis",
    plainMeaning: "stopped bile flow",
    shortDefinition: "slowed or blocked bile flow",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-chole-combining", text: "chol/e", meaning: "bile; gall" },
      { partId: "part-batch-definflam-stasis-suffix", text: "-stasis", meaning: "standing still; stopping" },
    ],
    prerequisiteIds: ["part-chole-combining", "part-batch-definflam-stasis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-definflam-path-and-stasis"],
    lessonIds: ["lesson-batch-definflam-path-and-stasis"],
    tags: ["unit-1", "gastrointestinal", "state"],
  },
];
