import type { Term } from "../../types/content";

export const terms: Term[] = [
  {
    id: "term-batch-measure-spirometer",
    term: "spirometer",
    normalizedTerm: "spirometer",
    pronunciationText: "spy-ROM-eh-ter",
    plainMeaning: "instrument that measures breathing",
    shortDefinition: "a device used to measure airflow and breathing volume",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-measure-spir-combining", text: "spir/o", meaning: "breath; breathing" },
      { partId: "part-batch-measure-meter-suffix", text: "-meter", meaning: "instrument for measuring" },
    ],
    prerequisiteIds: ["part-batch-measure-spir-combining", "part-batch-measure-meter-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-tools"],
    lessonIds: ["lesson-batch-measurement-tools"],
    tags: ["unit-1", "measurement-family", "respiratory"],
  },
  {
    id: "term-batch-measure-spirometry",
    term: "spirometry",
    normalizedTerm: "spirometry",
    pronunciationText: "spy-ROM-eh-tree",
    plainMeaning: "the process of measuring breathing",
    shortDefinition: "the test that measures airflow and breathing capacity",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-measure-spir-combining", text: "spir/o", meaning: "breath; breathing" },
      { partId: "part-batch-measure-metry-suffix", text: "-metry", meaning: "process of measuring" },
    ],
    prerequisiteIds: ["part-batch-measure-spir-combining", "part-batch-measure-metry-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-tools"],
    lessonIds: ["lesson-batch-measurement-tools"],
    tags: ["unit-1", "measurement-family", "respiratory"],
  },
  {
    id: "term-batch-measure-oximeter",
    term: "oximeter",
    normalizedTerm: "oximeter",
    pronunciationText: "ok-SIM-eh-ter",
    plainMeaning: "instrument that measures oxygen level",
    shortDefinition: "a device used to measure oxygen saturation",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-measure-ox-combining", text: "ox/o", meaning: "oxygen" },
      { partId: "part-batch-measure-meter-suffix", text: "-meter", meaning: "instrument for measuring" },
    ],
    prerequisiteIds: ["part-batch-measure-ox-combining", "part-batch-measure-meter-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-tools"],
    lessonIds: ["lesson-batch-measurement-tools"],
    tags: ["unit-1", "measurement-family", "respiratory"],
  },
  {
    id: "term-batch-measure-oximetry",
    term: "oximetry",
    normalizedTerm: "oximetry",
    pronunciationText: "ok-SIM-eh-tree",
    plainMeaning: "the process of measuring oxygen level",
    shortDefinition: "measurement of oxygen saturation",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-measure-ox-combining", text: "ox/o", meaning: "oxygen" },
      { partId: "part-batch-measure-metry-suffix", text: "-metry", meaning: "process of measuring" },
    ],
    prerequisiteIds: ["part-batch-measure-ox-combining", "part-batch-measure-metry-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-tools"],
    lessonIds: ["lesson-batch-measurement-tools"],
    tags: ["unit-1", "measurement-family", "respiratory"],
  },
  {
    id: "term-batch-measure-thermometer",
    term: "thermometer",
    normalizedTerm: "thermometer",
    pronunciationText: "ther-MOM-eh-ter",
    plainMeaning: "instrument that measures temperature",
    shortDefinition: "a device used to measure body temperature",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-measure-therm-combining", text: "therm/o", meaning: "heat; temperature" },
      { partId: "part-batch-measure-meter-suffix", text: "-meter", meaning: "instrument for measuring" },
    ],
    prerequisiteIds: ["part-batch-measure-therm-combining", "part-batch-measure-meter-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-tools"],
    lessonIds: ["lesson-batch-measurement-tools"],
    tags: ["unit-1", "measurement-family", "general"],
  },
  {
    id: "term-batch-measure-thermometry",
    term: "thermometry",
    normalizedTerm: "thermometry",
    pronunciationText: "ther-MOM-eh-tree",
    plainMeaning: "the process of measuring temperature",
    shortDefinition: "measurement of temperature",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-measure-therm-combining", text: "therm/o", meaning: "heat; temperature" },
      { partId: "part-batch-measure-metry-suffix", text: "-metry", meaning: "process of measuring" },
    ],
    prerequisiteIds: ["part-batch-measure-therm-combining", "part-batch-measure-metry-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-tools"],
    lessonIds: ["lesson-batch-measurement-tools"],
    tags: ["unit-1", "measurement-family", "general"],
  },
  {
    id: "term-batch-measure-electroencephalogram",
    term: "electroencephalogram",
    normalizedTerm: "electroencephalogram",
    pronunciationText: "eh-lek-troh-en-SEF-uh-loh-gram",
    plainMeaning: "record of brain electrical activity",
    shortDefinition: "the recorded tracing of electrical activity in the brain",
    bodySystem: "neurologic",
    difficulty: 3,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-electr-combining", text: "electr/o", meaning: "electricity" },
      { partId: "part-encephal-combining", text: "encephal/o", meaning: "brain" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-imaging-electr-combining", "part-encephal-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-records"],
    lessonIds: ["lesson-batch-measurement-records"],
    tags: ["unit-1", "measurement-family", "neurologic"],
  },
  {
    id: "term-batch-measure-electroencephalograph",
    term: "electroencephalograph",
    normalizedTerm: "electroencephalograph",
    pronunciationText: "eh-lek-troh-en-SEF-uh-loh-graf",
    plainMeaning: "instrument that records brain electrical activity",
    shortDefinition: "the instrument used to produce an EEG tracing",
    bodySystem: "neurologic",
    difficulty: 3,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-electr-combining", text: "electr/o", meaning: "electricity" },
      { partId: "part-encephal-combining", text: "encephal/o", meaning: "brain" },
      { partId: "part-batch-imaging-graph-suffix", text: "-graph", meaning: "instrument that records" },
    ],
    prerequisiteIds: ["part-batch-imaging-electr-combining", "part-encephal-combining", "part-batch-imaging-graph-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-records"],
    lessonIds: ["lesson-batch-measurement-records"],
    tags: ["unit-1", "measurement-family", "neurologic"],
  },
  {
    id: "term-batch-measure-electroencephalography",
    term: "electroencephalography",
    normalizedTerm: "electroencephalography",
    pronunciationText: "eh-lek-troh-en-sef-uh-LOG-ruh-fee",
    plainMeaning: "process of recording brain electrical activity",
    shortDefinition: "the process of producing an EEG recording",
    bodySystem: "neurologic",
    difficulty: 3,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-electr-combining", text: "electr/o", meaning: "electricity" },
      { partId: "part-encephal-combining", text: "encephal/o", meaning: "brain" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording or imaging" },
    ],
    prerequisiteIds: ["part-batch-imaging-electr-combining", "part-encephal-combining", "part-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-records"],
    lessonIds: ["lesson-batch-measurement-records"],
    tags: ["unit-1", "measurement-family", "neurologic"],
  },
  {
    id: "term-batch-measure-myelogram",
    term: "myelogram",
    normalizedTerm: "myelogram",
    pronunciationText: "MYE-eh-loh-gram",
    plainMeaning: "record or image of the spinal canal",
    shortDefinition: "an imaging study of the spinal canal using contrast",
    bodySystem: "neurologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-myel-combining", text: "myel/o", meaning: "marrow; spinal cord" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-growthmass-myel-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-records"],
    lessonIds: ["lesson-batch-measurement-records"],
    tags: ["unit-1", "measurement-family", "neurologic"],
  },
  {
    id: "term-batch-measure-myelography",
    term: "myelography",
    normalizedTerm: "myelography",
    pronunciationText: "my-eh-LOG-ruh-fee",
    plainMeaning: "the process of imaging the spinal canal",
    shortDefinition: "radiographic imaging of the spinal canal using contrast",
    bodySystem: "neurologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-growthmass-myel-combining", text: "myel/o", meaning: "marrow; spinal cord" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording or imaging" },
    ],
    prerequisiteIds: ["part-batch-growthmass-myel-combining", "part-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-records"],
    lessonIds: ["lesson-batch-measurement-records"],
    tags: ["unit-1", "measurement-family", "neurologic"],
  },
  {
    id: "term-batch-measure-tomogram",
    term: "tomogram",
    normalizedTerm: "tomogram",
    pronunciationText: "TOH-moh-gram",
    plainMeaning: "section image",
    shortDefinition: "an image representing a slice or section through the body",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-measure-tom-combining", text: "tom/o", meaning: "cut; section" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-measure-tom-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-section-imaging"],
    lessonIds: ["lesson-batch-measurement-section-imaging"],
    tags: ["unit-1", "measurement-family", "imaging"],
  },
  {
    id: "term-batch-measure-tomography",
    term: "tomography",
    normalizedTerm: "tomography",
    pronunciationText: "toh-MOG-ruh-fee",
    plainMeaning: "process of making section images",
    shortDefinition: "imaging by sections or slices through the body",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-measure-tom-combining", text: "tom/o", meaning: "cut; section" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording or imaging" },
    ],
    prerequisiteIds: ["part-batch-measure-tom-combining", "part-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-section-imaging"],
    lessonIds: ["lesson-batch-measurement-section-imaging"],
    tags: ["unit-1", "measurement-family", "imaging"],
  },
  {
    id: "term-batch-measure-echocardiogram",
    term: "echocardiogram",
    normalizedTerm: "echocardiogram",
    pronunciationText: "ek-oh-KAR-dee-oh-gram",
    plainMeaning: "ultrasound image record of the heart",
    shortDefinition: "an ultrasound-based recording or image of the heart",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-batch-measure-echo-prefix", text: "echo-", meaning: "reflected sound" },
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-measure-echo-prefix", "part-batch-imaging-cardi-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-section-imaging"],
    lessonIds: ["lesson-batch-measurement-section-imaging"],
    tags: ["unit-1", "measurement-family", "cardiovascular"],
  },
  {
    id: "term-batch-measure-echocardiograph",
    term: "echocardiograph",
    normalizedTerm: "echocardiograph",
    pronunciationText: "ek-oh-KAR-dee-oh-graf",
    plainMeaning: "instrument that records ultrasound images of the heart",
    shortDefinition: "the instrument used to record echocardiographic images",
    bodySystem: "cardiovascular",
    difficulty: 3,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "partial",
    parts: [
      { partId: "part-batch-measure-echo-prefix", text: "echo-", meaning: "reflected sound" },
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-batch-imaging-graph-suffix", text: "-graph", meaning: "instrument that records" },
    ],
    prerequisiteIds: ["part-batch-measure-echo-prefix", "part-batch-imaging-cardi-combining", "part-batch-imaging-graph-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-section-imaging"],
    lessonIds: ["lesson-batch-measurement-section-imaging"],
    tags: ["unit-1", "measurement-family", "cardiovascular"],
  },
  {
    id: "term-batch-measure-echocardiography",
    term: "echocardiography",
    normalizedTerm: "echocardiography",
    pronunciationText: "ek-oh-kar-dee-OG-ruh-fee",
    plainMeaning: "process of ultrasound imaging of the heart",
    shortDefinition: "the process of using ultrasound to image the heart",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-batch-measure-echo-prefix", text: "echo-", meaning: "reflected sound" },
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-graphy-suffix", text: "-graphy", meaning: "process of recording or imaging" },
    ],
    prerequisiteIds: ["part-batch-measure-echo-prefix", "part-batch-imaging-cardi-combining", "part-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-measurement-section-imaging"],
    lessonIds: ["lesson-batch-measurement-section-imaging"],
    tags: ["unit-1", "measurement-family", "cardiovascular"],
  },
];
