import type { Term } from "../../types/content";

export const terms: Term[] = [
  {
    id: "term-batch-neuritis",
    term: "neuritis",
    normalizedTerm: "neuritis",
    pronunciationText: "nyu-RY-tis",
    plainMeaning: "inflammation of a nerve",
    shortDefinition: "a nerve inflammation or irritation",
    bodySystem: "nervous",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-neur-root", text: "neur", meaning: "nerve" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-neur-root", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-1"],
    lessonIds: ["lesson-batch-inflammatory-roots-1"],
    tags: ["unit-1", "inflammation", "nerve"],
  },
  {
    id: "term-batch-appendicitis",
    term: "appendicitis",
    normalizedTerm: "appendicitis",
    pronunciationText: "ap-en-dih-SY-tis",
    plainMeaning: "inflammation of the appendix",
    shortDefinition: "an inflamed appendix",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-appendic-combining", text: "appendic/o", meaning: "appendix" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-appendic-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-1"],
    lessonIds: ["lesson-batch-inflammatory-roots-1"],
    tags: ["unit-1", "inflammation", "gastrointestinal"],
  },
  {
    id: "term-batch-peritonitis",
    term: "peritonitis",
    normalizedTerm: "peritonitis",
    pronunciationText: "pair-ih-toh-NY-tis",
    plainMeaning: "inflammation of the abdominal lining",
    shortDefinition: "inflammation of the peritoneum",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-periton-combining", text: "periton/o", meaning: "peritoneum" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-periton-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-1"],
    lessonIds: ["lesson-batch-inflammatory-roots-1"],
    tags: ["unit-1", "inflammation", "abdominal"],
  },
  {
    id: "term-batch-conjunctivitis",
    term: "conjunctivitis",
    normalizedTerm: "conjunctivitis",
    pronunciationText: "kon-junk-tih-VY-tis",
    plainMeaning: "inflammation of the eye lining",
    shortDefinition: "inflammation of the conjunctiva",
    bodySystem: "ocular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-conjunctiv-combining", text: "conjunctiv/o", meaning: "conjunctiva" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-conjunctiv-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-1"],
    lessonIds: ["lesson-batch-inflammatory-roots-1"],
    tags: ["unit-1", "inflammation", "eye"],
  },
  {
    id: "term-batch-tonsillitis",
    term: "tonsillitis",
    normalizedTerm: "tonsillitis",
    pronunciationText: "ton-suh-LY-tis",
    plainMeaning: "inflammation of the tonsils",
    shortDefinition: "inflamed tonsils",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-tonsill-combining", text: "tonsill/o", meaning: "tonsil" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-tonsill-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-1"],
    lessonIds: ["lesson-batch-inflammatory-roots-1"],
    tags: ["unit-1", "inflammation", "respiratory"],
  },
  {
    id: "term-batch-phlebitis",
    term: "phlebitis",
    normalizedTerm: "phlebitis",
    pronunciationText: "fleh-BY-tis",
    plainMeaning: "inflammation of a vein",
    shortDefinition: "a vein that is inflamed",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-phleb-combining", text: "phleb/o", meaning: "vein" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-phleb-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-2"],
    lessonIds: ["lesson-batch-inflammatory-roots-2"],
    tags: ["unit-1", "inflammation", "vascular"],
  },
  {
    id: "term-batch-lymphangitis",
    term: "lymphangitis",
    normalizedTerm: "lymphangitis",
    pronunciationText: "LIMF-an-JY-tis",
    plainMeaning: "inflammation of lymph vessels",
    shortDefinition: "inflamed lymph vessels",
    bodySystem: "lymphatic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-lymph-combining", text: "lymph/o", meaning: "lymph" },
      { partId: "part-angi-combining", text: "angi/o", meaning: "vessel" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-lymph-combining", "part-angi-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-2"],
    lessonIds: ["lesson-batch-inflammatory-roots-2"],
    tags: ["unit-1", "inflammation", "lymphatic"],
  },
  {
    id: "term-batch-vaginitis",
    term: "vaginitis",
    normalizedTerm: "vaginitis",
    pronunciationText: "vaj-ih-NY-tis",
    plainMeaning: "inflammation of the vagina",
    shortDefinition: "inflamed vaginal tissue",
    bodySystem: "reproductive",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-vagin-combining", text: "vagin/o", meaning: "vagina" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-vagin-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-2"],
    lessonIds: ["lesson-batch-inflammatory-roots-2"],
    tags: ["unit-1", "inflammation", "reproductive"],
  },
  {
    id: "term-batch-vulvitis",
    term: "vulvitis",
    normalizedTerm: "vulvitis",
    pronunciationText: "vul-VY-tis",
    plainMeaning: "inflammation of the vulva",
    shortDefinition: "inflamed vulvar tissue",
    bodySystem: "reproductive",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-vulv-combining", text: "vulv/o", meaning: "vulva" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-vulv-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-2"],
    lessonIds: ["lesson-batch-inflammatory-roots-2"],
    tags: ["unit-1", "inflammation", "reproductive"],
  },
  {
    id: "term-batch-cervicitis",
    term: "cervicitis",
    normalizedTerm: "cervicitis",
    pronunciationText: "ser-vih-SY-tis",
    plainMeaning: "inflammation of the cervix",
    shortDefinition: "inflamed cervical tissue",
    bodySystem: "reproductive",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-cervic-combining", text: "cervic/o", meaning: "cervix" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-cervic-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-2"],
    lessonIds: ["lesson-batch-inflammatory-roots-2"],
    tags: ["unit-1", "inflammation", "reproductive"],
  },
  {
    id: "term-batch-meningitis",
    term: "meningitis",
    normalizedTerm: "meningitis",
    pronunciationText: "meh-nin-JY-tis",
    plainMeaning: "inflammation of the meninges",
    shortDefinition: "inflamed membranes around the brain and spinal cord",
    bodySystem: "nervous",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-mening-combining", text: "mening/o", meaning: "meninges" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-mening-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-inflammatory-roots-2"],
    lessonIds: ["lesson-batch-inflammatory-roots-2"],
    tags: ["unit-1", "inflammation", "nervous"],
  },
  {
    id: "term-batch-lymphedema",
    term: "lymphedema",
    normalizedTerm: "lymphedema",
    pronunciationText: "LIMF-ih-DEE-muh",
    plainMeaning: "swelling from trapped lymph fluid",
    shortDefinition: "swelling caused by lymph buildup",
    bodySystem: "lymphatic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-lymph-combining", text: "lymph/o", meaning: "lymph" },
      { partId: "part-batch-inflammatory-edem-combining", text: "edem/o", meaning: "swelling" },
    ],
    prerequisiteIds: ["part-lymph-combining", "part-batch-inflammatory-edem-combining"],
    prerequisiteLessonIds: ["lesson-batch-swelling-growth-roots"],
    lessonIds: ["lesson-batch-swelling-growth-roots"],
    tags: ["unit-1", "swelling", "lymphatic"],
  },
  {
    id: "term-batch-thyromegaly",
    term: "thyromegaly",
    normalizedTerm: "thyromegaly",
    pronunciationText: "thye-roh-MEG-uh-lee",
    plainMeaning: "enlargement of the thyroid",
    shortDefinition: "an enlarged thyroid gland",
    bodySystem: "endocrine",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-thyroid-combining", text: "thyroid/o", meaning: "thyroid gland" },
      { partId: "part-megaly-suffix", text: "-megaly", meaning: "enlargement" },
    ],
    prerequisiteIds: ["part-thyroid-combining", "part-megaly-suffix"],
    prerequisiteLessonIds: ["lesson-batch-swelling-growth-roots"],
    lessonIds: ["lesson-batch-swelling-growth-roots"],
    tags: ["unit-1", "swelling", "endocrine"],
  },
  {
    id: "term-batch-hypertrophy",
    term: "hypertrophy",
    normalizedTerm: "hypertrophy",
    pronunciationText: "hy-PER-truh-fee",
    plainMeaning: "excessive growth of tissue",
    shortDefinition: "an increase in tissue size",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-hyper-prefix", text: "hyper-", meaning: "too much; excessive" },
      { partId: "part-batch-inflammatory-trophy-suffix", text: "-trophy", meaning: "growth" },
    ],
    prerequisiteIds: ["part-hyper-prefix", "part-batch-inflammatory-trophy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-swelling-growth-roots"],
    lessonIds: ["lesson-batch-swelling-growth-roots"],
    tags: ["unit-1", "growth", "tissue"],
  },
  {
    id: "term-batch-atrophy",
    term: "atrophy",
    normalizedTerm: "atrophy",
    pronunciationText: "AT-ruh-fee",
    plainMeaning: "wasting or shrinkage of tissue",
    shortDefinition: "a decrease in tissue size or bulk",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-a-prefix", text: "a-", meaning: "without; not" },
      { partId: "part-batch-inflammatory-trophy-suffix", text: "-trophy", meaning: "growth" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-a-prefix", "part-batch-inflammatory-trophy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-swelling-growth-roots"],
    lessonIds: ["lesson-batch-swelling-growth-roots"],
    tags: ["unit-1", "growth", "tissue"],
  },
  {
    id: "term-batch-metaplasia",
    term: "metaplasia",
    normalizedTerm: "metaplasia",
    pronunciationText: "meh-tuh-PLAY-zhuh",
    plainMeaning: "change in the type of tissue or cells",
    shortDefinition: "a switch from one mature cell type to another",
    bodySystem: "pathology",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-meta-prefix", text: "meta-", meaning: "change; after" },
      { partId: "part-plasia-suffix", text: "-plasia", meaning: "growth; formation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-meta-prefix", "part-plasia-suffix"],
    prerequisiteLessonIds: ["lesson-batch-tissue-change-roots"],
    lessonIds: ["lesson-batch-tissue-change-roots"],
    tags: ["unit-1", "tissue-change", "pathology"],
  },
  {
    id: "term-batch-chondromalacia",
    term: "chondromalacia",
    normalizedTerm: "chondromalacia",
    pronunciationText: "kon-droh-muh-LAY-shuh",
    plainMeaning: "softening of cartilage",
    shortDefinition: "cartilage that has become soft",
    bodySystem: "musculoskeletal",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-chondr-combining", text: "chondr/o", meaning: "cartilage" },
      { partId: "part-malacia-suffix", text: "-malacia", meaning: "softening" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-chondr-combining", "part-malacia-suffix"],
    prerequisiteLessonIds: ["lesson-batch-tissue-change-roots"],
    lessonIds: ["lesson-batch-tissue-change-roots"],
    tags: ["unit-1", "tissue-change", "musculoskeletal"],
  },
  {
    id: "term-batch-neoplasia",
    term: "neoplasia",
    normalizedTerm: "neoplasia",
    pronunciationText: "nee-oh-PLAY-zhuh",
    plainMeaning: "new abnormal growth",
    shortDefinition: "new, abnormal tissue growth",
    bodySystem: "oncology",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-neo-prefix", text: "neo-", meaning: "new" },
      { partId: "part-plasia-suffix", text: "-plasia", meaning: "growth; formation" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-neo-prefix", "part-plasia-suffix"],
    prerequisiteLessonIds: ["lesson-batch-tissue-change-roots"],
    lessonIds: ["lesson-batch-tissue-change-roots"],
    tags: ["unit-1", "tissue-change", "oncology"],
  },
  {
    id: "term-batch-stenosis",
    term: "stenosis",
    normalizedTerm: "stenosis",
    pronunciationText: "steh-NOH-sis",
    plainMeaning: "narrowing of a passage or opening",
    shortDefinition: "a narrowed body passage",
    bodySystem: "general",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-sten-combining", text: "sten/o", meaning: "narrow; tight" },
      { partId: "part-batch-inflammatory-stenosis-suffix", text: "-stenosis", meaning: "narrowing" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-sten-combining", "part-batch-inflammatory-stenosis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-narrowing-dilation-roots"],
    lessonIds: ["lesson-batch-narrowing-dilation-roots"],
    tags: ["unit-1", "narrowing", "general"],
  },
  {
    id: "term-batch-bronchostenosis",
    term: "bronchostenosis",
    normalizedTerm: "bronchostenosis",
    pronunciationText: "brong-koh-steh-NOH-sis",
    plainMeaning: "narrowing of a bronchus",
    shortDefinition: "a narrowed bronchial passage",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-bronch-combining", text: "bronch/o", meaning: "bronchial tube" },
      { partId: "part-batch-inflammatory-sten-combining", text: "sten/o", meaning: "narrow; tight" },
      { partId: "part-batch-inflammatory-stenosis-suffix", text: "-stenosis", meaning: "narrowing" },
    ],
    prerequisiteIds: [
      "part-bronch-combining",
      "part-batch-inflammatory-sten-combining",
      "part-batch-inflammatory-stenosis-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-narrowing-dilation-roots"],
    lessonIds: ["lesson-batch-narrowing-dilation-roots"],
    tags: ["unit-1", "narrowing", "respiratory"],
  },
  {
    id: "term-batch-tracheostenosis",
    term: "tracheostenosis",
    normalizedTerm: "tracheostenosis",
    pronunciationText: "tray-kee-oh-steh-NOH-sis",
    plainMeaning: "narrowing of the trachea",
    shortDefinition: "a narrowed tracheal passage",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-trache-combining", text: "trache/o", meaning: "trachea" },
      { partId: "part-batch-inflammatory-sten-combining", text: "sten/o", meaning: "narrow; tight" },
      { partId: "part-batch-inflammatory-stenosis-suffix", text: "-stenosis", meaning: "narrowing" },
    ],
    prerequisiteIds: [
      "part-trache-combining",
      "part-batch-inflammatory-sten-combining",
      "part-batch-inflammatory-stenosis-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-narrowing-dilation-roots"],
    lessonIds: ["lesson-batch-narrowing-dilation-roots"],
    tags: ["unit-1", "narrowing", "respiratory"],
  },
  {
    id: "term-batch-vasodilation",
    term: "vasodilation",
    normalizedTerm: "vasodilation",
    pronunciationText: "VAY-zoh-dih-LAY-shun",
    plainMeaning: "widening of a blood vessel",
    shortDefinition: "a vessel opening wider than usual",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-vascul-root", text: "vascul", meaning: "vessel" },
      { partId: "part-batch-inflammatory-dilat-combining", text: "dilat/o", meaning: "widen; open" },
    ],
    prerequisiteIds: ["part-vascul-root", "part-batch-inflammatory-dilat-combining"],
    prerequisiteLessonIds: ["lesson-batch-narrowing-dilation-roots"],
    lessonIds: ["lesson-batch-narrowing-dilation-roots"],
    tags: ["unit-1", "dilation", "vascular"],
  },
  {
    id: "term-batch-bronchiectasis",
    term: "bronchiectasis",
    normalizedTerm: "bronchiectasis",
    pronunciationText: "brong-kee-EK-tuh-sis",
    plainMeaning: "widening of a bronchus",
    shortDefinition: "an abnormally widened bronchial tube",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-bronch-combining", text: "bronch/o", meaning: "bronchial tube" },
      { partId: "part-batch-inflammatory-ectasis-suffix", text: "-ectasis", meaning: "dilation; widening" },
    ],
    prerequisiteIds: ["part-bronch-combining", "part-batch-inflammatory-ectasis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-narrowing-dilation-roots"],
    lessonIds: ["lesson-batch-narrowing-dilation-roots"],
    tags: ["unit-1", "dilation", "respiratory"],
  },
  {
    id: "term-batch-hemorrhage",
    term: "hemorrhage",
    normalizedTerm: "hemorrhage",
    pronunciationText: "HEM-rij",
    plainMeaning: "bursting forth of blood; bleeding",
    shortDefinition: "a heavy or sudden bleed",
    bodySystem: "hematologic",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-hem-combining", text: "hem/o", meaning: "blood" },
      { partId: "part-batch-inflammatory-rrhage-suffix", text: "-rrhage", meaning: "bursting forth; bleeding" },
    ],
    prerequisiteIds: ["part-hem-combining", "part-batch-inflammatory-rrhage-suffix"],
    prerequisiteLessonIds: ["lesson-batch-narrowing-dilation-roots"],
    lessonIds: ["lesson-batch-narrowing-dilation-roots"],
    tags: ["unit-1", "bleeding", "hematologic"],
  },
  {
    id: "term-batch-menorrhagia",
    term: "menorrhagia",
    normalizedTerm: "menorrhagia",
    pronunciationText: "men-oh-RAY-jee-uh",
    plainMeaning: "excessive menstrual bleeding",
    shortDefinition: "heavy menstrual bleeding",
    bodySystem: "reproductive",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-men-combining", text: "men/o", meaning: "menstruation; monthly flow" },
      { partId: "part-batch-inflammatory-rrhagia-suffix", text: "-rrhagia", meaning: "excessive bleeding" },
    ],
    prerequisiteIds: ["part-men-combining", "part-batch-inflammatory-rrhagia-suffix"],
    prerequisiteLessonIds: ["lesson-batch-flow-protrusion-roots"],
    lessonIds: ["lesson-batch-flow-protrusion-roots"],
    tags: ["unit-1", "bleeding", "reproductive"],
  },
  {
    id: "term-batch-cystocele",
    term: "cystocele",
    normalizedTerm: "cystocele",
    pronunciationText: "SIS-toh-seel",
    plainMeaning: "bladder hernia or bulge",
    shortDefinition: "a bulging bladder into the vaginal wall",
    bodySystem: "urinary",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-cyst-combining", text: "cyst/o", meaning: "bladder; sac" },
      { partId: "part-batch-inflammatory-cele-suffix", text: "-cele", meaning: "hernia; protrusion; swelling" },
    ],
    prerequisiteIds: ["part-cyst-combining", "part-batch-inflammatory-cele-suffix"],
    prerequisiteLessonIds: ["lesson-batch-flow-protrusion-roots"],
    lessonIds: ["lesson-batch-flow-protrusion-roots"],
    tags: ["unit-1", "protrusion", "urinary"],
  },
  {
    id: "term-batch-rectocele",
    term: "rectocele",
    normalizedTerm: "rectocele",
    pronunciationText: "REK-toh-seel",
    plainMeaning: "rectal bulge or hernia",
    shortDefinition: "a bulging of the rectum into nearby tissue",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-rect-combining", text: "rect/o", meaning: "rectum" },
      { partId: "part-batch-inflammatory-cele-suffix", text: "-cele", meaning: "hernia; protrusion; swelling" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-rect-combining", "part-batch-inflammatory-cele-suffix"],
    prerequisiteLessonIds: ["lesson-batch-flow-protrusion-roots"],
    lessonIds: ["lesson-batch-flow-protrusion-roots"],
    tags: ["unit-1", "protrusion", "gastrointestinal"],
  },
  {
    id: "term-batch-encephalocele",
    term: "encephalocele",
    normalizedTerm: "encephalocele",
    pronunciationText: "en-SEF-uh-loh-seel",
    plainMeaning: "brain tissue hernia",
    shortDefinition: "a protrusion of brain tissue through the skull",
    bodySystem: "nervous",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-encephal-combining", text: "encephal/o", meaning: "brain" },
      { partId: "part-batch-inflammatory-cele-suffix", text: "-cele", meaning: "hernia; protrusion; swelling" },
    ],
    prerequisiteIds: ["part-encephal-combining", "part-batch-inflammatory-cele-suffix"],
    prerequisiteLessonIds: ["lesson-batch-flow-protrusion-roots"],
    lessonIds: ["lesson-batch-flow-protrusion-roots"],
    tags: ["unit-1", "protrusion", "nervous"],
  },
  {
    id: "term-batch-meningocele",
    term: "meningocele",
    normalizedTerm: "meningocele",
    pronunciationText: "meh-NIN-joh-seel",
    plainMeaning: "hernia involving the meninges",
    shortDefinition: "a bulging of the meninges through an opening",
    bodySystem: "nervous",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-mening-combining", text: "mening/o", meaning: "meninges" },
      { partId: "part-batch-inflammatory-cele-suffix", text: "-cele", meaning: "hernia; protrusion; swelling" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-mening-combining", "part-batch-inflammatory-cele-suffix"],
    prerequisiteLessonIds: ["lesson-batch-flow-protrusion-roots"],
    lessonIds: ["lesson-batch-flow-protrusion-roots"],
    tags: ["unit-1", "protrusion", "nervous"],
  },
  {
    id: "term-batch-hydrocele",
    term: "hydrocele",
    normalizedTerm: "hydrocele",
    pronunciationText: "HY-droh-seel",
    plainMeaning: "fluid-filled swelling or sac",
    shortDefinition: "a fluid collection that forms a swelling",
    bodySystem: "reproductive",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-hydr-combining", text: "hydr/o", meaning: "water; fluid" },
      { partId: "part-batch-inflammatory-cele-suffix", text: "-cele", meaning: "hernia; protrusion; swelling" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-hydr-combining", "part-batch-inflammatory-cele-suffix"],
    prerequisiteLessonIds: ["lesson-batch-flow-protrusion-roots"],
    lessonIds: ["lesson-batch-flow-protrusion-roots"],
    tags: ["unit-1", "protrusion", "fluid"],
  },
];
