import type { Term } from "../../types/content";

export const terms: Term[] = [
  {
    id: "term-batch-radiograph",
    term: "radiograph",
    normalizedTerm: "radiograph",
    pronunciationText: "RAY-dee-oh-graf",
    plainMeaning: "an image made with X-rays",
    shortDefinition: "a record or image produced with radiation",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-radi-combining", text: "radi/o", meaning: "radiation; X-ray" },
      { partId: "part-batch-imaging-graph-suffix", text: "-graph", meaning: "instrument that records" },
    ],
    prerequisiteIds: ["part-batch-imaging-radi-combining", "part-batch-imaging-graph-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["batch-imaging", "recording"],
  },
  {
    id: "term-batch-radiography",
    term: "radiography",
    normalizedTerm: "radiography",
    pronunciationText: "RAY-dee-OG-ruh-fee",
    plainMeaning: "the process of making X-ray images",
    shortDefinition: "the process of recording images with radiation",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-radi-combining", text: "radi/o", meaning: "radiation; X-ray" },
      { partId: "part-batch-imaging-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-batch-imaging-radi-combining", "part-batch-imaging-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["batch-imaging", "recording"],
  },
  {
    id: "term-batch-sonogram",
    term: "sonogram",
    normalizedTerm: "sonogram",
    pronunciationText: "SOH-noh-gram",
    plainMeaning: "an image made with sound waves",
    shortDefinition: "a sound-based record or picture",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-son-combining", text: "son/o", meaning: "sound" },
      { partId: "part-batch-imaging-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-imaging-son-combining", "part-batch-imaging-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["batch-imaging", "recording"],
  },
  {
    id: "term-batch-sonography",
    term: "sonography",
    normalizedTerm: "sonography",
    pronunciationText: "SOH-NOG-ruh-fee",
    plainMeaning: "the process of making sound-wave images",
    shortDefinition: "the process of recording images with sound",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-son-combining", text: "son/o", meaning: "sound" },
      { partId: "part-batch-imaging-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-batch-imaging-son-combining", "part-batch-imaging-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["batch-imaging", "recording"],
  },
  {
    id: "term-batch-mammogram",
    term: "mammogram",
    normalizedTerm: "mammogram",
    pronunciationText: "MAM-oh-gram",
    plainMeaning: "an X-ray image of the breast",
    shortDefinition: "a breast image made with X-rays",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-mamm-combining", text: "mamm/o", meaning: "breast" },
      { partId: "part-batch-imaging-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-imaging-mamm-combining", "part-batch-imaging-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["batch-imaging", "recording"],
  },
  {
    id: "term-batch-mammography",
    term: "mammography",
    normalizedTerm: "mammography",
    pronunciationText: "mam-OG-ruh-fee",
    plainMeaning: "the process of making breast images",
    shortDefinition: "the process of recording breast images with X-rays",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-mamm-combining", text: "mamm/o", meaning: "breast" },
      { partId: "part-batch-imaging-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-batch-imaging-mamm-combining", "part-batch-imaging-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-imaging-records"],
    lessonIds: ["lesson-batch-imaging-records"],
    tags: ["batch-imaging", "recording"],
  },
  {
    id: "term-batch-angiogram",
    term: "angiogram",
    normalizedTerm: "angiogram",
    pronunciationText: "AN-jee-oh-gram",
    plainMeaning: "an image or record of a vessel",
    shortDefinition: "a vessel image or recording",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-angi-combining", text: "angi/o", meaning: "vessel" },
      { partId: "part-batch-imaging-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-imaging-angi-combining", "part-batch-imaging-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-vascular-heart-records"],
    lessonIds: ["lesson-batch-vascular-heart-records"],
    tags: ["batch-imaging", "vascular"],
  },
  {
    id: "term-batch-angiography",
    term: "angiography",
    normalizedTerm: "angiography",
    pronunciationText: "an-jee-OG-ruh-fee",
    plainMeaning: "the process of making vessel images",
    shortDefinition: "the process of recording vessels with images",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-angi-combining", text: "angi/o", meaning: "vessel" },
      { partId: "part-batch-imaging-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-batch-imaging-angi-combining", "part-batch-imaging-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-vascular-heart-records"],
    lessonIds: ["lesson-batch-vascular-heart-records"],
    tags: ["batch-imaging", "vascular"],
  },
  {
    id: "term-batch-cardiogram",
    term: "cardiogram",
    normalizedTerm: "cardiogram",
    pronunciationText: "KAR-dee-oh-gram",
    plainMeaning: "a record of the heart",
    shortDefinition: "a recording or image of heart activity",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-batch-imaging-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: ["part-batch-imaging-cardi-combining", "part-batch-imaging-gram-suffix"],
    prerequisiteLessonIds: ["lesson-batch-vascular-heart-records"],
    lessonIds: ["lesson-batch-vascular-heart-records"],
    tags: ["batch-imaging", "cardiac"],
  },
  {
    id: "term-batch-cardiograph",
    term: "cardiograph",
    normalizedTerm: "cardiograph",
    pronunciationText: "KAR-dee-oh-graf",
    plainMeaning: "an instrument that records the heart",
    shortDefinition: "a device that records heart activity",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-batch-imaging-graph-suffix", text: "-graph", meaning: "instrument that records" },
    ],
    prerequisiteIds: ["part-batch-imaging-cardi-combining", "part-batch-imaging-graph-suffix"],
    prerequisiteLessonIds: ["lesson-batch-vascular-heart-records"],
    lessonIds: ["lesson-batch-vascular-heart-records"],
    tags: ["batch-imaging", "cardiac"],
  },
  {
    id: "term-batch-cardiography",
    term: "cardiography",
    normalizedTerm: "cardiography",
    pronunciationText: "kar-dee-OG-ruh-fee",
    plainMeaning: "the process of recording the heart",
    shortDefinition: "the process of recording heart activity",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-batch-imaging-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: ["part-batch-imaging-cardi-combining", "part-batch-imaging-graphy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-vascular-heart-records"],
    lessonIds: ["lesson-batch-vascular-heart-records"],
    tags: ["batch-imaging", "cardiac"],
  },
  {
    id: "term-batch-electrocardiogram",
    term: "electrocardiogram",
    normalizedTerm: "electrocardiogram",
    pronunciationText: "ee-lek-troh-KAR-dee-oh-gram",
    plainMeaning: "a record of the heart's electrical activity",
    shortDefinition: "a heart tracing that records electrical activity",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-electr-combining", text: "electr/o", meaning: "electricity" },
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-batch-imaging-gram-suffix", text: "-gram", meaning: "record or image" },
    ],
    prerequisiteIds: [
      "part-batch-imaging-electr-combining",
      "part-batch-imaging-cardi-combining",
      "part-batch-imaging-gram-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-vascular-heart-records"],
    lessonIds: ["lesson-batch-vascular-heart-records"],
    tags: ["batch-imaging", "cardiac", "electrical"],
  },
  {
    id: "term-batch-electrocardiograph",
    term: "electrocardiograph",
    normalizedTerm: "electrocardiograph",
    pronunciationText: "ee-lek-troh-KAR-dee-oh-graf",
    plainMeaning: "an instrument that records the heart's electrical activity",
    shortDefinition: "a device that records the electrical activity of the heart",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-electr-combining", text: "electr/o", meaning: "electricity" },
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-batch-imaging-graph-suffix", text: "-graph", meaning: "instrument that records" },
    ],
    prerequisiteIds: [
      "part-batch-imaging-electr-combining",
      "part-batch-imaging-cardi-combining",
      "part-batch-imaging-graph-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-vascular-heart-records"],
    lessonIds: ["lesson-batch-vascular-heart-records"],
    tags: ["batch-imaging", "cardiac", "electrical"],
  },
  {
    id: "term-batch-electrocardiography",
    term: "electrocardiography",
    normalizedTerm: "electrocardiography",
    pronunciationText: "ee-lek-troh-kar-dee-OG-ruh-fee",
    plainMeaning: "the process of recording the heart's electrical activity",
    shortDefinition: "the process of making a heart electrical tracing",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-electr-combining", text: "electr/o", meaning: "electricity" },
      { partId: "part-batch-imaging-cardi-combining", text: "cardi/o", meaning: "heart" },
      { partId: "part-batch-imaging-graphy-suffix", text: "-graphy", meaning: "process of recording" },
    ],
    prerequisiteIds: [
      "part-batch-imaging-electr-combining",
      "part-batch-imaging-cardi-combining",
      "part-batch-imaging-graphy-suffix",
    ],
    prerequisiteLessonIds: ["lesson-batch-vascular-heart-records"],
    lessonIds: ["lesson-batch-vascular-heart-records"],
    tags: ["batch-imaging", "cardiac", "electrical"],
  },
  {
    id: "term-batch-bronchoscopy",
    term: "bronchoscopy",
    normalizedTerm: "bronchoscopy",
    pronunciationText: "brong-KOS-koh-pee",
    plainMeaning: "viewing the bronchial tubes with a scope",
    shortDefinition: "a scoped look at the bronchi",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-bronch-combining", text: "bronch/o", meaning: "bronchial tube; airway branch" },
      { partId: "part-batch-imaging-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" },
    ],
    prerequisiteIds: ["part-batch-imaging-bronch-combining", "part-batch-imaging-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-scope-procedures"],
    lessonIds: ["lesson-batch-scope-procedures"],
    tags: ["batch-imaging", "scope"],
  },
  {
    id: "term-batch-colonoscopy",
    term: "colonoscopy",
    normalizedTerm: "colonoscopy",
    pronunciationText: "koh-luh-NOS-koh-pee",
    plainMeaning: "viewing the colon with a scope",
    shortDefinition: "a scoped look at the colon",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-col-combining", text: "col/o", meaning: "colon" },
      { partId: "part-batch-imaging-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" },
    ],
    prerequisiteIds: ["part-batch-imaging-col-combining", "part-batch-imaging-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-scope-procedures"],
    lessonIds: ["lesson-batch-scope-procedures"],
    tags: ["batch-imaging", "scope"],
  },
  {
    id: "term-batch-endoscopy",
    term: "endoscopy",
    normalizedTerm: "endoscopy",
    pronunciationText: "en-DOS-koh-pee",
    plainMeaning: "viewing the inside of something with a scope",
    shortDefinition: "a scoped look inside the body",
    bodySystem: "diagnostic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-imaging-endo-prefix", text: "endo-", meaning: "within; inside" },
      { partId: "part-batch-imaging-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" },
    ],
    prerequisiteIds: ["part-batch-imaging-endo-prefix", "part-batch-imaging-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-batch-scope-procedures"],
    lessonIds: ["lesson-batch-scope-procedures"],
    tags: ["batch-imaging", "scope"],
  },
];
