import type { Term } from "../../types/content";

export const terms: Term[] = [
  {
    id: "term-batch-fluid-anuria",
    term: "anuria",
    normalizedTerm: "anuria",
    pronunciationText: "an-YUR-ee-uh",
    plainMeaning: "no urine output",
    shortDefinition: "absence of urine production or near absence of urine output",
    bodySystem: "renal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-inflammatory-a-prefix", text: "a-", meaning: "without; not" },
      { partId: "part-uria-suffix", text: "-uria", meaning: "urine condition; urination" },
    ],
    prerequisiteIds: ["part-batch-inflammatory-a-prefix", "part-uria-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-urine-output"],
    lessonIds: ["lesson-batch-fluid-urine-output"],
    tags: ["unit-1", "urine-family", "renal"],
  },
  {
    id: "term-batch-fluid-nocturia",
    term: "nocturia",
    normalizedTerm: "nocturia",
    pronunciationText: "nok-TOOR-ee-uh",
    plainMeaning: "urinating often at night",
    shortDefinition: "waking at night to urinate",
    bodySystem: "renal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-fluid-noct-combining", text: "noct/o", meaning: "night" },
      { partId: "part-uria-suffix", text: "-uria", meaning: "urine condition; urination" },
    ],
    prerequisiteIds: ["part-batch-fluid-noct-combining", "part-uria-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-urine-output"],
    lessonIds: ["lesson-batch-fluid-urine-output"],
    tags: ["unit-1", "urine-family", "renal"],
  },
  {
    id: "term-batch-fluid-pyuria",
    term: "pyuria",
    normalizedTerm: "pyuria",
    pronunciationText: "pie-YUR-ee-uh",
    plainMeaning: "pus in the urine",
    shortDefinition: "white cells or pus present in urine",
    bodySystem: "renal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-fluid-py-combining", text: "py/o", meaning: "pus" },
      { partId: "part-uria-suffix", text: "-uria", meaning: "urine condition; urination" },
    ],
    prerequisiteIds: ["part-batch-fluid-py-combining", "part-uria-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-urine-output"],
    lessonIds: ["lesson-batch-fluid-urine-output"],
    tags: ["unit-1", "urine-family", "renal"],
  },
  {
    id: "term-batch-fluid-glycosuria",
    term: "glycosuria",
    normalizedTerm: "glycosuria",
    pronunciationText: "gly-koh-SYUR-ee-uh",
    plainMeaning: "glucose in the urine",
    shortDefinition: "sugar present in the urine",
    bodySystem: "endocrine",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-glyc-combining", text: "glyc/o", meaning: "sugar; glucose" },
      { partId: "part-uria-suffix", text: "-uria", meaning: "urine condition; urination" },
    ],
    prerequisiteIds: ["part-glyc-combining", "part-uria-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-urine-output"],
    lessonIds: ["lesson-batch-fluid-urine-output"],
    tags: ["unit-1", "urine-family", "endocrine"],
  },
  {
    id: "term-batch-fluid-bacteriuria",
    term: "bacteriuria",
    normalizedTerm: "bacteriuria",
    pronunciationText: "bak-teer-ee-YUR-ee-uh",
    plainMeaning: "bacteria in the urine",
    shortDefinition: "bacteria present in a urine sample",
    bodySystem: "renal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-fluid-bacteri-combining", text: "bacteri/o", meaning: "bacteria" },
      { partId: "part-uria-suffix", text: "-uria", meaning: "urine condition; urination" },
    ],
    prerequisiteIds: ["part-batch-fluid-bacteri-combining", "part-uria-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-urine-output"],
    lessonIds: ["lesson-batch-fluid-urine-output"],
    tags: ["unit-1", "urine-family", "renal"],
  },
  {
    id: "term-batch-fluid-ketonuria",
    term: "ketonuria",
    normalizedTerm: "ketonuria",
    pronunciationText: "kee-toh-NYUR-ee-uh",
    plainMeaning: "ketones in the urine",
    shortDefinition: "ketone bodies present in urine",
    bodySystem: "endocrine",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-fluid-keton-combining", text: "keton/o", meaning: "ketones" },
      { partId: "part-uria-suffix", text: "-uria", meaning: "urine condition; urination" },
    ],
    prerequisiteIds: ["part-batch-fluid-keton-combining", "part-uria-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-urine-output"],
    lessonIds: ["lesson-batch-fluid-urine-output"],
    tags: ["unit-1", "urine-family", "endocrine"],
  },
  {
    id: "term-batch-fluid-hematemesis",
    term: "hematemesis",
    normalizedTerm: "hematemesis",
    pronunciationText: "hee-mat-EM-eh-sis",
    plainMeaning: "vomiting blood",
    shortDefinition: "vomiting of blood from the upper gastrointestinal tract",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-hemat-combining", text: "hemat/o", meaning: "blood" },
      { partId: "part-batch-fluid-emesis-suffix", text: "-emesis", meaning: "vomiting" },
    ],
    prerequisiteIds: ["part-hemat-combining", "part-batch-fluid-emesis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-blood-out"],
    lessonIds: ["lesson-batch-fluid-blood-out"],
    tags: ["unit-1", "bleeding-family", "gastrointestinal"],
  },
  {
    id: "term-batch-fluid-hemoptysis",
    term: "hemoptysis",
    normalizedTerm: "hemoptysis",
    pronunciationText: "hee-MOP-tih-sis",
    plainMeaning: "coughing up blood",
    shortDefinition: "spitting or coughing up blood from the respiratory tract",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-hem-combining", text: "hem/o", meaning: "blood" },
      { partId: "part-batch-fluid-ptysis-suffix", text: "-ptysis", meaning: "spitting; coughing up" },
    ],
    prerequisiteIds: ["part-hem-combining", "part-batch-fluid-ptysis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-blood-out"],
    lessonIds: ["lesson-batch-fluid-blood-out"],
    tags: ["unit-1", "bleeding-family", "respiratory"],
  },
  {
    id: "term-batch-fluid-hyperemesis",
    term: "hyperemesis",
    normalizedTerm: "hyperemesis",
    pronunciationText: "hy-per-EM-eh-sis",
    plainMeaning: "excessive vomiting",
    shortDefinition: "severe or persistent vomiting",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-hyper-prefix", text: "hyper-", meaning: "too much; above normal" },
      { partId: "part-batch-fluid-emesis-suffix", text: "-emesis", meaning: "vomiting" },
    ],
    prerequisiteIds: ["part-hyper-prefix", "part-batch-fluid-emesis-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-blood-out"],
    lessonIds: ["lesson-batch-fluid-blood-out"],
    tags: ["unit-1", "bleeding-family", "gastrointestinal"],
  },
  {
    id: "term-batch-fluid-epistaxis",
    term: "epistaxis",
    normalizedTerm: "epistaxis",
    pronunciationText: "ep-ih-STAK-sis",
    plainMeaning: "nosebleed",
    shortDefinition: "bleeding from the nose",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-batch-fluid-blood-out"],
    lessonIds: ["lesson-batch-fluid-blood-out"],
    tags: ["unit-1", "bleeding-family", "recognition-first"],
  },
  {
    id: "term-batch-fluid-melena",
    term: "melena",
    normalizedTerm: "melena",
    pronunciationText: "meh-LEE-nuh",
    plainMeaning: "black tarry stool from digested blood",
    shortDefinition: "dark stool caused by digested blood in the gastrointestinal tract",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-batch-fluid-blood-out"],
    lessonIds: ["lesson-batch-fluid-blood-out"],
    tags: ["unit-1", "bleeding-family", "recognition-first"],
  },
  {
    id: "term-batch-fluid-hematochezia",
    term: "hematochezia",
    normalizedTerm: "hematochezia",
    pronunciationText: "hee-mat-oh-KEE-zee-uh",
    plainMeaning: "passing bright blood in stool",
    shortDefinition: "visible fresh blood passed through the rectum",
    bodySystem: "gastrointestinal",
    difficulty: 3,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "partial",
    parts: [
      { partId: "part-hemat-combining", text: "hemat/o", meaning: "blood" },
      { partId: "part-batch-fluid-chezia-suffix", text: "-chezia", meaning: "passage of stool" },
    ],
    prerequisiteIds: ["part-hemat-combining", "part-batch-fluid-chezia-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-blood-out"],
    lessonIds: ["lesson-batch-fluid-blood-out"],
    tags: ["unit-1", "bleeding-family", "gastrointestinal"],
  },
  {
    id: "term-batch-fluid-otorrhea",
    term: "otorrhea",
    normalizedTerm: "otorrhea",
    pronunciationText: "oh-toh-REE-uh",
    plainMeaning: "ear discharge",
    shortDefinition: "fluid draining from the ear",
    bodySystem: "otologic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-ot-combining", text: "ot/o", meaning: "ear" },
      { partId: "part-rrhea-suffix", text: "-rrhea", meaning: "flow; discharge" },
    ],
    prerequisiteIds: ["part-ot-combining", "part-rrhea-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-discharge-flow"],
    lessonIds: ["lesson-batch-fluid-discharge-flow"],
    tags: ["unit-1", "discharge-family", "otologic"],
  },
  {
    id: "term-batch-fluid-diarrhea",
    term: "diarrhea",
    normalizedTerm: "diarrhea",
    pronunciationText: "dye-uh-REE-uh",
    plainMeaning: "frequent loose stool flowing through",
    shortDefinition: "loose, frequent bowel movements",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-batch-fluid-dia-prefix", text: "dia-", meaning: "through; across" },
      { partId: "part-rrhea-suffix", text: "-rrhea", meaning: "flow; discharge" },
    ],
    prerequisiteIds: ["part-batch-fluid-dia-prefix", "part-rrhea-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-discharge-flow"],
    lessonIds: ["lesson-batch-fluid-discharge-flow"],
    tags: ["unit-1", "discharge-family", "gastrointestinal"],
  },
  {
    id: "term-batch-fluid-galactorrhea",
    term: "galactorrhea",
    normalizedTerm: "galactorrhea",
    pronunciationText: "gah-lak-toh-REE-uh",
    plainMeaning: "milk discharge",
    shortDefinition: "milky nipple discharge unrelated to normal lactation",
    bodySystem: "reproductive",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-batch-fluid-galact-combining", text: "galact/o", meaning: "milk" },
      { partId: "part-rrhea-suffix", text: "-rrhea", meaning: "flow; discharge" },
    ],
    prerequisiteIds: ["part-batch-fluid-galact-combining", "part-rrhea-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-discharge-flow"],
    lessonIds: ["lesson-batch-fluid-discharge-flow"],
    tags: ["unit-1", "discharge-family", "reproductive"],
  },
  {
    id: "term-batch-fluid-steatorrhea",
    term: "steatorrhea",
    normalizedTerm: "steatorrhea",
    pronunciationText: "stee-at-oh-REE-uh",
    plainMeaning: "fat in the stool",
    shortDefinition: "fatty stool caused by poor fat absorption",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-batch-fluid-steat-combining", text: "steat/o", meaning: "fat" },
      { partId: "part-rrhea-suffix", text: "-rrhea", meaning: "flow; discharge" },
    ],
    prerequisiteIds: ["part-batch-fluid-steat-combining", "part-rrhea-suffix"],
    prerequisiteLessonIds: ["lesson-batch-fluid-discharge-flow"],
    lessonIds: ["lesson-batch-fluid-discharge-flow"],
    tags: ["unit-1", "discharge-family", "gastrointestinal"],
  },
];
