import type { Term } from "../../types/content";

export const terms: Term[] = [
  {
    id: "term-cardiology",
    term: "cardiology",
    normalizedTerm: "cardiology",
    pronunciationText: "kar-dee-OL-uh-jee",
    plainMeaning: "the study of the heart",
    shortDefinition: "the medical study of heart structure and function",
    bodySystem: "cardiovascular",
    difficulty: 1,
    frequencyBand: "core",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-cardi-root", text: "cardi", meaning: "heart" },
      { partId: "part-ology-suffix", text: "-logy", meaning: "study of" }
    ],
    prerequisiteIds: ["part-cardi-root", "part-ology-suffix"],
    prerequisiteLessonIds: ["lesson-unit0-word-parts"],
    lessonIds: ["lesson-unit0-word-parts"],
    tags: ["unit-0", "decoding"],
  },
  {
    id: "term-neurology",
    term: "neurology",
    normalizedTerm: "neurology",
    pronunciationText: "nyoor-OL-uh-jee",
    plainMeaning: "the study of the nervous system",
    shortDefinition: "the medical specialty focused on nerves and the nervous system",
    bodySystem: "nervous",
    difficulty: 1,
    frequencyBand: "core",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-neur-root", text: "neur", meaning: "nerve" },
      { partId: "part-ology-suffix", text: "-logy", meaning: "study of" }
    ],
    prerequisiteIds: ["part-neur-root", "part-ology-suffix"],
    prerequisiteLessonIds: ["lesson-unit0-word-parts"],
    lessonIds: ["lesson-unit0-word-parts"],
    tags: ["unit-0", "decoding"],
  },
  {
    id: "term-diagnosis",
    term: "diagnosis",
    normalizedTerm: "diagnosis",
    pronunciationText: "dy-ag-NOH-sis",
    plainMeaning: "identification of a condition",
    shortDefinition: "the act or result of identifying a disease or condition",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit0-plural-patterns"],
    lessonIds: ["lesson-unit0-plural-patterns"],
    tags: ["unit-0", "plural"],
  },
  {
    id: "term-diagnoses",
    term: "diagnoses",
    normalizedTerm: "diagnoses",
    pronunciationText: "dy-ag-NOH-seez",
    plainMeaning: "more than one diagnosis",
    shortDefinition: "the plural form of diagnosis",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit0-plural-patterns"],
    lessonIds: ["lesson-unit0-plural-patterns"],
    tags: ["unit-0", "plural"],
  },
  {
    id: "term-vertebra",
    term: "vertebra",
    normalizedTerm: "vertebra",
    pronunciationText: "VER-tuh-bruh",
    plainMeaning: "one bone in the spine",
    shortDefinition: "a single spinal bone",
    bodySystem: "musculoskeletal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit0-plural-patterns"],
    lessonIds: ["lesson-unit0-plural-patterns"],
    tags: ["unit-0", "plural"],
  },
  {
    id: "term-vertebrae",
    term: "vertebrae",
    normalizedTerm: "vertebrae",
    pronunciationText: "VER-tuh-bray",
    plainMeaning: "more than one vertebra",
    shortDefinition: "the plural form of vertebra",
    bodySystem: "musculoskeletal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit0-plural-patterns"],
    lessonIds: ["lesson-unit0-plural-patterns"],
    tags: ["unit-0", "plural"],
  },
  {
    id: "term-bacterium",
    term: "bacterium",
    normalizedTerm: "bacterium",
    pronunciationText: "bak-TEER-ee-um",
    plainMeaning: "one bacterium",
    shortDefinition: "a single microscopic organism of the bacteria group",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit0-plural-patterns"],
    lessonIds: ["lesson-unit0-plural-patterns"],
    tags: ["unit-0", "plural"],
  },
  {
    id: "term-bacteria",
    term: "bacteria",
    normalizedTerm: "bacteria",
    pronunciationText: "bak-TEER-ee-uh",
    plainMeaning: "more than one bacterium",
    shortDefinition: "the plural form of bacterium",
    bodySystem: "general",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "opaque",
    parts: [],
    prerequisiteIds: [],
    prerequisiteLessonIds: ["lesson-unit0-plural-patterns"],
    lessonIds: ["lesson-unit0-plural-patterns"],
    tags: ["unit-0", "plural"],
  },
  {
    id: "term-gastritis",
    term: "gastritis",
    normalizedTerm: "gastritis",
    pronunciationText: "gas-TRY-tis",
    plainMeaning: "inflammation of the stomach",
    shortDefinition: "irritation or inflammation in the stomach lining",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-gastr-root", text: "gastr", meaning: "stomach" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-gastr-root", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-common-suffixes"],
    lessonIds: ["lesson-unit1-common-suffixes"],
    tags: ["unit-1", "suffix"],
  },
  {
    id: "term-arthritis",
    term: "arthritis",
    normalizedTerm: "arthritis",
    pronunciationText: "ar-THRY-tis",
    plainMeaning: "inflammation of a joint",
    shortDefinition: "joint inflammation or irritation",
    bodySystem: "musculoskeletal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-arthr-combining", text: "arthr/o", meaning: "joint" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-arthr-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    lessonIds: ["lesson-unit1-common-suffixes", "lesson-unit1-core-body-roots"],
    tags: ["unit-1", "suffix", "roots"],
  },
  {
    id: "term-dermatitis",
    term: "dermatitis",
    normalizedTerm: "dermatitis",
    pronunciationText: "der-ma-TYE-tis",
    plainMeaning: "inflammation of the skin",
    shortDefinition: "skin irritation or inflammation",
    bodySystem: "integumentary",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-derm-combining", text: "derm/o", meaning: "skin" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-derm-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    lessonIds: ["lesson-unit1-core-body-roots"],
    tags: ["unit-1", "roots"],
  },
  {
    id: "term-hepatitis",
    term: "hepatitis",
    normalizedTerm: "hepatitis",
    pronunciationText: "hep-uh-TYE-tis",
    plainMeaning: "inflammation of the liver",
    shortDefinition: "liver inflammation",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-hepat-combining", text: "hepat/o", meaning: "liver" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-hepat-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    lessonIds: ["lesson-unit1-core-body-roots"],
    tags: ["unit-1", "roots"],
  },
  {
    id: "term-nephrology",
    term: "nephrology",
    normalizedTerm: "nephrology",
    pronunciationText: "neh-FROL-uh-jee",
    plainMeaning: "the study of the kidneys",
    shortDefinition: "the medical study or specialty focused on the kidneys",
    bodySystem: "urinary",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-nephr-combining", text: "nephr/o", meaning: "kidney" },
      { partId: "part-ology-suffix", text: "-logy", meaning: "study of" }
    ],
    prerequisiteIds: ["part-nephr-combining", "part-ology-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    lessonIds: ["lesson-unit1-core-body-roots"],
    tags: ["unit-1", "roots"],
  },
  {
    id: "term-hematology",
    term: "hematology",
    normalizedTerm: "hematology",
    pronunciationText: "hee-muh-TOL-uh-jee",
    plainMeaning: "the study of blood",
    shortDefinition: "the medical study or specialty focused on blood",
    bodySystem: "hematologic",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-hemat-combining", text: "hemat/o", meaning: "blood" },
      { partId: "part-ology-suffix", text: "-logy", meaning: "study of" }
    ],
    prerequisiteIds: ["part-hemat-combining", "part-ology-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    lessonIds: ["lesson-unit1-core-body-roots"],
    tags: ["unit-1", "roots"],
  },
  {
    id: "term-neuralgia",
    term: "neuralgia",
    normalizedTerm: "neuralgia",
    pronunciationText: "nyoor-AL-jee-uh",
    plainMeaning: "nerve pain",
    shortDefinition: "pain that follows the course of a nerve",
    bodySystem: "nervous",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-neur-root", text: "neur", meaning: "nerve" },
      { partId: "part-algia-suffix", text: "-algia", meaning: "pain" }
    ],
    prerequisiteIds: ["part-neur-root", "part-algia-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-core-body-roots"],
    lessonIds: ["lesson-unit1-core-body-roots"],
    tags: ["unit-1", "roots"],
  },
  {
    id: "term-hypertension",
    term: "hypertension",
    normalizedTerm: "hypertension",
    pronunciationText: "hy-per-TEN-shun",
    plainMeaning: "blood pressure that is too high",
    shortDefinition: "abnormally high blood pressure",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-hyper-prefix", text: "hyper-", meaning: "too much" }
    ],
    prerequisiteIds: ["part-hyper-prefix"],
    prerequisiteLessonIds: ["lesson-unit1-common-prefixes"],
    lessonIds: ["lesson-unit1-common-prefixes"],
    tags: ["unit-1", "prefix"],
  },
  {
    id: "term-hypotension",
    term: "hypotension",
    normalizedTerm: "hypotension",
    pronunciationText: "hy-poh-TEN-shun",
    plainMeaning: "blood pressure that is too low",
    shortDefinition: "abnormally low blood pressure",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [
      { partId: "part-hypo-prefix", text: "hypo-", meaning: "too little" }
    ],
    prerequisiteIds: ["part-hypo-prefix"],
    prerequisiteLessonIds: ["lesson-unit1-common-prefixes"],
    lessonIds: ["lesson-unit1-common-prefixes"],
    tags: ["unit-1", "prefix"],
  },
  {
    id: "term-tachycardia",
    term: "tachycardia",
    normalizedTerm: "tachycardia",
    pronunciationText: "tak-ee-KAR-dee-uh",
    plainMeaning: "a heart rate that is too fast",
    shortDefinition: "an abnormally fast heart rate",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-tachy-prefix", text: "tachy-", meaning: "fast" },
      { partId: "part-cardi-root", text: "cardi", meaning: "heart" }
    ],
    prerequisiteIds: ["part-tachy-prefix", "part-cardi-root"],
    prerequisiteLessonIds: ["lesson-unit1-rate-prefixes"],
    lessonIds: ["lesson-unit1-rate-prefixes"],
    tags: ["unit-1", "prefix"],
  },
  {
    id: "term-bradycardia",
    term: "bradycardia",
    normalizedTerm: "bradycardia",
    pronunciationText: "bray-dee-KAR-dee-uh",
    plainMeaning: "a heart rate that is too slow",
    shortDefinition: "an abnormally slow heart rate",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-brady-prefix", text: "brady-", meaning: "slow" },
      { partId: "part-cardi-root", text: "cardi", meaning: "heart" }
    ],
    prerequisiteIds: ["part-brady-prefix", "part-cardi-root"],
    prerequisiteLessonIds: ["lesson-unit1-rate-prefixes"],
    lessonIds: ["lesson-unit1-rate-prefixes"],
    tags: ["unit-1", "prefix"],
  },
  {
    id: "term-appendectomy",
    term: "appendectomy",
    normalizedTerm: "appendectomy",
    pronunciationText: "ah-pen-DEK-toh-mee",
    plainMeaning: "surgical removal of the appendix",
    shortDefinition: "an operation to remove the appendix",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-appendic-combining", text: "appendic/o", meaning: "appendix" },
      { partId: "part-ectomy-suffix", text: "-ectomy", meaning: "surgical removal" }
    ],
    prerequisiteIds: ["part-appendic-combining", "part-ectomy-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-procedure-language"],
    lessonIds: ["lesson-unit1-procedure-language"],
    tags: ["unit-1", "procedures"],
  },
  {
    id: "term-colonoscopy",
    term: "colonoscopy",
    normalizedTerm: "colonoscopy",
    pronunciationText: "koh-luh-NOS-kuh-pee",
    plainMeaning: "viewing the colon with a scope",
    shortDefinition: "a procedure that uses a scope to look at the colon",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-col-combining", text: "col/o", meaning: "colon" },
      { partId: "part-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" }
    ],
    prerequisiteIds: ["part-col-combining", "part-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-procedure-language"],
    lessonIds: ["lesson-unit1-procedure-language"],
    tags: ["unit-1", "procedures"],
  },
  {
    id: "term-gastrotomy",
    term: "gastrotomy",
    normalizedTerm: "gastrotomy",
    pronunciationText: "gas-TROT-oh-mee",
    plainMeaning: "an incision into the stomach",
    shortDefinition: "a surgical cut into the stomach",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-gastr-root", text: "gastr", meaning: "stomach" },
      { partId: "part-otomy-suffix", text: "-otomy", meaning: "incision into" }
    ],
    prerequisiteIds: ["part-gastr-root", "part-otomy-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-procedure-language"],
    lessonIds: ["lesson-unit1-procedure-language"],
    tags: ["unit-1", "procedures"],
  },
  {
    id: "term-cardiogram",
    term: "cardiogram",
    normalizedTerm: "cardiogram",
    pronunciationText: "KAR-dee-oh-gram",
    plainMeaning: "a record or image of heart activity",
    shortDefinition: "a graphic record related to heart activity",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-cardi-root", text: "cardi", meaning: "heart" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" }
    ],
    prerequisiteIds: ["part-cardi-root", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-unit1-procedure-language"],
    lessonIds: ["lesson-unit1-procedure-language"],
    tags: ["unit-1", "procedures"],
  },
  {
    id: "term-angiogram",
    term: "angiogram",
    normalizedTerm: "angiogram",
    pronunciationText: "AN-jee-oh-gram",
    plainMeaning: "a record or image of a vessel",
    shortDefinition: "an imaging record that shows blood vessels",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-angi-combining", text: "angi/o", meaning: "vessel" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" }
    ],
    prerequisiteIds: ["part-angi-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-cardiovascular-starter"],
    lessonIds: ["lesson-unit2-cardiovascular-starter"],
    tags: ["unit-2", "cardiovascular"],
  },
  {
    id: "term-arteritis",
    term: "arteritis",
    normalizedTerm: "arteritis",
    pronunciationText: "ar-ter-EYE-tis",
    plainMeaning: "inflammation of an artery",
    shortDefinition: "artery inflammation",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-arteri-combining", text: "arteri/o", meaning: "artery" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-arteri-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-cardiovascular-starter"],
    lessonIds: ["lesson-unit2-cardiovascular-starter"],
    tags: ["unit-2", "cardiovascular"],
  },
  {
    id: "term-venogram",
    term: "venogram",
    normalizedTerm: "venogram",
    pronunciationText: "VEE-noh-gram",
    plainMeaning: "a record or image of a vein",
    shortDefinition: "an imaging record that shows a vein or veins",
    bodySystem: "cardiovascular",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-ven-combining", text: "ven/o", meaning: "vein" },
      { partId: "part-gram-suffix", text: "-gram", meaning: "record or image" }
    ],
    prerequisiteIds: ["part-ven-combining", "part-gram-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-cardiovascular-starter"],
    lessonIds: ["lesson-unit2-cardiovascular-starter"],
    tags: ["unit-2", "cardiovascular"],
  },
  {
    id: "term-bronchitis",
    term: "bronchitis",
    normalizedTerm: "bronchitis",
    pronunciationText: "brong-KYE-tis",
    plainMeaning: "inflammation of the bronchial tubes",
    shortDefinition: "airway irritation or inflammation in the larger breathing tubes",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-bronch-combining", text: "bronch/o", meaning: "bronchial tube" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-bronch-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-airway-language"],
    lessonIds: ["lesson-unit2-respiratory-airway-language"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-bronchoscopy",
    term: "bronchoscopy",
    normalizedTerm: "bronchoscopy",
    pronunciationText: "bron-KOS-kuh-pee",
    plainMeaning: "viewing the airways with a scope",
    shortDefinition: "a scoped look inside the bronchial tubes",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-bronch-combining", text: "bronch/o", meaning: "bronchial tube" },
      { partId: "part-scopy-suffix", text: "-scopy", meaning: "viewing with a scope" }
    ],
    prerequisiteIds: ["part-bronch-combining", "part-scopy-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-airway-language"],
    lessonIds: ["lesson-unit2-respiratory-airway-language"],
    tags: ["unit-2", "respiratory", "procedures"],
  },
  {
    id: "term-tracheotomy",
    term: "tracheotomy",
    normalizedTerm: "tracheotomy",
    pronunciationText: "tray-kee-OT-oh-mee",
    plainMeaning: "an incision into the windpipe",
    shortDefinition: "a surgical cut into the trachea",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-trache-combining", text: "trache/o", meaning: "trachea" },
      { partId: "part-otomy-suffix", text: "-otomy", meaning: "incision into" }
    ],
    prerequisiteIds: ["part-trache-combining", "part-otomy-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-airway-language"],
    lessonIds: ["lesson-unit2-respiratory-airway-language"],
    tags: ["unit-2", "respiratory", "procedures"],
  },
  {
    id: "term-pulmonary",
    term: "pulmonary",
    normalizedTerm: "pulmonary",
    pronunciationText: "PUL-muh-ner-ee",
    plainMeaning: "related to the lungs",
    shortDefinition: "describing the lungs or lung function",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [{ partId: "part-pulmon-combining", text: "pulmon/o", meaning: "lung" }],
    prerequisiteIds: ["part-pulmon-combining"],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-airway-language"],
    lessonIds: ["lesson-unit2-respiratory-airway-language"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-pneumonia",
    term: "pneumonia",
    normalizedTerm: "pneumonia",
    pronunciationText: "new-MOHN-yuh",
    plainMeaning: "a lung infection",
    shortDefinition: "infection or inflammation affecting the lungs",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "partial",
    parts: [{ partId: "part-pneum-combining", text: "pneum/o", meaning: "lung" }],
    prerequisiteIds: ["part-pneum-combining"],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-airway-language"],
    lessonIds: ["lesson-unit2-respiratory-airway-language"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-tachypnea",
    term: "tachypnea",
    normalizedTerm: "tachypnea",
    pronunciationText: "tak-ik-NEE-uh",
    plainMeaning: "breathing that is too fast",
    shortDefinition: "an abnormally fast breathing rate",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-tachy-prefix", text: "tachy-", meaning: "fast" },
      { partId: "part-pnea-suffix", text: "-pnea", meaning: "breathing" }
    ],
    prerequisiteIds: ["part-tachy-prefix", "part-pnea-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-bradypnea",
    term: "bradypnea",
    normalizedTerm: "bradypnea",
    pronunciationText: "brad-ik-NEE-uh",
    plainMeaning: "breathing that is too slow",
    shortDefinition: "an abnormally slow breathing rate",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-brady-prefix", text: "brady-", meaning: "slow" },
      { partId: "part-pnea-suffix", text: "-pnea", meaning: "breathing" }
    ],
    prerequisiteIds: ["part-brady-prefix", "part-pnea-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-dyspnea",
    term: "dyspnea",
    normalizedTerm: "dyspnea",
    pronunciationText: "DISP-nee-uh",
    plainMeaning: "difficult breathing; shortness of breath",
    shortDefinition: "breathing that feels hard or uncomfortable",
    bodySystem: "respiratory",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-dys-prefix", text: "dys-", meaning: "difficult or abnormal" },
      { partId: "part-pnea-suffix", text: "-pnea", meaning: "breathing" }
    ],
    prerequisiteIds: ["part-dys-prefix", "part-pnea-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-hypoxia",
    term: "hypoxia",
    normalizedTerm: "hypoxia",
    pronunciationText: "hy-POK-see-uh",
    plainMeaning: "oxygen that is too low",
    shortDefinition: "lower-than-normal oxygen available to the body or tissues",
    bodySystem: "respiratory",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-hypo-prefix", text: "hypo-", meaning: "too little" },
      { partId: "part-oxia-suffix", text: "-oxia", meaning: "oxygen state" }
    ],
    prerequisiteIds: ["part-hypo-prefix", "part-oxia-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-respiratory-breathing-status"],
    lessonIds: ["lesson-unit2-respiratory-breathing-status"],
    tags: ["unit-2", "respiratory"],
  },
  {
    id: "term-enteritis",
    term: "enteritis",
    normalizedTerm: "enteritis",
    pronunciationText: "en-ter-EYE-tis",
    plainMeaning: "inflammation of the intestine",
    shortDefinition: "inflammation or irritation in the intestines",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-enter-combining", text: "enter/o", meaning: "intestine" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-enter-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-gastrointestinal-inflammation"],
    lessonIds: ["lesson-unit2-gastrointestinal-inflammation"],
    tags: ["unit-2", "gastrointestinal"],
  },
  {
    id: "term-gastroenteritis",
    term: "gastroenteritis",
    normalizedTerm: "gastroenteritis",
    pronunciationText: "gas-troh-en-ter-EYE-tis",
    plainMeaning: "inflammation involving the stomach and intestines",
    shortDefinition: "an illness that irritates both the stomach and intestines",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-gastr-root", text: "gastr", meaning: "stomach" },
      { partId: "part-enter-combining", text: "enter/o", meaning: "intestine" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-gastr-root", "part-enter-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-gastrointestinal-inflammation"],
    lessonIds: ["lesson-unit2-gastrointestinal-inflammation"],
    tags: ["unit-2", "gastrointestinal"],
  },
  {
    id: "term-esophagitis",
    term: "esophagitis",
    normalizedTerm: "esophagitis",
    pronunciationText: "ee-sof-uh-JYE-tis",
    plainMeaning: "inflammation of the esophagus",
    shortDefinition: "irritation or inflammation in the swallowing tube",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "extended",
    sourceType: "pedagogic",
    compositionality: "full",
    parts: [
      { partId: "part-esophag-combining", text: "esophag/o", meaning: "esophagus" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-esophag-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-gastrointestinal-inflammation"],
    lessonIds: ["lesson-unit2-gastrointestinal-inflammation"],
    tags: ["unit-2", "gastrointestinal"],
  },
  {
    id: "term-colitis",
    term: "colitis",
    normalizedTerm: "colitis",
    pronunciationText: "koh-LYE-tis",
    plainMeaning: "inflammation of the colon",
    shortDefinition: "colon inflammation",
    bodySystem: "gastrointestinal",
    difficulty: 1,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-col-combining", text: "col/o", meaning: "colon" },
      { partId: "part-itis-suffix", text: "-itis", meaning: "inflammation" }
    ],
    prerequisiteIds: ["part-col-combining", "part-itis-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-gastrointestinal-inflammation"],
    lessonIds: ["lesson-unit2-gastrointestinal-inflammation"],
    tags: ["unit-2", "gastrointestinal"],
  },
  {
    id: "term-cholecystectomy",
    term: "cholecystectomy",
    normalizedTerm: "cholecystectomy",
    pronunciationText: "koh-lee-sis-TEK-toh-mee",
    plainMeaning: "surgical removal of the gallbladder",
    shortDefinition: "an operation to remove the gallbladder",
    bodySystem: "gastrointestinal",
    difficulty: 2,
    frequencyBand: "common",
    sourceType: "lay_exposure",
    compositionality: "full",
    parts: [
      { partId: "part-cholecyst-combining", text: "cholecyst/o", meaning: "gallbladder" },
      { partId: "part-ectomy-suffix", text: "-ectomy", meaning: "surgical removal" }
    ],
    prerequisiteIds: ["part-cholecyst-combining", "part-ectomy-suffix"],
    prerequisiteLessonIds: ["lesson-unit2-gastrointestinal-procedures"],
    lessonIds: ["lesson-unit2-gastrointestinal-procedures"],
    tags: ["unit-2", "gastrointestinal", "procedures"],
  }
];
